#!/usr/bin/env bash
# build_blob.sh — regenerate the TAD combined audio-data blob (P3: the consolidated
# 21-song project with real FM/drum samples; override with TAD_PROJECT= for tests).
#
# Output blob layout (self-contained, from `tad-compiler ca65-export --output-bin`):
#   [ loader.bin (116) ][ audio-driver.bin (3218) ][ Tad_DataTable ][ common + songs ]
# The Poppy port + build_interp_rom.py .incbin THIS single file (no separate driver blobs needed).
#
# Reproducibility pins (see vendor/VERSION.md): TAD @ 822164b, tad-compiler 0.3.0, cc65 V2.18.
set -euo pipefail
cd "$(dirname "$0")"                       # soundwork/tad

TC="${TAD_COMPILER:-/home/chad/terrific-audio-driver/target/release/tad-compiler}"
PROJECT="${TAD_PROJECT:-mml_drafts/superman_all.terrificaudio}"   # P3 consolidated project
OUT=build
mkdir -p "$OUT"

echo "[build_blob] project=$PROJECT"
"$TC" check "$PROJECT"
# HIROM to match build/interp.sfc. Segment name is irrelevant to the .bin (only labels the .s wrapper).
"$TC" ca65-export --hirom --segment RODATA2 \
    --output-asm "$OUT/audio-data.s" \
    --output-bin "$OUT/audio-data.bin" \
    "$PROJECT"
"$TC" ca65-enums -o "$OUT/audio.inc" "$PROJECT"

echo "[build_blob] wrote:"
ls -l "$OUT/audio-data.bin" "$OUT/audio-data.s" "$OUT/audio.inc"
echo "[build_blob] blob size = $(wc -c < "$OUT/audio-data.bin") bytes"

# Generate the Poppy blob-symbol equates consumed by port/tad_glue.pasm (concatenated
# before it by tools/build_interp.sh). The blob is .incbin'd at $ED:002B — segment
# offset 43, matching stock ca65's [43-byte LoadAudioData][blob] layout — so the
# DataTable's segment-relative u24 entries are usable UNSKEWED: far addr = $ED:0000 +
# entry, linear across banks $ED/$EE/... (HiROM $C0-$FF is file-linear). This replaces
# P1's single-bank DATA_SEGMENT_SKEW=43 subtraction (whose borrow never propagated to
# the bank byte — broken for a >64KB blob).
python3 - "$OUT" <<'EOF'
import re, sys
from pathlib import Path
out = Path(sys.argv[1])
s = (out / "audio-data.s").read_text()
drv_off  = int(re.search(r"Tad_AudioDriver_Bin := __Tad_AudioData_0 \+ (\d+)", s).group(1))
drv_size = int(re.search(r"Tad_AudioDriver_SIZE = (\d+)", s).group(1))
ldr_size = int(re.search(r"Tad_Loader_SIZE = (\d+)", s).group(1))
dt_off   = int(re.search(r"Tad_DataTable := __Tad_AudioData_0 \+ (\d+)", s).group(1))
n_items  = int(re.search(r"N_DATA_ITEMS = (\d+)", s).group(1))
base = 0xED0000 + 0x2B          # blob incbin address (segment offset 43)
blob = len((out / "audio-data.bin").read_bytes())
banks = (0x2B + blob + 0xFFFF) // 0x10000
(out / "tad_blob_syms.pasm").write_text(f"""\
; GENERATED by build_blob.sh — blob-derived symbols for tad_glue.pasm. Do not edit.
; blob = {blob} bytes @ 5A22 $ED:002B (file $2D002B), spans {banks} bank(s).
AUDIO_DATA_BANK      = $ED
Tad_Loader_Bin       = ${base:06X}
Tad_Loader_SIZE      = {ldr_size}
Tad_AudioDriver_Bin  = ${base + drv_off:06X}
Tad_AudioDriver_SIZE = ${drv_size:04X}
Tad_DataTable        = ${base + dt_off:06X}
N_DATA_ITEMS         = {n_items}
""")
print(f"[build_blob] tad_blob_syms.pasm: DataTable=${base+dt_off:06X} items={n_items} ({banks} bank(s))")
EOF
