#!/usr/bin/env python3
"""
Build the full-ROM 68K-interpreter harness: a 1MB HiROM .sfc embedding the
65816 interpreter (file $8000, CPU $00/$C0:8000-FFFF) + the entire 512KB 68K
program image (file $10000, CPU $C1:0000+ — so 68K addr A reads flat at $C10000+A).
Load this in Mesen (MESEN_ROM) to let the interpreter follow cross-ROM control flow.
"""
from pathlib import Path

INTERP = Path("src/interp.bin").read_bytes()        # 32KB ($8000-$FFFF)
IMG = Path("data/superman_m68k.bin").read_bytes()   # 512KB 68K program
GFX = Path("tools/mame-trace/gfx1.bin").read_bytes() # 2MB arcade tile ROM (16x16 planar 4bpp)
assert len(INTERP) == 0x8000, len(INTERP)
assert len(IMG) == 0x80000, len(IMG)
assert len(GFX) == 0x200000, len(GFX)

# 4MB HiROM: interp @ $C0:8000, 68K image @ $C1:0000 (file $10000), arcade tile ROM
# gfx1 @ $C9:0000 (file $90000) so the runtime tile decoder reads gfx[code*1024+off]
# at flat CPU address $C90000 + code*1024.
ROM = bytearray(0x400000)                            # 4MB HiROM
ROM[0x8000:0x10000] = INTERP                         # interpreter + vectors @ $00/$C0:8000
ROM[0x10000:0x90000] = IMG                           # 68K image @ $C1:0000 (flat $C10000+A)
ROM[0x90000:0x290000] = GFX                          # arcade tiles @ $C9:0000 (flat $C90000+off)
VID = Path("src/video.bin").read_bytes()             # video subsystem (assembled @ $8000)
assert len(VID) <= 0x8000, len(VID)
ROM[0x298000:0x298000+len(VID)] = VID                # @ $E9:8000 (file $298000); jsl/jml VID_*

# --- SA-1 ESCAPE BANK ---
# Native transpiled escapes too big for bank $00's free gaps live here. File $290000 is the
# 32KB gap between the gfx tile ROM (ends $290000) and the video subsystem ($298000). The SA-1's
# default MMC maps file $200000-$2FFFFF -> $80-$9F:8000-FFFF (Sa1.cpp), so file $290000 = SA-1
# $92:8000 (segment 2, bank $80 + ($90000/$8000=18) = $92). The interp dispatches here with
# `jml $92:8000`; escapes return `jml inext` and call bank-$00 leaf helpers via `jsl <h>_l`.
# escbank.pasm is assembled @ .org $8000, so escbank_entry ($8000) -> file $290000 = $92:8000.
import os.path as _osp
if _osp.exists("src/escbank.bin"):
    ESC = Path("src/escbank.bin").read_bytes()
    assert len(ESC) <= 0x8000, ("escape bank %d bytes overflows the $290000..$298000 gap" % len(ESC))
    ROM[0x290000:0x290000+len(ESC)] = ESC            # @ SA-1 $92:8000 (file $290000)

# --- SECOND SA-1 ESCAPE BANK ($94:8000, file $2A0000) ---
# The $92 bank's bodies region filled to $F000 (jah2 dispatch chains). file $2A0000 is free (after
# VID at $298000-$2A0000) and the SA-1 MMC maps it to $94:8000 (file $200000-$2FFFFF -> $80-$9F;
# ($A0000/$8000=20)+$80=$94). Confirmed by a live marker read. escbank2.pasm is .org $8000, so
# escbank2 $8000 -> file $2A0000 -> $94:8000. $92 dispatchers `jml entry_X` into it.
if _osp.exists("src/escbank2.bin"):
    ESC2 = Path("src/escbank2.bin").read_bytes()
    assert len(ESC2) <= 0x8000, ("escbank2 %d bytes overflows the $2A0000..$2A8000 bank" % len(ESC2))
    ROM[0x2A0000:0x2A0000+len(ESC2)] = ESC2          # @ SA-1 $94:8000 (file $2A0000)

# --- AOT address-translation table (xlat_dispatch's data; SA-1 $96:8000 = file $2B0000) ---
# 2-level page table 68K PC -> native escape entry, generated by tools/gen_xlat_table.py. Bank $96
# is in the SA-1 MMC window ($80-$9F) and verified live-readable. xlat_dispatch (escbank2 $94:F900)
# indexes it via long addressing; a zero entry = miss = interpret.
if _osp.exists("src/xlat_table.bin"):
    XLAT = Path("src/xlat_table.bin").read_bytes()
    assert len(XLAT) <= 0x8000, ("xlat table %d bytes overflows the $2B0000..$2B8000 bank" % len(XLAT))
    ROM[0x2B0000:0x2B0000+len(XLAT)] = XLAT          # @ SA-1 $96:8000 (file $2B0000)

# --- THIRD SA-1 escape bank ($97:8000, file $2B8000) ---
# entry_25110 (collision, $025110): its 8KB body overflowed its bank-$00 inline gap ($D1ED..$E000)
# and was silently clobbered by the following .org routines. Relocated to this fresh 32KB bank (the
# SA-1 MMC maps file $200000-$2FFFFF -> $80-$9F uniformly, so file $2B8000 = $97:8000, executable
# like $92/$94). Bank $00's dead inline entry_25110 @ $D1ED is redirected here via `jml $978000`.
if _osp.exists("src/escbank4.bin"):
    ESC4 = Path("src/escbank4.bin").read_bytes()
    assert len(ESC4) <= 0x8000, ("escbank4 %d bytes overflows the $2C0000..$2C8000 bank" % len(ESC4))
    ROM[0x2C0000:0x2C0000+len(ESC4)] = ESC4          # @ SA-1 $98:8000 (file $2C0000)
if _osp.exists("src/escbank3.bin"):
    ESC3 = Path("src/escbank3.bin").read_bytes()
    assert len(ESC3) <= 0x8000, ("escbank3 %d bytes overflows the $2B8000..$2C0000 bank" % len(ESC3))
    ROM[0x2B8000:0x2B8000+len(ESC3)] = ESC3          # @ SA-1 $97:8000 (file $2B8000)

# --- FIFTH SA-1 escape bank ($99:8000, file $2C8000) ---
# The $023-25xxx trap#5-cluster SHELL segments (coroutine yield-loop bodies + their callees;
# CP1 item 2.3). Resume PCs dispatch via bank-$02 xlat pages; $00FA call-bridge sentinel.
if _osp.exists("src/escbank5.bin"):
    ESC5 = Path("src/escbank5.bin").read_bytes()
    assert len(ESC5) <= 0x8000, ("escbank5 %d bytes overflows the $2C8000..$2D0000 bank" % len(ESC5))
    ROM[0x2C8000:0x2C8000+len(ESC5)] = ESC5          # @ SA-1 $99:8000 (file $2C8000)

# --- TAD audio-data blob (sound port P3: 21 songs + real samples, multi-bank) ---
# Self-contained: [loader.bin(116)][audio-driver.bin(3218)][DataTable][common+21 songs]. Placed at
# file $2D002B = 5A22 HiROM $ED:002B — segment offset 43, mirroring stock ca65's
# [43-byte LoadAudioData proc][blob] layout so the DataTable's segment-relative u24 entries resolve
# UNSKEWED (far addr = $ED:0000 + entry; map mode $31 keeps $C0-$FF file-linear across banks
# $ED/$EE/...). The ported LoadAudioData/Tad_Init upload it to the SPC700. Regen with
# soundwork/tad/build_blob.sh (also generates build/tad_blob_syms.pasm for tad_glue.pasm).
if _osp.exists("soundwork/tad/build/audio-data.bin"):
    TADBLOB = Path("soundwork/tad/build/audio-data.bin").read_bytes()
    assert 0x2D002B + len(TADBLOB) <= 0x400000, ("TAD blob %d bytes overflows the ROM" % len(TADBLOB))
    ROM[0x2D002B:0x2D002B+len(TADBLOB)] = TADBLOB     # @ 5A22 $ED:002B (file $2D002B)

# --- SA-1 LoROM mirror of the interpreter ---
# Under the SA-1 cart map, the 5A22 (and the SA-1) see $00-$1F:8000-FFFF as LoROM-style
# (32KB/bank): $00:8000-FFFF -> FILE $0-$7FFF, so $00:FFFC (reset) -> FILE $7FFC and the
# interp's DBR=$00 abs reads of its own ROM data (e.g. RESP1, the C-Chip response) -> FILE
# $0-$7FFF. Plain HiROM mirrored ROM file $8000-FFFF into $00:8000 there; the SA-1 map does
# not. Restore that by mirroring the 32KB interp into FILE $0-$7FFF, so $00:8000 presents a
# full copy of the interpreter + data tables + vectors exactly as the interp was designed
# for (DBR=$00). The 5A22 boots into it at $00:8000 with NO interp.pasm changes; the interp
# also stays reachable at $C0:8000 (HiROM-linear) for when it moves to the SA-1 (Phase A2).
ROM[0x0000:0x8000] = INTERP                          # interp mirror @ $00-$1F:8000 (LoROM)
# A2 boot-flow swap: the 5A22 reset vector ($00:FFFC -> file $7FFC) points at cpu5a22_boot
# ($FC00), NOT the interp reset. The 5A22 bootstraps the SA-1 (CRV=$8000 = interp reset)
# then halts; the SA-1 runs the interpreter. (The mirror set $7FFC = interp reset $8000;
# override it here.)
ROM[0x7FFC] = 0x00; ROM[0x7FFD] = 0xFC               # 5A22 reset vector = $FC00 (cpu5a22_boot)

# HiROM cartridge header at file $FFC0 (= CPU $00:FFC0)
H = 0xFFC0
title = b"SUPERMAN INTERP H>SNES"[:21].ljust(21, b" ")
ROM[H:H+21] = title
# Extended header at $FFB0 (recognized because DeveloperId $FFDA below = $33):
# ExpansionRamSize $FFBD = $06 -> SA-1 BW-RAM = 1024<<6 = 64KB (the shared RAM at
# SNES $40:0000, reachable by both the 5A22 and the SA-1). Without this byte the
# coprocessor RAM is 0 and $40:0000 is unmapped (BaseCartridge.cpp:244).
ROM[0xFFBD] = 0x07      # SA-1 BW-RAM size: 128 KB ($40:0000 work RAM + $41:0000 shadow)
ROM[H+0x15] = 0x31      # map mode: HiROM + FastROM (SA-1 keeps the $C0-$FF linear ROM map)
ROM[H+0x16] = 0x33      # cart type: SA-1 ((RomType&0xF0)>>4==3 -> CoprocessorType::SA1)
ROM[H+0x17] = 0x0C      # ROM size: 4MB (2^12 KB)
ROM[H+0x18] = 0x07      # SRAM size = 128 KB: for SA-1 this IS the BW-RAM (the save RAM,
                        # sized by SramSize $FFD8 -> _saveRamSize; BaseCartridge.cpp:259).
                        # mapSram=false for SA-1 so no conflict; Sa1::Init maps it to
                        # $40-$5F (SA-1) / $40-$4F (5A22). $40:0000=work RAM, $41:0000=shadow.
ROM[H+0x19] = 0x01      # country
ROM[H+0x1A] = 0x33      # licensee
ROM[H+0x1B] = 0x00      # version
# checksum (zero the fields, sum, write complement+checksum)
for i in range(H+0x1C, H+0x20):
    ROM[i] = 0x00
total = sum(ROM) & 0xFFFF
comp = (~total) & 0xFFFF
ROM[H+0x1C] = comp & 0xFF
ROM[H+0x1D] = (comp >> 8) & 0xFF
ROM[H+0x1E] = total & 0xFF
ROM[H+0x1F] = (total >> 8) & 0xFF

out = Path("build/interp.sfc")
out.parent.mkdir(exist_ok=True)
out.write_bytes(ROM)
print(f"wrote {out} ({len(ROM)} bytes, HiROM)")
print(f"reset vector @file $FFFC: ${ROM[0xFFFC]|(ROM[0xFFFD]<<8):04X}")
print(f"68K image @ $C1:0000 (file $10000); 68K reset bytes @ image $3EF0: "
      f"{IMG[0x3EF0:0x3EF6].hex()}")
