#!/usr/bin/env python3
"""Refresh the auto-generated bank-$00 symbol constants in src/escbank.pasm from src/interp.sym.

The escape bank (src/escbank.pasm, runs at SA-1 $92:8000) calls into the bank-$00 interpreter
(jml inext, jsl rdw40_l, ...). Those targets live in interp.pasm, whose addresses SHIFT whenever
interp.pasm changes. Poppy's --pansy-input doesn't export the interp's local labels, so instead
we extract the needed symbols from the -s symbol file and rewrite the marked block in escbank.pasm
as `NAME=$BBAAAA` constants (24-bit so jml/jsl encode the bank byte). Run before assembling escbank.
"""
import re, sys
from pathlib import Path

# bank-$00 interp symbols an escape may reference (jml/jsl targets + rtl-wrappers)
NEEDED = ["inext", "rdw40_l", "wrw40_l", "rdb40_l", "wrb40_l", "push32_l",
          "rdw_ea_l", "readbyte_l", "writeword_l", "writebyte_l", "usmul_l", "op_rts_sentinel", "ojmp_hook",
          "jsrabs_hook",  # jah2_ext (escbank extension chain) tail-calls the original miss handler
          "bhp_after",    # jah2_ext_bsr tail-calls back into bsr_hookpush's miss continuation
          "ors_pre",      # an escbank escape's terminal rts routes here (bank-aware sentinel resume)
          "lh_sched",     # entry_swo (scheduler switch-OUT) tail-jumps into the native $074C scan
          "op_rte",       # entry_swin (scheduler switch-IN) tail: pop SR+PC + ors_rte resume dispatch
          "lh_nofire"]    # entry_swin gate-off/bounds-fail: loop_hook's clc;rts transparent no-fire

sym_path = Path("src/interp.sym")
esc_path = Path("src/escbank.pasm")
if not sym_path.exists():
    sys.exit("gen_escbank_syms: src/interp.sym missing (build interp.bin with -s first)")

# parse "BB:AAAA name" lines
addr = {}
for line in sym_path.read_text(encoding="utf-8-sig").splitlines():
    m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
    if m:
        bank, off, name = m.group(1), m.group(2), m.group(3)
        addr[name] = "$%02X%04X" % (int(bank, 16), int(off, 16))

lines = ["; >>> ESCBANK_SYMS — auto-generated by tools/gen_escbank_syms.py (do not edit) <<<"]
missing = []
for n in NEEDED:
    if n in addr:
        lines.append("%s=%s" % (n, addr[n]))
    else:
        missing.append(n)
# Cross-bank: feed escbank2's entry_X addresses ($94:8000, file $2A0000) so $92 dispatchers can
# `jml entry_X` into the 2nd bank. escbank2.sym is produced by the earlier escbank2 assembly pass.
esc2_sym = Path("src/escbank2.sym")
n2 = 0
if esc2_sym.exists():
    for line in esc2_sym.read_text(encoding="utf-8-sig").splitlines():
        m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(entry_[0-9a-z_]+)", line)
        if m:
            # Poppy assembles escbank2 at .org $8000 reporting bank $00; it actually loads at file
            # $2A0000 = SA-1 $94:8000. Force bank $94 so `jml entry_X` targets the real bank.
            lines.append("%s=$94%04X" % (m.group(3), int(m.group(2), 16)))
            n2 += 1
lines.append("; <<< ESCBANK_SYMS <<<")
block = "\n".join(lines)

src = esc_path.read_text()
pat = re.compile(r"; >>> ESCBANK_SYMS.*?; <<< ESCBANK_SYMS <<<", re.DOTALL)
if pat.search(src):
    src = pat.sub(block, src)
else:
    src = block + "\n\n" + src
esc_path.write_text(src)
print("gen_escbank_syms: wrote %d bank-$00 + %d escbank2 entry_X symbols%s" %
      (len(NEEDED) - len(missing), n2, (" (MISSING: %s)" % missing) if missing else ""))
