#!/usr/bin/env python3
"""Refresh the auto-generated bank-$00 symbol constants in src/escbank2.pasm from src/interp.sym.

escbank2.pasm is the SECOND escape bank (SA-1 $94:8000, file $2A0000; see
[[escbank-overflow-second-bank]]) — for native escapes that no longer fit in $92's bodies region.
Like gen_escbank_syms.py for $92, it pins the bank-$00 jml/jsl targets (whose addresses shift when
interp.pasm changes) into a marked block. esc_udiv is NOT here — escbank2 has its own local copy
(a same-bank `jsr esc_udiv`). ibridge is NOT here — --bank2 bodies inline the interpret-bridge with
a $00FD sentinel (resumes via ors_pre -> ors_94chk -> bank $94) instead of $92's ibridge.
"""
import re, sys
from pathlib import Path

NEEDED = ["inext", "rdw40_l", "wrw40_l", "rdb40_l", "wrb40_l", "push32_l",
          "rdw_ea_l", "readbyte_l", "writeword_l", "writebyte_l", "usmul_l",
          "op_rts_sentinel", "ojmp_hook", "ors_pre"]

sym_path = Path("src/interp.sym")
esc_path = Path("src/escbank2.pasm")
if not sym_path.exists():
    sys.exit("gen_escbank2_syms: src/interp.sym missing (build interp.bin with -s first)")
if not esc_path.exists():
    sys.exit(0)  # escbank2 optional

addr = {}
for line in sym_path.read_text(encoding="utf-8-sig").splitlines():
    m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
    if m:
        bank, off, name = m.group(1), m.group(2), m.group(3)
        addr[name] = "$%02X%04X" % (int(bank, 16), int(off, 16))

lines = ["; >>> ESCBANK2_SYMS — auto-generated by tools/gen_escbank2_syms.py (do not edit) <<<"]
missing = []
for n in NEEDED:
    if n in addr: lines.append("%s=%s" % (n, addr[n]))
    else: missing.append(n)
lines.append("; <<< ESCBANK2_SYMS <<<")
block = "\n".join(lines)

src = esc_path.read_text()
pat = re.compile(r"; >>> ESCBANK2_SYMS.*?; <<< ESCBANK2_SYMS <<<", re.DOTALL)
src = pat.sub(block, src) if pat.search(src) else block + "\n\n" + src
esc_path.write_text(src)
print("gen_escbank2_syms: wrote %d symbols%s" %
      (len(NEEDED) - len(missing), (" (MISSING: %s)" % missing) if missing else ""))
