#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 player coordinate clamp at $013314."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "escbank9.pasm"
TRANSPILE = ROOT / "tools" / "transpile.py"
START = (
    "; >>> STAGE3_13314 — generated by "
    "tools/gen_stage3_13314.py <<<"
)
END = "; <<< STAGE3_13314 <<<"

PC = 0x013314
ORIGIN = 0xD800
LIMIT = 0xE000
INSTRUCTION_COUNT = 23
FLAGS = (
    "--bank7",
    "--table",
    "--exitccr",
    "--xflag",
    "--accharge",
    "--restore-static-residue",
    "--restore-indirect-residue",
    "--bail",
)


def generate() -> str:
    result = subprocess.run(
        [sys.executable, str(TRANSPILE), f"{PC:06X}", *FLAGS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = f"all {INSTRUCTION_COUNT} instrs transpiled"
    if (
        expected not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            f"incomplete ${PC:06X} transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_13314:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = f"""    .org ${ORIGIN:04X}
.a16
.i16
; Reserved island $9F:{ORIGIN:04X}-$9F:{LIMIT - 1:04X}; source PC ${PC:06X}.
entry_13314t:
    rep #$30
    ; Generated direct accesses touch A6 down to -$40.  The faithful RTS
    ; consumes four bytes at A7.  Reject before the first architectural write
    ; unless both complete ranges are canonical mapped work RAM.
    lda $3A
    cmp #$00F0
    bne h13314_cold
    lda $38
    cmp #$0040
    bcc h13314_cold
    cmp #$4000
    bcs h13314_cold
    lda $3E
    cmp #$00F0
    bne h13314_cold
    lda $3C
    cmp #$3FFD
    bcs h13314_cold
    bra h13314_hot
h13314_cold:
    lda #$3314
    sta $40
    lda #$0001
    sta $42
    jml.l inext
h13314_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $013314 table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if "    jsr esc_ac_charge\n" in body:
        raise RuntimeError("$013314 retained a foreign AC helper")
    return body + "\nentry_13314t_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $013314 generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_13314: regenerated $013314@$9F:D800")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
