#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $0278E8 two-record parent."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = "; >>> STAGE3_278E8 — generated by tools/gen_stage3_278e8.py <<<"
END = "; <<< STAGE3_278E8 <<<"
PC = 0x0278E8


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 10 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $0278E8 transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_278e8:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """    .org $D000
.a16
.i16
; Reserved island $9F:D000-$D7FF; source PC $0278E8.
entry_278e8:
    rep #$30
    ; The parent writes A5-relative counters, advances A4 to a second record,
    ; and makes nested calls that push four-byte returns. Reject before the
    ; first architectural change unless every direct range is canonical.
    lda $32
    cmp #$00F0
    bne h278e8_cold
    lda $30
    cmp #$3FC9
    bcs h278e8_cold
    lda $36
    cmp #$00F0
    bne h278e8_cold
    lda $34
    cmp #$0124
    bcs h278e8_cold
    lda $3E
    cmp #$00F0
    bne h278e8_cold
    lda $3C
    cmp #$0004
    bcc h278e8_cold
    cmp #$3FFD
    bcs h278e8_cold
    bra h278e8_hot
h278e8_cold:
    lda #$78E8
    sta $40
    lda #$0002
    sta $42
    jml.l inext
h278e8_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $0278E8 table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace("    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n")
    if body.count("    jsr esc9_ac_charge\n") != 6:
        raise RuntimeError("$0278E8 lost an AC-charge basic block")

    for label, pinned in (
        ("br278e8_1", 0xE3D8),
        ("br278e8_2", 0xE3DC),
        ("br278e8_3", 0xE3E0),
    ):
        bridge = (
            f"    lda #{label}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        replacement = (
            f"    lda #${pinned:04X}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        if body.count(bridge) != 1:
            raise RuntimeError(f"$0278E8 lost callback bridge {label}")
        body = body.replace(bridge, replacement, 1)

    dispatcher_bridge = (
        "    lda #$7912\n"
        "    sta $40\n"
        "    lda #$0002\n"
        "    sta $42\n"
        "    jml.l ojmp_hook\n"
    )
    dispatcher_direct = dispatcher_bridge.replace(
        "    jml.l ojmp_hook\n", "    jml.l $9FA500\n"
    )
    if body.count(dispatcher_bridge) != 2:
        raise RuntimeError("$0278E8 lost its two $027912 child calls")
    body = body.replace(dispatcher_bridge, dispatcher_direct)
    return body + "\nentry_278e8_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $0278E8 generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_278e8: regenerated $0278E8@$9F:D000")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
