#!/usr/bin/env python3
"""Refresh the auto-generated bank-$00 symbol constants in src/escbank4.pasm from src/interp.sym.

escbank4.pasm is the THIRD escape bank (SA-1 $98:8000, file $2C0000) — hosts entry_25110 (collision),
whose 8KB body overflowed its bank-$00 inline gap. Like gen_escbank2_syms.py for $94, it pins the
bank-$00 jml/jsl targets (whose addresses shift when interp.pasm changes) into a marked block. The
--bank2 body's CALL-BRIDGE sentinels are sed'd $00FD->$00FC so the resume goes ors_pre->ors_94chk->
ors_97chk->ors_pre_97 (bank $97) rather than ->ors_pre_94 (bank $94). Same NEEDED symbols as escbank2.
"""
import re, sys
from pathlib import Path

NEEDED = ["inext", "rdw40_l", "wrw40_l", "rdb40_l", "wrb40_l", "push32_l",
          "rdw_ea_l", "readbyte_l", "writeword_l", "writebyte_l", "usmul_l",
          "op_rts_sentinel", "ojmp_hook", "ors_pre"]

sym_path = Path("src/interp.sym")
esc_path = Path("src/escbank4.pasm")
if not sym_path.exists():
    sys.exit("gen_escbank4_syms: src/interp.sym missing (build interp.bin with -s first)")
if not esc_path.exists():
    sys.exit(0)  # escbank4 optional

addr = {}
for line in sym_path.read_text(encoding="utf-8-sig").splitlines():
    m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
    if m:
        bank, off, name = m.group(1), m.group(2), m.group(3)
        addr[name] = "$%02X%04X" % (int(bank, 16), int(off, 16))

lines = ["; >>> ESCBANK3_SYMS — auto-generated by tools/gen_escbank4_syms.py (do not edit) <<<"]
missing = []
for n in NEEDED:
    if n in addr: lines.append("%s=%s" % (n, addr[n]))
    else: missing.append(n)
lines.append("; <<< ESCBANK3_SYMS <<<")
block = "\n".join(lines)

src = esc_path.read_text()
pat = re.compile(r"; >>> ESCBANK3_SYMS.*?; <<< ESCBANK3_SYMS <<<", re.DOTALL)
src = pat.sub(block, src) if pat.search(src) else block + "\n\n" + src
esc_path.write_text(src)
print("gen_escbank4_syms: wrote %d symbols%s" %
      (len(NEEDED) - len(missing), (" (MISSING: %s)" % missing) if missing else ""))
