#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $0079FE/$007AC6 coroutine fast path."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
PROGRAM = ROOT / "data/superman_m68k.bin"
START = (
    "; >>> STAGE3_79FE — generated by tools/gen_stage3_79fe.py <<<"
)
END = "; <<< STAGE3_79FE <<<"


BODY = r"""    .org $BD80
.a16
.i16
; Pages $76/$77 retain the established one-shot fan-out dispatcher.  Page
; $78 is an admitted sparse miss.  Only the exact $0079FE/$007AC6 coroutine
; PCs below are native on pages $79/$7A; every other PC rejoins xd_table.
stage3_79_sparse_dispatch:
    rep #$30
    lda $40
    xba
    and #$00FF
    cmp #$0078
    bcc stage3_79_sparse_fanout
    cmp #$0079
    bcc stage3_79_sparse_miss
    lda $40
    cmp #$79FE
    bne stage3_79_sparse_7ac6
    jmp entry_79fe
stage3_79_sparse_7ac6:
    cmp #$7AC6
    bne stage3_79_sparse_miss
    jmp entry_7ac6
stage3_79_sparse_fanout:
    jml.l $9EA700
stage3_79_sparse_miss:
    jml.l $94F931
stage3_79_sparse_dispatch_end:

    .org $BE00
.a16
.i16
; --- transpiled from $0079FE (11 completed instructions before TRAP #5) ---
entry_79fe:
    rep #$30
    lda #$79FE
    sta $92
    lda #$000B
    sta $90
    bra h79fe_guard

    .org $BE10
; --- transpiled from $007AC6 (BRA plus the same 11-instruction path) ---
entry_7ac6:
    rep #$30
    lda #$7AC6
    sta $92
    lda #$000C
    sta $90
    bra h79fe_guard

    .org $BE20
h79fe_guard:
    ; The hot path directly touches only A5-relative work RAM.  Admit the
    ; exact organic round-1 Stage-3 state: active task, mode zero, and table
    ; index $000C.  Guard scratch is nonarchitectural; a miss resumes at the
    ; original entry PC before any D/A/CCR/work/AC change.
    lda $36
    cmp #$00F0
    bne h79fe_cold
    lda $34
    bne h79fe_cold
    ldx #$2A37
    lda $400000,x
    and #$00FF
    cmp #$0001
    bne h79fe_cold
    ldx #$2930
    lda $400000,x
    xba
    bne h79fe_cold
    ldx #$292C
    lda $400000,x
    xba
    cmp #$000C
    bne h79fe_cold

    ; Architectural result of:
    ;   MOVE.W $2930(A5),D0 / CMP #1,D0 / BNE;
    ;   MOVE.W $292C(A5),D1 / EXT.L / ASL.L #4;
    ;   LEA $6AB4,A0 / MOVE.W (A0,D1.L),D2;
    ;   MOVE.B D2,$2A36(A5).
    ; The immutable World-set table word at $006B74 is $0004.
    lda $90
    jsr esc9_ac_charge
    stz $00
    lda #$00C0
    sta $04
    stz $06
    lda #$0004
    sta $08
    lda #$6AB4
    sta $20
    stz $22
    ldx #$2A36
    sep #$20
    lda #$04
    sta $400000,x
    rep #$20

    ; ASL.L #4 of positive $0000000C leaves X/N/Z/V/C all clear.  The
    ; following LEA/MOVEs do not alter the 68000 flags.
    stz $A2
    stz $70
    stz $60
    stz $72
    stz $6E

    ; Scheduler/IRQ semantics remain original: delegate the terminal TRAP #5.
    lda #$7AC4
    sta $40
    stz $42
    jml.l inext

h79fe_cold:
    lda $92
    sta $40
    stz $42
    jml.l inext
entry_stage3_79_loop_end:
"""


def main() -> int:
    program = PROGRAM.read_bytes()
    if program[0x79FE:0x7A12] != bytes.fromhex(
        "4a2d2a37670000c6302d29300c4000016600009e"
    ):
        raise SystemExit("$0079FE source prologue no longer matches the guard")
    if program[0x7AC0:0x7ACA] != bytes.fromhex(
        "1b422a364e456000ff36"
    ):
        raise SystemExit("$007AC0 source tail no longer matches the fast path")
    if program[0x6B74:0x6B76] != bytes.fromhex("0004"):
        raise SystemExit("$006B74 table word is no longer $0004")

    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $0079FE generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + BODY + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_79fe: regenerated $0079FE/$007AC6@$9F:BE00")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
