#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $02E676 object-status routine."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = "; >>> STAGE3_2E676 — generated by tools/gen_stage3_2e676.py <<<"
END = "; <<< STAGE3_2E676 <<<"
PC = 0x02E676


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 27 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $02E676 transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_2e676:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """    .org $E400
.a16
.i16
; Reserved island $9F:E400-$E7FF; source PC $02E676.
entry_2e676t:
    rep #$30
    ; The routine reads two record pointers from A4+$30/$34, then directly
    ; writes each pointed record through +$0E. Validate the base, both live
    ; pointers, and the genuine return before the first architectural write.
    lda $32
    cmp #$00F0
    bne h2e676_cold
    lda $30
    cmp #$3FC9
    bcs h2e676_cold
    tax
    lda $400034,x
    xba
    cmp #$00F0
    bne h2e676_cold
    lda $400036,x
    xba
    cmp #$3FF1
    bcs h2e676_cold
    lda $400030,x
    xba
    cmp #$00F0
    bne h2e676_cold
    lda $400032,x
    xba
    cmp #$3FF1
    bcs h2e676_cold
    lda $3E
    cmp #$00F0
    bne h2e676_cold
    lda $3C
    cmp #$3FFD
    bcs h2e676_cold
    bra h2e676_hot
h2e676_cold:
    lda #$E676
    sta $40
    lda #$0002
    sta $42
    jml.l inext
h2e676_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $02E676 table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if body.count("    jsr esc9_ac_charge\n") != 8:
        raise RuntimeError("$02E676 lost an AC-charge basic block")
    return body + "\nentry_2e676t_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $02E676 generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_2e676: regenerated $02E676@$9F:E400")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
