#!/usr/bin/env python3
"""Regenerate the bounded spike-path bodies in SA-1 escape bank $9E."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank8.pasm"
BG_OFFSET_TABLE = ROOT / "src/render_bg_offsets.bin"
START = "; >>> ESCBANK8_BODIES — generated by tools/gen_escbank8_bodies.py <<<"
END = "; <<< ESCBANK8_BODIES <<<"


def render_bg_offsets() -> bytes:
    """Return source-cell -> SNES top-left tilemap byte offsets.

    The producer scans the arcade planes in column-major blocks of 32 cells.
    Each 16x16 arcade cell expands to a 2x2 group in the split 64x32 SNES
    tilemap.  Keep this formula identical to video.pasm's one-time
    ``bg_offset_table_init`` so the SA-1 transition builder can replace its
    per-cell shift tree with one immutable ROM lookup.
    """

    output = bytearray()
    for column in range(16):
        for row in range(32):
            horizontal = column * 8 + (row & 1) * 4
            if horizontal & 0x40:
                horizontal = (horizontal & 0x3F) + 0x0800
            offset = (row & 0x1E) * 64 + horizontal
            output.extend(offset.to_bytes(2, "little"))
    if len(output) != 0x400:
        raise AssertionError("renderer BG offset table must be exactly 1024 bytes")
    return bytes(output)


def transpile(pc: int, *args: str, allow_rte_bail: bool = False) -> str:
    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        f"{pc:06X}",
        "--bank7",  # banked helper/JML lowering; $00F8 returns resume bank $9D
        *args,
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"transpile failed for ${pc:06X}")
    if "UNIMPLEMENTED" in result.stdout:
        raise SystemExit(f"transpile emitted an incomplete body for ${pc:06X}")
    if "BAIL" in result.stderr:
        expected = "$0004FE rte" if allow_rte_bail else None
        if expected is None or result.stderr.count("BAIL edges") != 1 or expected not in result.stderr:
            sys.stderr.write(result.stderr)
            raise SystemExit(f"unexpected transpiler bail for ${pc:06X}")
    return result.stdout.rstrip()


def guard_entry(
    body: str,
    entry: str,
    pc: int,
    *,
    exact_words: tuple[tuple[int, int], ...] = (),
    bank_words: tuple[int, ...] = (),
) -> str:
    """Restart the original instruction before any direct-work-RAM mutation."""

    needle = f"{entry}:\n    rep #$30\n"
    tag = entry.removeprefix("entry_")
    lines = [needle.rstrip("\n")]
    for address, value in exact_words:
        lines.extend(
            [
                f"    lda ${address:02X}",
                f"    cmp #${value:04X}",
                f"    bne h{tag}_cold",
            ]
        )
    for address in bank_words:
        lines.extend(
            [
                f"    lda ${address:02X}",
                "    cmp #$00F0",
                f"    bne h{tag}_cold",
            ]
        )
    lines.extend(
        [
            f"    bra h{tag}_hot",
            f"h{tag}_cold:",
            f"    lda #${pc & 0xFFFF:04X}",
            "    sta $40",
            f"    lda #${(pc >> 16) & 0xFF:04X}",
            "    sta $42",
            "    jml.l inext",
            f"h{tag}_hot:",
        ]
    )
    replacement = "\n".join(lines) + "\n"
    if body.count(needle) != 1:
        raise SystemExit(f"unexpected entry prologue for {entry}")
    return body.replace(needle, replacement, 1)


def direct_real_return(
    body: str,
    call_pc: int,
    callee_pc: int,
    target: str,
    *,
    same_bank: bool = False,
) -> str:
    """Keep a genuine 68K return on the stack but enter a proven table body.

    ``--real-return-calls`` deliberately ends a span in ``inext``.  For callees
    that already have a table-convention body, the pushed architectural return
    is exactly that body's entry contract, so bypass only the interpreter fetch.
    The target PC remains in $40/$42 for guarded fallback paths.
    """

    ret = (call_pc + (4 if call_pc == 0x007782 else 6)) & 0xFFFFFF
    # The only BSR in this set is the four-byte $007782 instruction; all other
    # selected calls are six-byte absolute-long JSRs.
    needle = (
        f"    lda #${callee_pc & 0xFFFF:04X}\n"
        "    sta $40\n"
        f"    lda #${(callee_pc >> 16) & 0xFFFF:04X}\n"
        "    sta $42\n"
        "    jml.l inext\n"
        f"    ; xlat continuation transpiled from ${ret:06X}"
    )
    jump = f"    {'jmp' if same_bank else 'jml.l'} {target}"
    replacement = needle.replace("    jml.l inext", jump, 1)
    if body.count(needle) != 1:
        raise SystemExit(
            f"unexpected real-return bridge at ${call_pc:06X} -> ${callee_pc:06X}"
        )
    return body.replace(needle, replacement, 1)


def sync_zero_move_ccr(body: str, trap_pc: int, tag: str, *, z: int) -> str:
    """Materialize the final CLR/MOVE CCR before an interpreted TRAP."""

    needle = (
        f"    lda #${trap_pc & 0xFFFF:04X}\n"
        "    sta $40\n"
        f"    lda #${(trap_pc >> 16) & 0xFFFF:04X}\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    sync = [
        "    ; The following interpreted TRAP stacks the 68K CCR.  Native",
        "    ; address/store plumbing clobbered host P, so publish the exact",
        "    ; final MOVE/CLR result while preserving X in $A2.",
        "    stz $70",
        "    stz $72",
        "    stz $6E",
    ]
    if z:
        sync.extend(("    lda #$0001", "    sta $60"))
    else:
        sync.append("    stz $60")
    replacement = "\n".join(sync) + "\n" + needle
    if body.count(needle) != 1:
        raise SystemExit(f"unexpected ${trap_pc:06X} TRAP tail in {tag}")
    return body.replace(needle, replacement, 1)


def entry_466() -> str:
    body = transpile(
        0x000466,
        "--coroutine",
        "--xflag",
        "--bail",
        allow_rte_bail=True,
    )
    terminal = (
        "    ; BAIL to interp @ $0004FE: rte    (opcode rte)\n"
        "    lda #$04FE\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if body.count(terminal) != 1:
        raise SystemExit("unexpected $000466 RTE tail")
    body = body.replace(
        terminal,
        "    ; Reuse the interpreter's exact SR/PC pop and coroutine/xlat hook.\n"
        "    jml.l op_rte",
        1,
    )
    body = guard_entry(
        body,
        "entry_466",
        0x000466,
        exact_words=((0x34, 0x0000),),
        bank_words=(0x36, 0x3E),
    )
    return body + "\nentry_466_end:"


def entry_1d51a() -> str:
    body = transpile(
        0x01D51A,
        "--coroutine",
        "--xflag",
        "--stopat=01D536",
    )
    body += (
        "\n    ; Execute the already-native allocator through the ordinary JSR hook;\n"
        "    ; its RTS is caught by entry_1d53a's xlat continuation.\n"
        "    lda #$D536\n"
        "    sta $40\n"
        "    lda #$0001\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    body = guard_entry(
        body,
        "entry_1d51a",
        0x01D51A,
        exact_words=((0x34, 0x0000),),
        bank_words=(0x36, 0x3E),
    )
    return body + "\nentry_1d51a_end:"


def entry_1d53a() -> str:
    body = transpile(0x01D53A, "--coroutine", "--xflag")
    success = (
        "Ltj1d53a_1d54c:\n"
        "    lda #$D54C\n"
        "    sta $40\n"
        "    lda #$0001\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if body.count(success) != 1:
        raise SystemExit("unexpected $01D53A success tail")
    body = body.replace(
        success,
        # Both labels execute in bank $9E.  Poppy records generated symbols
        # with bank $00, so a symbolic JML encodes $00:9176 and silently
        # leaves this escape bank.  A same-bank absolute JMP preserves PBR.
        "Ltj1d53a_1d54c:\n    jmp entry_1d54c\n",
        1,
    )
    body = guard_entry(
        body,
        "entry_1d53a",
        0x01D53A,
        bank_words=(0x26, 0x3A, 0x3E),
    )
    return body + "\nentry_1d53a_end:"


def entry_1d54c() -> str:
    body = transpile(
        0x01D54C,
        "--coroutine",
        "--xflag",
        "--jt=1D588:0:6",
    )
    return body + "\nentry_1d54c_end:"


def entry_24d28() -> str:
    body = transpile(0x024D28, "--coroutine", "--xflag")
    trap_tail = (
        "    lda #$4D62\n"
        "    sta $40\n"
        "    lda #$0002\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if body.count(trap_tail) != 1:
        raise SystemExit("unexpected $024D28 TRAP #1 tail")
    body = body.replace(
        trap_tail,
        "    ; The final MOVE.W #$10,-(A7) exports N=Z=V=C=0; the prior\n"
        "    ; bounded LSL.W #4 of a zero-extended byte also leaves X=0.\n"
        "    ; Materialize that exact SR before op_trap builds its frame.\n"
        "    stz $60\n"
        "    stz $70\n"
        "    stz $72\n"
        "    stz $6E\n"
        "    stz $A2\n"
        + trap_tail,
        1,
    )
    body = guard_entry(
        body,
        "entry_24d28",
        0x024D28,
        # A4 is the signed spawn-record stream in original ROM ($04xxxx),
        # while A5 and A7 are work-RAM pointers.  Treat any other shape as a
        # guarded interpreter fallback before the native body mutates state.
        exact_words=((0x32, 0x0004), (0x34, 0x0000)),
        bank_words=(0x36, 0x3E),
    )
    return body + "\nentry_24d28_end:"


def entry_24d64() -> str:
    body = transpile(0x024D64, "--coroutine", "--xflag")
    tst_d7 = "    lda $1C\n    bne Lf24d64_1"
    if body.count(tst_d7) != 1:
        raise SystemExit("unexpected $024D64 TST.W D7 branch")
    body = body.replace(
        tst_d7,
        "    ; TST.W D7 is the last CCR producer on every exit path.\n"
        "    ; Persist N/Z and clear V/C before native work clobbers host P.\n"
        "    lda $1C\n"
        "    and #$8000\n"
        "    sta $70\n"
        "    stz $72\n"
        "    stz $6E\n"
        "    stz $60\n"
        "    lda $1C\n"
        "    bne h24d64_tst_nonzero\n"
        "    inc $60\n"
        "h24d64_tst_nonzero:\n"
        "    lda $1C\n"
        "    bne Lf24d64_1",
        1,
    )
    terminal = (
        "    lda #$4CB6\n"
        "    sta $40\n"
        "    lda #$0002\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if body.count(terminal) != 1:
        raise SystemExit("unexpected $024D64 loop tail")
    body = body.replace(
        terminal,
        "    ; Rejoin the original bank-$99 native loop at its exported seam.\n"
        "    jml.l entry_24cb6",
        1,
    )
    body = guard_entry(
        body,
        "entry_24d64",
        0x024D64,
        exact_words=((0x34, 0x0000),),
        bank_words=(0x2E, 0x36, 0x3E),
    )
    return body + "\nentry_24d64_end:"


def entry_1f4b0t() -> str:
    body = transpile(0x01F4B0, "--table", "--rom=a4")
    if body.count("entry_1f4b0:") != 1:
        raise SystemExit("unexpected $01F4B0 entry label")
    body = body.replace("entry_1f4b0:", "entry_1f4b0t:", 1)
    body = guard_entry(
        body,
        "entry_1f4b0t",
        0x01F4B0,
        exact_words=((0x34, 0x0000),),
        bank_words=(0x36, 0x3E),
    )
    return body + "\nentry_1f4b0t_end:"


def xlat_76_dispatch() -> str:
    """Compact exact dispatcher for otherwise-empty bank-$00 pages $76/$77."""

    targets = (
        (0x76B6, "entry_76b6"),
        (0x76BC, "entry_76bc"),
        (0x76C2, "entry_76c2"),
        (0x76D4, "entry_76d4"),
        (0x76EC, "entry_76ec"),
        (0x7704, "entry_7704"),
        (0x771C, "entry_771c"),
        (0x7734, "entry_7734"),
        (0x7748, "entry_7748"),
        (0x776A, "entry_776a"),
        (0x777A, "entry_777a"),
        (0x7782, "entry_7782"),
        (0x7786, "entry_7786"),
    )
    lines = [
        "; Compact continuation dispatcher for the one-shot $0076B6 fan-out.",
        "; $94:F900 admits only pages $76/$77; every unknown PC rejoins the",
        "; ordinary dense-table miss path without changing $40/$42.",
        "xlat_76_dispatch:",
        "    rep #$30",
        "    lda $42",
        "    bne xdd8_miss",
        "    lda $40",
    ]
    for pc, _entry in targets:
        lines.extend((f"    cmp #${pc:04X}", f"    beq xdd8_{pc:04x}"))
    lines.extend(("xdd8_miss:", "    jml.l xd_table"))
    for pc, entry in targets:
        lines.extend((f"xdd8_{pc:04x}:", f"    jmp {entry}"))
    lines.append("xlat_76_dispatch_end:")
    return "\n".join(lines)


def entry_76_chain() -> str:
    common = ("--coroutine", "--xflag", "--exitccr", "--restore-static-residue")

    first = transpile(
        0x0076B6,
        *common,
        "--real-return-calls=0076B6,0076BC",
    )
    first = direct_real_return(first, 0x0076B6, 0x024AA8, "entry_24aa8t")
    first = direct_real_return(first, 0x0076BC, 0x028F92, "entry_28f92t")
    first = sync_zero_move_ccr(first, 0x0076D2, "entry_76b6", z=0)
    first = guard_entry(first, "entry_76b6", 0x0076B6, bank_words=(0x36, 0x3E))
    pieces = [first + "\nentry_76b6_end:"]

    for pc, trap_pc in (
        (0x0076D4, 0x0076EA),
        (0x0076EC, 0x007702),
        (0x007704, 0x00771A),
        (0x00771C, 0x007732),
    ):
        body = transpile(pc, *common)
        body = sync_zero_move_ccr(body, trap_pc, f"entry_{pc:x}", z=0)
        body = guard_entry(body, f"entry_{pc:x}", pc, bank_words=(0x36, 0x3E))
        pieces.append(body + f"\nentry_{pc:x}_end:")

    tail = transpile(
        0x007734,
        *common,
        "--stopat=007786",
        "--real-return-calls=007742,007764,007774,00777C,007782",
    )
    for call_pc in (0x007742, 0x007764, 0x007774):
        tail = direct_real_return(tail, call_pc, 0x0008FA, "entry_8fat")
    tail = direct_real_return(tail, 0x00777C, 0x00091E, "entry_91et")
    tail = direct_real_return(
        tail, 0x007782, 0x0008B46, "entry_8b46t", same_bank=True
    )
    tail = guard_entry(
        tail, "entry_7734", 0x007734, bank_words=(0x36, 0x3A, 0x3E)
    )
    if not tail.endswith("entry_7786:\nbr7734_5:"):
        raise SystemExit("unexpected $007734 stop-at-$007786 seam")
    tail += (
        "\n    ; Continue byte-retained at the first post-$8B46 instruction;"
        "\n    ; this deliberately leaves the later trap-bearing control loop unchanged."
        "\n    lda #$7786"
        "\n    sta $40"
        "\n    lda #$0000"
        "\n    sta $42"
        "\n    jml.l inext"
        "\nentry_7734_end:"
    )
    pieces.append(tail)
    return "\n\n".join(pieces)


def entry_1e71e() -> str:
    body = transpile(
        0x01E71E,
        "--coroutine",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
        "--real-return-calls=01E76E,01E7AE",
    )
    body = guard_entry(body, "entry_1e71e", 0x01E71E, bank_words=(0x36, 0x3E))
    return body + "\nentry_1e71e_end:"


def entry_24_roots() -> str:
    common = ("--coroutine", "--xflag", "--exitccr", "--restore-static-residue")
    b5a = transpile(0x024B5A, *common, "--real-return-calls=024BA4")
    b5a = sync_zero_move_ccr(b5a, 0x024BC0, "entry_24b5a", z=1)
    b5a = guard_entry(b5a, "entry_24b5a", 0x024B5A, bank_words=(0x36, 0x3E))

    r27c = transpile(
        0x02427C,
        *common,
        "--real-return-calls=02427C,024282,024288,02428E",
    )
    r27c = sync_zero_move_ccr(r27c, 0x02429A, "entry_2427c", z=1)
    r27c = guard_entry(r27c, "entry_2427c", 0x02427C, bank_words=(0x36, 0x3E))
    return (
        b5a
        + "\nentry_24b5a_end:\n\n"
        + r27c
        + "\nentry_2427c_end:"
    )


def entry_8b46_cluster() -> str:
    root = transpile(
        0x008B46,
        "--table",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
        "--stopat=008B62",
    )
    if root.count("entry_8b46:") != 1:
        raise SystemExit("unexpected $008B46 table entry")
    root = root.replace("entry_8b46:", "entry_8b46t:", 1)
    # STOPAT is a hard fall-through bound, so append the exact next-PC state
    # and enter the no-push mid-function loop in the same bank.
    root += (
        "\n    lda #$8B62"
        "\n    sta $40"
        "\n    lda #$0000"
        "\n    sta $42"
        "\n    jmp entry_8b62"
    )
    root = guard_entry(root, "entry_8b46t", 0x008B46, bank_words=(0x36, 0x3E))

    loop = transpile(
        0x008B62,
        "--coroutine",
        "--fnfrag",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
        "--rom=a0",
        "--real-return-calls=008B6C",
    )
    bridge = (
        "    ; REAL-RETURN BRIDGE jsr $96a.l: push $008B72, resume through xlat entry_8b72\n"
        "    lda #$8B72\n"
        "    sta $54\n"
        "    lda #$0000\n"
        "    sta $56\n"
        "    jsl.l push32_l\n"
        "    lda #$096A\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    standard = (
        "    ; Standard skipped-JSR escape: $96A consumes $40/$42 as the genuine\n"
        "    ; return, writes its exact residue at A7-4, and returns through xlat.\n"
        "    lda #$8B72\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l entry_96a"
    )
    if loop.count(bridge) != 1:
        raise SystemExit("unexpected $008B6C real-return bridge")
    loop = loop.replace(bridge, standard, 1)
    trap = (
        "    lda #$8B9A\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    def sync_trap(body: str, tag: str) -> str:
        trap_sync = (
            "    ; MOVE.B D3,$2A36(A5) is the final CCR producer before TRAP #5.\n"
            "    lda $0C\n"
            "    and #$0080\n"
            "    sta $70\n"
            "    stz $72\n"
            "    stz $6E\n"
            "    stz $60\n"
            "    lda $0C\n"
            "    and #$00FF\n"
            f"    bne h{tag}_trap_nonzero\n"
            "    inc $60\n"
            f"h{tag}_trap_nonzero:\n"
            + trap
        )
        if body.count(trap) != 1:
            raise SystemExit(f"unexpected ${tag.upper()} loop/trap shape")
        return body.replace(trap, trap_sync, 1)

    loop = sync_trap(loop, "8b62")
    if loop.count("    jmp L8b62_8ba2") != 1:
        raise SystemExit("unexpected $008B62 inner-loop exit")
    loop = loop.replace("    jmp L8b62_8ba2", "    jmp entry_8ba2", 1)

    # The post-yield inner loop is a separate no-push fragment.  Its BGE tail
    # must preserve CMP's X (CMP does not alter X), then directly enter the
    # two-instruction outer-counter fragment instead of falling back to fetch.
    inner = transpile(
        0x008B7A,
        "--coroutine",
        "--fnfrag",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
        "--rom=a0",
    )
    inner = sync_trap(inner, "8b7a")
    x_tail = "    sta $6E\n    sta $A2\n    lda #$8BA2"
    if inner.count(x_tail) != 1:
        raise SystemExit("unexpected $008B7A CMP tail")
    inner = inner.replace(x_tail, "    sta $6E\n    lda #$8BA2", 1)
    inner_seam = (
        "    lda #$8BA2\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if inner.count(inner_seam) != 1:
        raise SystemExit("unexpected $008B7A -> $008BA2 seam")
    inner = inner.replace(
        inner_seam,
        inner_seam.replace("    jml.l inext", "    jmp entry_8ba2"),
        1,
    )

    outer = transpile(
        0x008BA2,
        "--coroutine",
        "--fnfrag",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
    )
    outer_seam = (
        "    lda #$8B62\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if outer.count(outer_seam) != 1:
        raise SystemExit("unexpected $008BA2 -> $008B62 seam")
    outer = outer.replace(
        outer_seam,
        outer_seam.replace("    jml.l inext", "    jmp entry_8b62"),
        1,
    )

    resume = transpile(
        0x008B9C,
        "--coroutine",
        "--xflag",
        "--exitccr",
        "--restore-static-residue",
    )
    resume_seam = (
        "    lda #$8B7A\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    if resume.count(resume_seam) != 1:
        raise SystemExit("unexpected $008B9C -> $008B7A seam")
    resume = resume.replace(
        resume_seam,
        resume_seam.replace("    jml.l inext", "    jmp entry_8b7a"),
        1,
    )
    resume = guard_entry(
        resume, "entry_8b9c", 0x008B9C, bank_words=(0x36, 0x3A, 0x3E)
    )
    return (
        root
        + "\nentry_8b46t_end:\n\n"
        + loop
        + "\nentry_8b62_end:\n\n"
        + inner
        + "\nentry_8b7a_end:\n\n"
        + outer
        + "\nentry_8ba2_end:\n\n"
        + resume
        + "\nentry_8b9c_end:"
    )


def entry_1c9ae_empty() -> str:
    """Collapse the fully inactive sixteen-record object pass.

    The production spike enters $01C9AE with D5.w=$000F and walks sixteen
    48-byte records.  An inactive record executes only MOVE.B/BEQ/ADDA/DBRA,
    four interpreter instructions per record.  Read all sixteen status bytes
    before changing architectural state.  Any active record, noncanonical
    pointer, noninitial loop count, or virtual IRQ boundary executes the one
    already-fetched MOVE.B through the generic byte reader, then rejoins at
    $01C9B0.  Re-entering $01C9AE would be caught by the same fetch choke and
    loop forever.
    """

    offsets = range(0, 0x300, 0x30)
    reads = ["    lda $400000,x"]
    reads.extend(f"    ora $40{offset:04X},x" for offset in list(offsets)[1:])
    return "\n".join(
        [
            "; --- transpiled from $01C9AE (guarded inactive-record span) ---",
            "; Guarded inactive-record fast path for $01C9AE-$01CD3C.",
            "; A hit replaces exactly 16 * 4 interpreted instructions.",
            "; Exact hex-only alias is consumed by gen_xlat_table.py.",
            "entry_1c9ae:",
            "entry_1c9ae_empty:",
            "    rep #$30",
            "    lda $22",
            "    cmp #$00F0",
            "    bne h1c9ae_empty_cold",
            "    lda $14",
            "    cmp #$000F",
            "    bne h1c9ae_empty_cold",
            "    lda $16",
            "    bne h1c9ae_empty_cold",
            "    lda $20",
            "    cmp #$FD30",
            "    bcs h1c9ae_empty_cold",
            "; Do not move a virtual 68000 IRQ across this 64-instruction span.",
            "    lda $AC",
            "    cmp #$0040",
            "    bcc h1c9ae_empty_cold",
            "    bra h1c9ae_empty_hot",
            "h1c9ae_empty_cold:",
            "    ; Guard miss: execute the already-fetched MOVE.B (A0),D4",
            "    ; exactly once.  Generic read preserves ROM/IO/work-RAM semantics.",
            "    lda $20",
            "    sta $54",
            "    lda $22",
            "    sta $52",
            "    jsl.l readbyte_l",
            "    and #$00FF",
            "    sta $9A",
            "    and #$0080",
            "    sta $70",
            "    stz $6E",
            "    stz $72",
            "    stz $60",
            "    lda $9A",
            "    and #$00FF",
            "    bne h1c9ae_empty_cold_nz",
            "    inc $60",
            "h1c9ae_empty_cold_nz:",
            "    sep #$20",
            "    sta $10",
            "    rep #$20",
            "    lda #$C9B0",
            "    sta $40",
            "    lda #$0001",
            "    sta $42",
            "    jml.l inext",
            "h1c9ae_empty_hot:",
            "    ldx $20",
            "    sep #$20",
            *reads,
            "    beq h1c9ae_empty_hit",
            "    rep #$30",
            "    jmp h1c9ae_empty_cold",
            "h1c9ae_empty_hit:",
            "    rep #$30",
            "; MOVE.B #0,D4 changes only D4's low byte.",
            "    lda $10",
            "    and #$FF00",
            "    sta $10",
            "; Sixteen ADDA.W #$30 / DBRA iterations.",
            "    lda $20",
            "    clc",
            "    adc #$0300",
            "    sta $20",
            "    lda #$FFFF",
            "    sta $14",
            "; Final MOVE.B zero: Z=1, N=V=C=0, X is preserved in $A2.",
            "    lda #$0001",
            "    sta $60",
            "    stz $6E",
            "    stz $70",
            "    stz $72",
            "; The main loop charges one instruction after this return; charge",
            "; the other 63 now so the original 64-instruction cadence is exact.",
            "    lda $AC",
            "    sec",
            "    sbc #$003F",
            "    sta $AC",
            "    lda #$CD40",
            "    sta $40",
            "    lda #$0001",
            "    sta $42",
            "    jml.l inext",
            "entry_1c9ae_empty_end:",
        ]
    )


def entry_d7be() -> str:
    """Transpile the bounded round-transition initializer prefix.

    $00D7BE initializes the scrolling/strip state, selects two immutable ROM
    table rows, and then branches to the existing $00D9A8 allocator seam.
    It is reached with a genuine 68K return already on the task stack, so the
    table convention is exact.  The generated prefix has no nested calls and
    therefore does not depend on bank-$9D's synthetic-return sentinel even
    though the shared transpiler lowering is selected with ``--bank7``.
    """

    body = transpile(
        0x00D7BE,
        "--table",
        "--video",
        "--xflag",
        "--restore-indirect-residue",
        "--restore-static-residue",
    )
    body = guard_entry(
        body,
        "entry_d7be",
        0x00D7BE,
        exact_words=((0x34, 0x0000),),
        bank_words=(0x36, 0x3E),
    )
    # The prefix reads words at 4(A7) and 6(A7).  Direct bank-$40 indexing is
    # exact unless that final read crosses the 64 KiB work-RAM bank boundary.
    needle = (
        "    lda $3E\n"
        "    cmp #$00F0\n"
        "    bne hd7be_cold\n"
        "    bra hd7be_hot\n"
    )
    replacement = (
        "    lda $3E\n"
        "    cmp #$00F0\n"
        "    bne hd7be_cold\n"
        "    lda $3C\n"
        "    cmp #$FFF9\n"
        "    bcs hd7be_cold\n"
        "    clc\n"
        "    adc #$0006\n"
        "    sta $54\n"
        "    lda $3E\n"
        "    adc #$0000\n"
        "    sta $52\n"
        "    jsl.l rdw_ea_l\n"
        "    cmp #$0004\n"
        "    bne hd7be_cold\n"
        "    ; This exact N=4 path executes 84 original 68000 instructions.\n"
        "    ; The fetch loop charges the first; retain the other 83 here.\n"
        "    lda $AC\n"
        "    cmp #$0054\n"
        "    bcc hd7be_cold\n"
        "    bra hd7be_hot\n"
    )
    if body.count(needle) != 1:
        raise SystemExit("unexpected $00D7BE A7 guard seam")
    body = body.replace(needle, replacement, 1)
    # Keep every conservative restart distinguishable in execution-hook
    # evidence.  The AC restart is additionally bucketed so a live transition
    # can identify a safe continuation size without writing diagnostic state.
    guard_branches = (
        ("    bne hd7be_cold\n", "    bne hd7be_cold_a5_low\n"),
        ("    bne hd7be_cold\n", "    bne hd7be_cold_a5_bank\n"),
        ("    bne hd7be_cold\n", "    bne hd7be_cold_a7_bank\n"),
        ("    bcs hd7be_cold\n", "    bcs hd7be_cold_a7_cross\n"),
        ("    bne hd7be_cold\n", "    bne hd7be_cold_count\n"),
        ("    bcc hd7be_cold\n", "    bcc hd7be_cold_ac\n"),
    )
    for old, new in guard_branches:
        if old not in body:
            raise SystemExit(f"unexpected $00D7BE guard branch: {old.strip()}")
        body = body.replace(old, new, 1)
    cold = "hd7be_cold:\n"
    cold_diagnostics = """hd7be_cold_a5_low:
    bra hd7be_cold
hd7be_cold_a5_bank:
    bra hd7be_cold
hd7be_cold_a7_bank:
    bra hd7be_cold
hd7be_cold_a7_cross:
    bra hd7be_cold
hd7be_cold_count:
    bra hd7be_cold
hd7be_cold_ac:
    lda $AC
    cmp #$0010
    bcc hd7be_cold_ac_lt16
    cmp #$0020
    bcc hd7be_cold_ac_16_31
    cmp #$0030
    bcc hd7be_cold_ac_32_47
    cmp #$0040
    bcc hd7be_cold_ac_48_63
    bra hd7be_cold_ac_64_83
hd7be_cold_ac_lt16:
    bra hd7be_cold
hd7be_cold_ac_16_31:
    bra hd7be_cold
hd7be_cold_ac_32_47:
    bra hd7be_cold
hd7be_cold_ac_48_63:
    bra hd7be_cold
hd7be_cold_ac_64_83:
    bra hd7be_cold
"""
    if body.count(cold) != 1:
        raise SystemExit("unexpected $00D7BE cold restart label")
    body = body.replace(cold, cold_diagnostics + cold, 1)
    terminal = (
        "    lda #$D9A8\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    charged_terminal = (
        "; The final SUBI.W reaches zero, then CMPI.W #0,D0 supplies the\n"
        "; architected exit CCR: X=0, N=0, Z=1, V=0, C=0.  The trailing\n"
        "; SUBA/MOVEA/BRA instructions do not alter it.\n"
        "    stz $A2\n"
        "    stz $70\n"
        "    lda #$0001\n"
        "    sta $60\n"
        "    stz $72\n"
        "    stz $6E\n"
        "    lda $AC\n"
        "    sec\n"
        "    sbc #$0053\n"
        "    sta $AC\n"
        + terminal
    )
    if body.count(terminal) != 1:
        raise SystemExit("unexpected $00D7BE -> $00D9A8 terminal seam")
    return body.replace(terminal, charged_terminal, 1) + "\nentry_d7be_end:"


def main() -> int:
    BG_OFFSET_TABLE.write_bytes(render_bg_offsets())
    source = SOURCE.read_text(encoding="utf-8")
    block = (
        START
        + "\n    .org $8000\n"
        + entry_466()
        + "\n\n    .org $9000\n"
        + entry_1d51a()
        + "\n\n"
        + entry_1d53a()
        + "\n\n"
        + entry_1d54c()
        + "\nentry_1d_init_end:\n"
        + "\n    .org $9800\n"
        + entry_24d28()
        + "\n\n    .org $9C00\n"
        + entry_24d64()
        + "\n\n    .org $A000\n"
        + entry_1f4b0t()
        + "\n\n    .org $A700\n"
        + xlat_76_dispatch()
        + "\n\n    .org $A800\n"
        + entry_76_chain()
        + "\n\n    .org $C000\n"
        + entry_1e71e()
        + "\n\n    .org $C800\n"
        + entry_24_roots()
        + "\n\n    .org $D000\n"
        + entry_8b46_cluster()
        + "\n\n    .org $D400\n"
        + entry_1c9ae_empty()
        + "\n\n    .org $D800\n"
        + entry_d7be()
        + "\nescbank8_end:\n"
        + END
    )
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if len(pattern.findall(source)) != 1:
        raise SystemExit("marked ESCBANK8_BODIES block is missing or duplicated")
    SOURCE.write_text(pattern.sub(block, source), encoding="utf-8")
    print(
        "gen_escbank8_bodies: regenerated bounded spike, fan-out, "
        "inactive-record, $D7BE transition entries, and the 1 KiB BG-offset table"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
