#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 player setup/callback body at $01337E."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "escbank9.pasm"
TRANSPILE = ROOT / "tools" / "transpile.py"
START = (
    "; >>> STAGE3_1337E — generated by "
    "tools/gen_stage3_1337e.py <<<"
)
END = "; <<< STAGE3_1337E <<<"

PC = 0x01337E
ORIGIN = 0xBA00
LIMIT = 0xC000
RETURN_TRAMPOLINE = 0xE7F8
INSTRUCTION_COUNT = 32
FLAGS = (
    "--bank7",
    "--table",
    "--exitccr",
    "--xflag",
    "--accharge",
    "--restore-static-residue",
    "--restore-indirect-residue",
    "--bail",
)


def generate() -> str:
    result = subprocess.run(
        [sys.executable, str(TRANSPILE), f"{PC:06X}", *FLAGS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = f"all {INSTRUCTION_COUNT} instrs transpiled"
    if (
        expected not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            f"incomplete ${PC:06X} transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_1337e:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = f"""    .org ${ORIGIN:04X}
.a16
.i16
; Reserved island $9F:{ORIGIN:04X}-$9F:{LIMIT - 1:04X}; source PC ${PC:06X}.
entry_1337et:
    rep #$30
    ; A5 supplies the player callback table and must remain the canonical
    ; $F0:0000 work-RAM base.  Generated direct accesses touch A6 down to
    ; -$6C.  This body pushes fourteen bytes before its dynamic JSR, whose
    ; genuine four-byte return residue is also restored below A7.  Reject
    ; before the first architectural write unless every direct range and the
    ; final RTS are wholly inside canonical mapped work RAM.
    lda $36
    cmp #$00F0
    bne h1337e_cold
    lda $34
    bne h1337e_cold
    lda $3A
    cmp #$00F0
    bne h1337e_cold
    lda $38
    cmp #$006C
    bcc h1337e_cold
    cmp #$4000
    bcs h1337e_cold
    lda $3E
    cmp #$00F0
    bne h1337e_cold
    lda $3C
    cmp #$0050
    bcc h1337e_cold
    cmp #$3FFD
    bcs h1337e_cold
    bra h1337e_hot
h1337e_cold:
    lda #$337E
    sta $40
    lda #$0001
    sta $42
    jml.l inext
h1337e_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $01337E table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if "    jsr esc_ac_charge\n" in body:
        raise RuntimeError("$01337E retained a foreign AC helper")

    original_bridge = (
        "    lda #br1337e_1\n"
        "    sta $40\n"
        "    lda #$00F8\n"
        "    sta $42\n"
    )
    pinned_bridge = (
        f"    lda #${RETURN_TRAMPOLINE:04X}\n"
        "    sta $40\n"
        "    lda #$00F8\n"
        "    sta $42\n"
    )
    if body.count(original_bridge) != 1:
        raise RuntimeError("$01337E lost its unique indirect-call bridge")
    body = body.replace(original_bridge, pinned_bridge, 1)
    return body + "\nentry_1337et_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $01337E generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_1337e: regenerated $01337E@$9F:BA00")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
