#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $00BD1C scroll coroutine in bank $9F."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = (
    "; >>> STAGE3_SCROLL_TASK — generated by "
    "tools/gen_stage3_scroll_task.py <<<"
)
END = "; <<< STAGE3_SCROLL_TASK <<<"
PC = 0x00BD1C
CALLBACK_RETURNS = (0x00BD98, 0x00BDB8, 0x00BDFA, 0x00BE24)
TRAMPOLINES = (0xE3C8, 0xE3CC, 0xE3D0, 0xE3D4)


CALLBACK_CHARGE_HELPER = """    .org $A820
.a16
.i16
; $2742's complete two-pass source CFG is a fixed 333 interpreter steps;
; $295A is a fixed fourteen.  Charge only callbacks that the shared ibridge
; recognizes natively; an unknown callback falls through and charges itself
; in the interpreter.
hbd1c_callback_charge:
    lda $22
    bne hbd1c_callback_charge_done
    lda $20
    cmp #$295A
    beq hbd1c_callback_charge_295a
    cmp #$2742
    bne hbd1c_callback_charge_done
    lda #$014D
    bra hbd1c_callback_charge_apply
hbd1c_callback_charge_295a:
    lda #$000E
hbd1c_callback_charge_apply:
    jsr esc9_ac_charge
hbd1c_callback_charge_done:
    rts
hbd1c_callback_charge_end:
"""

STAGE3_13282_RESUMES = """    .org $A880
.a16
.i16
; $013282's two call bridges use bank-$9D pinned JML trampolines, then
; resume through these bank-local adapters.
entry_13282_callback_resume_1:
    jmp br13282_1
entry_13282_callback_resume_2:
    jmp br13282_2
entry_13282_resumes_end:

; >>> STAGE3_SELECTOR_FAST — generated by tools/gen_stage3_selector.py <<<
; <<< STAGE3_SELECTOR_FAST <<<
"""


def callback_residue(label: str, return_pc: int) -> str:
    return f"""{label}:
    ; Replace the private bridge tag below the popped A7 with the exact
    ; original dynamic-JSR return retained by the arcade.
    lda $3C
    sec
    sbc #$0004
    tax
    lda #${return_pc >> 16:04X}
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #${return_pc & 0xFFFF:04X}
    xba
    sta $400000,x
    xba
"""


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--coroutine",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 83 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $00BD1C coroutine transpilation:\n"
            + result.stdout
            + result.stderr
        )
    body = result.stdout.rstrip()
    prologue = (
        "entry_bd1c:\n"
        "    rep #$30\n"
        "    ; coroutine task body: NO return-push "
        "(entered by the op_rte resume hook, not a jsr)\n"
    )
    guarded = """entry_bd1c:
    rep #$30
    ; Every direct work-RAM access is A5-relative through $2A42, and the
    ; deepest argument/callback frame consumes eighteen bytes.  Reject before
    ; the first write unless both bases are the canonical task shape.
    lda $34
    bne hbd1c_cold
    lda $36
    cmp #$00F0
    bne hbd1c_cold
    lda $3E
    cmp #$00F0
    bne hbd1c_cold
    lda $3C
    cmp #$0012
    bcc hbd1c_cold
    cmp #$4001
    bcs hbd1c_cold
    bra hbd1c_hot
hbd1c_cold:
    lda #$BD1C
    sta $40
    stz $42
    jml.l inext
hbd1c_hot:
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $00BD1C coroutine prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if body.count("    jsr esc9_ac_charge\n") < 12:
        raise RuntimeError("$00BD1C lost dynamic AC-charge sites")

    for index, (return_pc, trampoline) in enumerate(
        zip(CALLBACK_RETURNS, TRAMPOLINES), start=1
    ):
        bridge = (
            f"    lda #brbd1c_{index}\n"
            "    sta $40\n"
            "    lda #$00F8\n"
            "    sta $42\n"
        )
        pinned = (
            f"    lda #${trampoline:04X}\n"
            "    sta $40\n"
            "    lda #$00F8\n"
            "    sta $42\n"
        )
        if body.count(bridge) != 1:
            raise RuntimeError(
                f"$00BD1C lost indirect bridge {index}"
            )
        body = body.replace(bridge, pinned, 1)
        label = f"brbd1c_{index}:\n"
        if body.count(label) != 1:
            raise RuntimeError(
                f"$00BD1C lost callback continuation {index}"
            )
        body = body.replace(
            label, callback_residue(label.rstrip(":\n"), return_pc), 1
        )

    callback_tail = (
        "    lda $22\n"
        "    sta $50\n"
        "    jml.l ibridge\n"
    )
    charged_callback_tail = (
        "    lda $22\n"
        "    sta $50\n"
        "    php\n"
        "    rep #$30\n"
        "    jsr hbd1c_callback_charge\n"
        "    plp\n"
        "    jml.l ibridge\n"
    )
    if body.count(callback_tail) != 4:
        raise RuntimeError("$00BD1C lost its four indirect callback tails")
    body = body.replace(callback_tail, charged_callback_tail)

    # The final block includes TRAP #5 in the source CFG, but the native body
    # stops immediately before that trap and delegates it to the interpreter.
    # Charge only the four completed instructions at this comparison seam.
    terminal_charge = (
        "Lfbd1c_8:\n"
        "    php\n"
        "    rep #$30\n"
        "    lda #$0005\n"
        "    jsr esc9_ac_charge\n"
        "    plp\n"
    )
    corrected_terminal_charge = terminal_charge.replace(
        "lda #$0005", "lda #$0004"
    )
    if body.count(terminal_charge) != 1:
        raise RuntimeError("$00BD1C lost its final TRAP-bearing block")
    body = body.replace(
        terminal_charge, corrected_terminal_charge, 1
    )

    # MOVE.L A4,$2A3E(A5) is the last completed 68000 instruction before the
    # terminal TRAP.  Guarded A4 is $00F0:xxxx, hence N/Z/V/C all clear while
    # X remains untouched.  The generic generator had treated CCR as dead at
    # TRAP and otherwise leaked the preceding CMP #14,D6 Z flag.
    terminal_tail = (
        "    lda #$BE58\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext"
    )
    corrected_terminal_tail = (
        "    stz $60\n"
        "    stz $70\n"
        "    stz $72\n"
        "    stz $6E\n"
        + terminal_tail
    )
    if body.count(terminal_tail) != 1:
        raise RuntimeError("$00BD1C lost its terminal inext tail")
    body = body.replace(terminal_tail, corrected_terminal_tail, 1)

    return (
        CALLBACK_CHARGE_HELPER
        + "\n"
        + STAGE3_13282_RESUMES
        + "\n    .org $B000\n"
        ".a16\n"
        ".i16\n"
        "; Reserved scroll-task island $9F:B000-$CFFF.\n"
        + body
        + "\nentry_bd1c_end:\n"
    )


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 scroll-task generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_scroll_task: regenerated $00BD1C@$9F:B000")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
