#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $013282 player/render update routine."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = "; >>> STAGE3_13282 — generated by tools/gen_stage3_13282.py <<<"
END = "; <<< STAGE3_13282 <<<"
PC = 0x013282
TRAMPOLINES = (0xE3E4, 0xE3E8)


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 32 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $013282 transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_13282:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """    .org $E000
.a16
.i16
; Reserved island $9F:E000-$FFFF; source PC $013282.
entry_13282t:
    rep #$30
    ; Direct accesses span A4+0..4, A5+0x2A6D, and A6-0x76..-0x1D.
    ; The nested $C6BC/$29B6 path can consume eighty bytes below the
    ; caller's A7. Reject before the first architectural write unless the
    ; complete address and stack envelope is canonical mapped work RAM.
    lda $32
    cmp #$00F0
    bne h13282_cold
    lda $30
    cmp #$3FFC
    bcs h13282_cold
    lda $36
    cmp #$00F0
    bne h13282_cold
    lda $34
    cmp #$1593
    bcs h13282_cold
    lda $3A
    cmp #$00F0
    bne h13282_cold
    lda $38
    cmp #$0076
    bcc h13282_cold
    cmp #$4000
    bcs h13282_cold
    lda $3E
    cmp #$00F0
    bne h13282_cold
    lda $3C
    cmp #$0050
    bcc h13282_cold
    cmp #$3FFD
    bcs h13282_cold
    bra h13282_hot
h13282_cold:
    lda #$3282
    sta $40
    lda #$0001
    sta $42
    jml.l inext
h13282_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $013282 table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if body.count("    jsr esc9_ac_charge\n") != 9:
        raise RuntimeError("$013282 lost an AC-charge basic block")

    for index, trampoline in enumerate(TRAMPOLINES, start=1):
        label = f"br13282_{index}"
        bridge = (
            f"    lda #{label}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        pinned = (
            f"    lda #${trampoline:04X}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        if body.count(bridge) != 1:
            raise RuntimeError(f"$013282 lost callback bridge {label}")
        body = body.replace(bridge, pinned, 1)

    return body + "\nentry_13282t_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $013282 generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_13282: regenerated $013282@$9F:E000")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
