#!/usr/bin/env python3
"""Regenerate the bounded Stage-3 table-convention hot bodies in bank $94."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "escbank2.pasm"
TRANSPILE = ROOT / "tools" / "transpile.py"
START = (
    "; >>> STAGE3_HOT_BODIES — generated by "
    "tools/gen_stage3_hot_bodies.py <<<"
)
END = "; <<< STAGE3_HOT_BODIES <<<"

# Fixed starts make every cross-bank sparse-dispatch target auditable.  The
# generator/build assertions prove that each body stays inside its island.
SPECS = (
    (0x027952, 0xB600, 0xBC00),
    (0x0279D2, 0xBC00, 0xC200),
    (0x02F3BA, 0xC200, 0xD800),
    # Leaf record-output helpers reached from the three bodies above.  Keep
    # these after the fixed $CA00 CE4 residue shim and before the existing
    # $D800 C172 island.
    (0x027B44, 0xCB40, 0xCD00),
    (0x02F56A, 0xCD00, 0xCEC0),
    (0x027B7C, 0xCEC0, 0xD100),
    (0x02F5A2, 0xD100, 0xD340),
    # Pure bank-$02 lookup called from three renderer-dispatch continuations.
    # Its BSR hook arm materializes the genuine return before entering this
    # table/rts-convention body; sparse xlat also covers faithful call bridges.
    (0x02E49C, 0xD340, 0xD480),
    # Tiny residual Stage-3 counter leaf.  The generic lowering is not safe
    # here: CMP must preserve X on the below-two exit, while ADDQ must export
    # its own N/Z/V/C/X on the other exit.  Keep the exact hand lowering in
    # this generator so regenerating the surrounding bodies cannot erase it.
    (0x0296C6, 0xD480, 0xD600),
    # Selector/address leaf immediately before the Stage-3 record dispatcher.
    # Its final LSL.W flags are live across ADDA.L/RTS and must be published
    # exactly, including X.
    (0x02E40E, 0xD540, 0xD700),
    # Coordinate/projectile record leaf.  The guarded lowering lives after
    # the fixed $DB00 palette-dirty helper and before the $E000 HLE island.
    (0x0135E0, 0xDB20, 0xE000),
)
FLAGS = (
    "--bank2",
    "--table",
    "--exitccr",
    "--xflag",
    "--accharge",
    "--restore-static-residue",
)


def generate(pc: int, origin: int, limit: int) -> str:
    if pc in (0x027B44, 0x02F56A):
        return generate_box_leaf(pc, origin, limit)
    if pc in (0x027B7C, 0x02F5A2):
        return generate_collision_leaf(pc, origin, limit)
    if pc == 0x02E49C:
        return generate_2e49c(origin, limit)
    if pc == 0x0296C6:
        return generate_296c6(origin, limit)
    if pc == 0x02E40E:
        return generate_2e40e(origin, limit)
    if pc == 0x0135E0:
        return generate_135e0(origin, limit)
    result = subprocess.run(
        [sys.executable, str(TRANSPILE), f"{pc:06X}", *FLAGS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if "all " not in result.stderr or "instrs transpiled" not in result.stderr:
        raise RuntimeError(
            f"${pc:06X} did not report a complete transpile:\n{result.stderr}"
        )
    body = result.stdout.rstrip()
    if pc == 0x027952:
        # This BSR is only emitted within the already-admitted, guarded
        # Stage-3 record parent.  Sending its $027AEA child through the
        # generic dispatcher loses that provenance and deliberately falls
        # back to the interpreter.  Tail-enter the child instead: it consumes
        # the same synthetic bridge return and retains its own guard/cold
        # fallback before any architectural write.
        old_comment = (
            "    ; CALL-BRIDGE bsr.w $27aea -> ojmp_hook "
            "(callee --table escape, else interpret), resume br27952_1"
        )
        new_comment = (
            "    ; CALL-BRIDGE bsr.w $27aea -> direct guarded native child; "
            "resume br27952_1"
        )
        if body.count(old_comment) != 1:
            raise RuntimeError("$027952 lost its $027AEA call bridge")
        body = body.replace(old_comment, new_comment, 1)
        bridge_start = body.index(new_comment)
        bridge_end = body.index("br27952_1:", bridge_start)
        bridge = body[bridge_start:bridge_end]
        if bridge.count("    jml.l ojmp_hook") != 1:
            raise RuntimeError(
                "$027952 $027AEA bridge is not the unique dispatcher tail"
            )
        body = (
            body[:bridge_start]
            + bridge.replace(
                # Poppy assembles each escape bank independently, so use the
                # audited fixed bank-$9F entry rather than an out-of-bank
                # label it cannot resolve.
                "    jml.l ojmp_hook", "    jml.l $9FC000", 1
            )
            + body[bridge_end:]
        )
    name = f"entry_{pc:x}"
    return (
        f"    .org ${origin:04X}\n"
        ".a16\n"
        ".i16\n"
        f"; Reserved island ${origin:04X}-${limit - 1:04X}; "
        f"source PC ${pc:06X}.\n"
        f"{body}\n"
        f"{name}_end:\n"
    )
def generate_box_leaf(pc: int, origin: int, limit: int) -> str:
    """Guarded wrapper for the two invariant 16-instruction box emitters."""

    params = {
        0x027B44: (0x000E, 0x00F9),
        0x02F56A: (0x0030, 0x00F3),
    }
    pointer_offset, attribute = params[pc]
    name = f"entry_{pc:x}"
    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC ${pc:06X}.
; Guarded hand-exact wrapper; shared direct emitter is fixed at $9F:E800.
; --- transpiled from ${pc:06X} (16 instrs) by tools/gen_stage3_hot_bodies.py [hand-exact] ---
{name}:
    rep #$30
    lda #${pointer_offset:04X}
    sta $80
    lda #${attribute:04X}
    sta $82
    lda #${pc & 0xFFFF:04X}
    sta $88
    lda #${pc >> 16:04X}
    sta $8A
    jml.l $9FE800
{name}_end:
"""


def generate_collision_leaf(pc: int, origin: int, limit: int) -> str:
    """Guarded wrapper for the two collision-record emitters."""

    params = {
        # pointer field, attribute, initial D7, byte-source mode, BSR return
        0x027B7C: (0x0018, 0x80F9, 0x0001, 0x0000, 0x7B8E),
        0x02F5A2: (0x0034, 0x80F3, 0x0002, 0x0001, 0xF5B4),
    }
    pointer_offset, attribute, d7, byte_mode, bsr_return = params[pc]
    name = f"entry_{pc:x}"
    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC ${pc:06X}.
; Guarded hand-exact wrapper; shared direct emitter is fixed at $9F:E900.
; --- transpiled from ${pc:06X} (20 instrs) by tools/gen_stage3_hot_bodies.py [hand-exact] ---
{name}:
    rep #$30
    lda #${pointer_offset:04X}
    sta $80
    lda #${attribute:04X}
    sta $82
    lda #${d7:04X}
    sta $84
    lda #${byte_mode:04X}
    sta $86
    lda #${pc & 0xFFFF:04X}
    sta $88
    lda #${pc >> 16:04X}
    sta $8A
    lda #${bsr_return:04X}
    sta $8C
    jml.l $9FE900
{name}_end:
"""


def generate_2e49c(origin: int, limit: int) -> str:
    """Guarded direct two-level ROM lookup for the Stage-3 draw selector."""

    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC $02E49C.
; The generated form used six generic big-endian word reads for a nine-
; instruction leaf.  This hand-exact path admits the immutable first table's
; nineteen real entries, reads the two A4 selectors without committing state,
; proves the derived second lookup remains in the 512 KiB arcade image, and
; then publishes the exact D0/A0/CCR/X/RTS result.  Every other legal address
; or index delegates before the original CLR.L D0.
; --- transpiled from $02E49C (9 instrs) by tools/gen_stage3_hot_bodies.py [hand-exact] ---
entry_2e49c:
    rep #$30

    ; Both A4 selector words and the genuine RTS return must be canonical,
    ; non-wrapping mapped work RAM before any architectural write.
    lda $32
    cmp #$00F0
    bne h2e49c_guard_fail
    lda $30
    cmp #$3FF3
    bcs h2e49c_guard_fail
    lda $3E
    cmp #$00F0
    bne h2e49c_guard_fail
    lda $3C
    cmp #$3FFD
    bcs h2e49c_guard_fail

    ldx $30
    lda $40000A,x
    xba
    sta $80                          ; first selector
    cmp #$0013                      ; table $02E6D0 has 19 entries
    bcs h2e49c_guard_fail
    lda $40000C,x
    xba
    sta $82                          ; second selector
    bra h2e49c_guard_ok
h2e49c_guard_fail:
    jmp h2e49c_cold
h2e49c_guard_ok:

    ; First immutable longword table: MC68000 $02E6D0 = SNES $C3:E6D0.
    lda $80
    asl a
    asl a
    tax
    lda $C3E6D0,x
    xba
    sta $8E                          ; selected table high word
    lda $C3E6D2,x
    xba
    sta $8C                          ; selected table low word

    ; LSL.W #2 wraps within D0's low word.  Add that zero-extended result to
    ; A0 exactly as the indexed MOVEA does, then prove one non-crossing long.
    lda $82
    asl a
    asl a
    sta $84                          ; final D0.w and second-table byte offset
    lda $8C
    clc
    adc $84
    sta $54
    lda $8E
    adc #$0000
    cmp #$0008
    bcs h2e49c_lookup_fail
    clc
    adc #$00C1                      ; MC68000 bank 0..7 -> SNES $C1..$C8
    sta $56
    lda $54
    cmp #$FFFD
    bcs h2e49c_lookup_fail
    bra h2e49c_lookup_ok
h2e49c_lookup_fail:
    jmp h2e49c_cold
h2e49c_lookup_ok:

    ldy #$0000
    lda [$54],y
    xba
    sta $22                          ; final A0 high word
    ldy #$0002
    lda [$54],y
    xba
    sta $20                          ; final A0 low word

    ; All nine original instructions execute before the leaf can return.
    lda #$0009
    jsr esc_ac_charge
    stz $02                          ; CLR.L leaves D0's high word zero
    lda $84
    sta $00

    ; Final LSL.W #2 owns N/Z/V/C and X.  Its last shifted bit is source bit
    ; 14; MOVEA and RTS do not alter those flags.
    stz $72
    stz $60
    stz $6E
    stz $A2
    lda $84
    and #$8000
    sta $70
    lda $84
    bne h2e49c_nonzero
    lda #$0001
    sta $60
h2e49c_nonzero:
    lda $82
    and #$4000
    beq h2e49c_carry_done
    lda #$0001
    sta $6E
    sta $A2
h2e49c_carry_done:

    ; Faithful table/rts return, including the genuine four-byte stack pop.
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

h2e49c_cold:
    lda #$E49C
    sta $40
    lda #$0002
    sta $42
    jml.l inext
entry_2e49c_end:
"""


def generate_296c6(origin: int, limit: int) -> str:
    """Exact table/rts lowering for CMP.B/BCC/ADDQ.W/RTS at $0296C6."""

    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC $0296C6.
; Hand-exact because CMP preserves X while ADDQ updates X from its carry.
; --- transpiled from $0296C6 (4 instrs) by tools/gen_stage3_hot_bodies.py [hand-exact] ---
entry_296c6:
    rep #$30
    ; CMP.B plus its fused BCS account for two original instructions.
    php
    rep #$30
    lda #$0002
    jsr esc_ac_charge
    plp
    lda $34
    clc
    adc #$293B
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sec
    sbc #$02
    php
    rep #$20
    bcs h296c6_addq

    ; Unsigned-below: export CMP.B N/Z/V/C and leave emulated X untouched.
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    lda $50
    and #$0040
    sta $72
    lda $50
    and #$0001
    eor #$0001
    sta $6E
    bra h296c6_rts

h296c6_addq:
    plp
    rep #$30
    php
    lda #$0001
    jsr esc_ac_charge
    plp
    lda $1C
    clc
    adc #$0001
    sta $1C
    ; ADDQ.W exports N/Z/V/C and sets X equal to carry.
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    lda $50
    and #$0040
    sta $72
    lda $50
    and #$0001
    sta $6E
    sta $A2

h296c6_rts:
    ; Charge the original RTS, pop its genuine 32-bit return, and retain the
    ; ordinary table/rts sentinel convention.
    php
    rep #$30
    lda #$0001
    jsr esc_ac_charge
    plp
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
entry_296c6_end:
"""


def generate_2e40e(origin: int, limit: int) -> str:
    """Exact table/rts lowering for the ten-instruction $02E40E leaf."""

    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC $02E40E.
; --- transpiled from $02E40E (10 instrs) by tools/gen_stage3_hot_bodies.py [hand-exact] ---
entry_2e40e:
    rep #$30
    ; MOVEA/CMP.B/BCS comprise the first basic block.
    php
    rep #$30
    lda #$0003
    jsr esc_ac_charge
    plp
    lda #$3CF6
    sta $30
    lda #$00F0
    sta $32
    lda $00
    sep #$20
    sec
    sbc #$07
    rep #$20
    bcc h2e40e_extend

    ; D0.b >= 7: select the alternate base and retire SUBQ.B #7,D0.
    php
    rep #$30
    lda #$0002
    jsr esc_ac_charge
    plp
    lda #$2BB4
    sta $30
    lda #$00F0
    sta $32
    lda $00
    sep #$20
    sec
    sbc #$07
    sta $00
    rep #$20

h2e40e_extend:
    ; EXT.W, EXT.L, LSL.W, ADDA.L, RTS.
    php
    rep #$30
    lda #$0005
    jsr esc_ac_charge
    plp
    lda $00
    and #$00FF
    cmp #$0080
    bcc h2e40e_positive
    ora #$FF00
    sta $00
    lda #$FFFF
    bra h2e40e_high_ready
h2e40e_positive:
    sta $00
    lda #$0000
h2e40e_high_ready:
    sta $02

    lda $00
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a
    sta $00
    ; LSL.W #6 publishes N/Z/C/X and always clears V.
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    lda $50
    and #$0001
    sta $6E
    sta $A2

    ; ADDA.L preserves the LSL flags already materialized above.
    lda $30
    clc
    adc $00
    sta $30
    lda $32
    adc $02
    sta $32

    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
entry_2e40e_end:
"""


def generate_135e0(origin: int, limit: int) -> str:
    """Guarded direct-map lowering for the $0135E0 coordinate record leaf."""

    return f"""    .org ${origin:04X}
.a16
.i16
; Reserved island ${origin:04X}-${limit - 1:04X}; source PC $0135E0.
; --- transpiled from $0135E0 (31 instrs) by tools/gen_stage3_hot_bodies.py [guarded hand-exact] ---
entry_135e0:
    rep #$30
    ; Ordinary table dispatch consumes the genuine 68000 BSR return below.
    ; The parent $013538 fast body instead enters h135e0_direct with no
    ; synthetic push; $B0 is private native scratch selecting that ABI.
    stz $B0
    bra h135e0_guard
h135e0_direct:
    rep #$30
    lda #$0001
    sta $B0
h135e0_guard:
    ; A0 is a bank-$01 arcade-ROM descriptor.  A1/A6/A7 and the pointer at
    ; -$54(A6) must remain inside the real 16 KiB MC68000 work-RAM window.
    ; Every direct-call reject is read-only and returns C=0 so its parent can
    ; take the unchanged generic call bridge.  Ordinary rejects restart the
    ; original first instruction.
    lda $22
    cmp #$0001
    bne h135e0_cold
    lda $20
    cmp #$FFF4
    bcs h135e0_cold
    lda $26
    cmp #$00F0
    bne h135e0_cold
    lda $24
    cmp #$3FF4
    bcs h135e0_cold
    lda $3A
    cmp #$00F0
    bne h135e0_cold
    lda $38
    cmp #$0054
    bcc h135e0_cold
    cmp #$4000
    bcs h135e0_cold
    lda $3E
    cmp #$00F0
    bne h135e0_cold
    lda $3C
    cmp #$3FFD
    bcs h135e0_cold
    lda $38
    sec
    sbc #$0054
    tax
    lda $400000,x
    xba
    cmp #$00F0
    bne h135e0_cold
    lda $400002,x
    xba
    cmp #$3FFB
    bcs h135e0_cold
    bra h135e0_hot
h135e0_cold:
    lda $B0
    beq h135e0_cold_interpreted
    stz $B0
    clc
    rtl
h135e0_cold_interpreted:
    lda #$35E0
    sta $40
    lda #$0001
    sta $42
    jml.l inext

h135e0_hot:
    ; TST.W (A1) / BLE.
    php
    rep #$30
    lda #$0002
    jsr esc_ac_charge
    plp
    ldx $24
    lda $400000,x
    xba
    and #$FFFF
    bne h135e0_nonzero
    jmp h135e0_early_zero
h135e0_nonzero:
    bpl h135e0_active
    jmp h135e0_early_negative

h135e0_active:
    ; Active non-mirrored block through BTST/BEQ: eleven instructions.
    php
    rep #$30
    lda #$000B
    jsr esc_ac_charge
    plp
    lda $38
    sec
    sbc #$0022
    tax
    lda $400000,x
    xba
    sta $00
    ldx $20
    lda $C20006,x
    xba
    clc
    adc $00
    sta $00
    pha
    lda $24
    clc
    adc #$0006
    tax
    pla
    xba
    sta $400000,x

    lda $38
    sec
    sbc #$0022
    tax
    lda $400000,x
    xba
    sta $00
    ldx $20
    lda $C20008,x
    xba
    clc
    adc $00
    sta $00
    pha
    lda $24
    clc
    adc #$0008
    tax
    pla
    xba
    sta $400000,x

    ldx $20
    lda $C20002,x
    xba
    sta $00
    lda $C20004,x
    xba
    sta $04
    sep #$20
    lda $C2000C,x
    sta $08
    rep #$20
    lda $38
    sec
    sbc #$0024
    tax
    lda $400000,x
    and #$00FF
    and #$0080
    beq h135e0_coordinates

    ; Mirrored descriptor transform: six instructions.
    php
    rep #$30
    lda #$0006
    jsr esc_ac_charge
    plp
    ldx $20
    lda $C20002,x
    xba
    sta $04
    lda $C20004,x
    xba
    sta $00
    lda $00
    eor #$FFFF
    inc a
    sta $00
    lda $04
    eor #$FFFF
    inc a
    sta $04
    lda $08
    eor #$FFFF
    inc a
    sta $08
    sep #$20
    lda $08
    clc
    adc #$80
    sta $08
    rep #$20

h135e0_coordinates:
    ; Coordinate writes, A2 publication, and RTS: twelve instructions.
    php
    rep #$30
    lda #$000C
    jsr esc_ac_charge
    plp
    lda $38
    sec
    sbc #$001E
    tax
    lda $400000,x
    xba
    sta $9A
    clc
    adc $00
    sta $0C
    pha
    lda $24
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x

    lda $9A
    clc
    adc $04
    sta $0C
    bcc h135e0_x_clear
    lda #$0001
    sta $A2
    bra h135e0_x_ready
h135e0_x_clear:
    stz $A2
h135e0_x_ready:
    lda $0C
    pha
    lda $24
    clc
    adc #$0004
    tax
    pla
    xba
    sta $400000,x

    lda $08
    pha
    lda $24
    clc
    adc #$000C
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20

    lda $38
    sec
    sbc #$0054
    tax
    lda $400000,x
    xba
    sta $2A
    lda $400002,x
    xba
    sta $28
    ldx $28
    lda #$0100
    sta $400000,x

    lda $24
    clc
    adc #$0004
    tax
    lda $400000,x
    pha
    lda $28
    clc
    adc #$0004
    tax
    pla
    sta $400000,x

    lda $24
    clc
    adc #$0002
    tax
    lda $400000,x
    xba
    sta $9E
    pha
    lda $28
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    ; Final MOVE.W publishes N/Z and clears V/C; X from the second ADD survives.
    lda $9E
    and #$8000
    sta $70
    stz $72
    stz $6E
    stz $60
    lda $9E
    bne h135e0_rts
    inc $60
    bra h135e0_rts

h135e0_early_zero:
    lda #$0001
    sta $60
    stz $70
    stz $72
    stz $6E
    bra h135e0_early_rts
h135e0_early_negative:
    stz $60
    lda #$8000
    sta $70
    stz $72
    stz $6E
h135e0_early_rts:
    php
    rep #$30
    lda #$0001
    jsr esc_ac_charge
    plp

h135e0_rts:
    ; A direct parent call has no 68000 return to consume.  Its caller writes
    ; the exact BSR residue below the unchanged A7 and resumes locally.  SEC
    ; is only a native ABI result; emulated C remains in $6E.
    lda $B0
    beq h135e0_emulated_rts
    stz $B0
    sec
    rtl
h135e0_emulated_rts:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
entry_135e0_end:
"""


def main() -> None:
    text = SOURCE.read_text()
    if text.count(START) != 1 or text.count(END) != 1:
        raise RuntimeError("Stage-3 generated-body markers are missing or duplicated")
    before, remainder = text.split(START, 1)
    _, after = remainder.split(END, 1)
    bodies = "\n".join(generate(*spec) for spec in SPECS)
    SOURCE.write_text(f"{before}{START}\n{bodies}{END}{after}")
    print(
        "gen_stage3_hot_bodies: regenerated "
        + ", ".join(f"${pc:06X}@${origin:04X}" for pc, origin, _ in SPECS)
    )


if __name__ == "__main__":
    main()
