#!/usr/bin/env python3
"""Regenerate guarded Stage-3 player hot routines in bank $9F."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "escbank9.pasm"
TRANSPILE = ROOT / "tools" / "transpile.py"
START = (
    "; >>> STAGE3_PLAYER_HOT — generated by "
    "tools/gen_stage3_player_hot.py <<<"
)
END = "; <<< STAGE3_PLAYER_HOT <<<"

# The bank-$9D $00F8 return sentinel cannot directly resume bank $9F.
# Each generated call therefore points at a pinned bank-$9D JML trampoline,
# which lands on the corresponding fixed bank-$9F resume adapter.
SPECS = (
    (
        0x0133EA,
        0xEC00,
        0xF100,
        0x0072,
        {
            "br133ea_1": 0xE7E0,
            "br133ea_2": 0xE7E4,
            "br133ea_3": 0xE7E8,
        },
        37,
    ),
    (
        0x013468,
        0xF100,
        0xF700,
        0x0070,
        {"br13468_1": 0xE7EC},
        64,
    ),
    (
        0x013538,
        0xF700,
        0x10000,
        0x0050,
        {
            "br13538_1": 0xE7F0,
            "br13538_2": 0xE7F4,
        },
        50,
    ),
)

FLAGS = (
    "--bank7",
    "--table",
    "--exitccr",
    "--xflag",
    "--accharge",
    "--restore-static-residue",
)


def guard_body(body: str, pc: int, origin: int, limit: int, a6_floor: int) -> str:
    """Reject direct A6/A7 aliases unless their complete range is canonical."""

    name = f"{pc:x}"
    prologue = (
        f"entry_{name}:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = f"""    .org ${origin:04X}
.a16
.i16
; Reserved island $9F:{origin:04X}-$9F:{limit - 1:04X}; source PC ${pc:06X}.
entry_{name}t:
    rep #$30
    ; Generated direct accesses touch A6 down to -${a6_floor:02X}; nested
    ; calls and the faithful RTS use A7.  Reject before the first observable
    ; 68000 write unless both complete ranges are canonical mapped work RAM.
    lda $3A
    cmp #$00F0
    bne h{name}_cold
    lda $38
    cmp #${a6_floor:04X}
    bcc h{name}_cold
    cmp #$4000
    bcs h{name}_cold
    lda $3E
    cmp #$00F0
    bne h{name}_cold
    lda $3C
    cmp #$0050
    bcc h{name}_cold
    cmp #$3FFD
    bcs h{name}_cold
    bra h{name}_hot
h{name}_cold:
    lda #${pc & 0xFFFF:04X}
    sta $40
    lda #${pc >> 16:04X}
    sta $42
    jml.l inext
h{name}_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError(f"unexpected ${pc:06X} table prologue")
    return body.replace(prologue, guarded, 1)


def pin_bridges(body: str, pc: int, bridges: dict[str, int]) -> str:
    for label, trampoline in bridges.items():
        original = (
            f"    lda #{label}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        pinned = (
            f"    lda #${trampoline:04X}\n"
            "    sta $54\n"
            "    lda #$00F8\n"
            "    sta $56\n"
        )
        if body.count(original) != 1:
            raise RuntimeError(
                f"${pc:06X} lost its unique {label} call bridge"
            )
        if pc == 0x013538:
            # The guarded $0135E0 leaf exposes a direct-call ABI.  On a hit it
            # performs the complete original leaf and returns C=1 without
            # changing emulated A7; the existing continuation then writes the
            # authentic BSR return residue.  A read-only guard miss returns
            # C=0 and executes this unchanged dispatcher bridge.
            pinned = (
                "    jsl.l h135e0_direct\n"
                f"    bcs {label}\n"
                + pinned
            )
        body = body.replace(original, pinned, 1)
    return body


def preserve_resume_abi(body: str, pc: int) -> str:
    """Keep fixed bank-$9F resume-adapter JMP targets byte-stable.

    Correct ``NEG.B Dn`` lowering makes each of the two $013468 blocks five
    bytes smaller.  The handler's interpreted-call resume adapter is a pinned
    bank-$9F ABI target, so consume those ten bytes in the unreachable span
    after the non-returning JML to ``ojmp_hook`` and before ``br13468_1``.
    This has no executed-cycle cost and keeps the ROM-pack target assertion
    meaningful.
    """

    if pc != 0x013468:
        return body
    needle = "    jml.l ojmp_hook\nbr13468_1:\n"
    padding = (
        "    jml.l ojmp_hook\n"
        "    ; Unreachable ABI pad: two corrected NEG.B blocks are 10 bytes "
        "smaller.\n"
        + ("    nop\n" * 10)
        + "br13468_1:\n"
    )
    if body.count(needle) != 1:
        raise RuntimeError("$013468 lost its unique BSR resume seam")
    return body.replace(needle, padding, 1)


def generate_one(
    pc: int,
    origin: int,
    limit: int,
    a6_floor: int,
    bridges: dict[str, int],
    instruction_count: int,
) -> str:
    result = subprocess.run(
        [sys.executable, str(TRANSPILE), f"{pc:06X}", *FLAGS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = f"all {instruction_count} instrs transpiled"
    if (
        expected not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            f"incomplete ${pc:06X} transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    body = guard_body(body, pc, origin, limit, a6_floor)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if "    jsr esc_ac_charge\n" in body:
        raise RuntimeError(f"${pc:06X} retained a foreign AC helper")
    body = pin_bridges(body, pc, bridges)
    body = preserve_resume_abi(body, pc)
    return body + f"\nentry_{pc:x}t_end:\n"


def generate() -> str:
    return "\n".join(generate_one(*spec) for spec in SPECS)


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 player-hot generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_player_hot: regenerated $0133EA/$013468/$013538")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
