#!/usr/bin/env python3
"""Refresh imported symbols in src/escbank3.pasm.

escbank3.pasm is the THIRD escape bank (SA-1 $97:8000, file $2B8000) — hosts entry_25110 (collision),
whose 8KB body overflowed its bank-$00 inline gap. Like gen_escbank2_syms.py for $94, it pins the
bank-$00 jml/jsl targets (whose addresses shift when interp.pasm changes) into a marked block. The
--bank2 body's CALL-BRIDGE sentinels are sed'd $00FD->$00FC so the resume goes ors_pre->ors_94chk->
ors_97chk->ors_pre_97 (bank $97) rather than ->ors_pre_94 (bank $94). Same NEEDED symbols as escbank2.

The bank-$97 $01E7C0 hot helper also re-enters six generated seams in bank
$98.  Those labels move when a byte-width repair changes the generated body,
so import them from the freshly assembled escbank4.sym instead of embedding
numeric addresses.  build_interp.sh assembles bank $98 before bank $97.
"""
import re, sys
from pathlib import Path

NEEDED = ["inext", "rdw40_l", "wrw40_l", "rdb40_l", "wrb40_l", "push32_l",
          "rdw_ea_l", "readbyte_l", "writeword_l", "writebyte_l", "usmul_l",
          "op_rts_sentinel", "ojmp_hook", "ors_pre"]

sym_path = Path("src/interp.sym")
esc_path = Path("src/escbank3.pasm")
if not sym_path.exists():
    sys.exit("gen_escbank3_syms: src/interp.sym missing (build interp.bin with -s first)")
if not esc_path.exists():
    sys.exit(0)  # escbank3 optional

addr = {}
for line in sym_path.read_text(encoding="utf-8-sig").splitlines():
    m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
    if m:
        bank, off, name = m.group(1), m.group(2), m.group(3)
        addr[name] = "$%02X%04X" % (int(bank, 16), int(off, 16))

lines = ["; >>> ESCBANK3_SYMS — auto-generated by tools/gen_escbank3_syms.py (do not edit) <<<"]
missing = []
for n in NEEDED:
    if n in addr: lines.append("%s=%s" % (n, addr[n]))
    else: missing.append(n)
lines.append("; <<< ESCBANK3_SYMS <<<")
block = "\n".join(lines)

src = esc_path.read_text()
pat = re.compile(r"; >>> ESCBANK3_SYMS.*?; <<< ESCBANK3_SYMS <<<", re.DOTALL)
src = pat.sub(block, src) if pat.search(src) else block + "\n\n" + src

esc4_sym_path = Path("src/escbank4.sym")
if not esc4_sym_path.exists():
    sys.exit(
        "gen_escbank3_syms: src/escbank4.sym missing "
        "(assemble escbank4 before escbank3)"
    )
esc4_addr = {}
for line in esc4_sym_path.read_text(encoding="utf-8-sig").splitlines():
    m = re.match(r"\s*[0-9A-Fa-f]{2}:([0-9A-Fa-f]{4})\s+(\S+)", line)
    if m:
        esc4_addr[m.group(2)] = int(m.group(1), 16)

cross_bank_needed = [
    "L1e7c0_1e7cc",
    "L1e7c0_1e94a",
    "L1e7c0_1ee3a",
    "br1e7c0_10",
    "Lf1e7c0_227",
    "entry_d96t",
]
cross_missing = [
    name for name in cross_bank_needed if name not in esc4_addr
]
if cross_missing:
    sys.exit(
        "gen_escbank3_syms: missing escbank4 symbols: %s"
        % cross_missing
    )
cross_lines = [
    "; >>> ESCBANK3_XBANK_SYMS -- auto-generated by "
    "tools/gen_escbank3_syms.py (do not edit) <<<"
]
for name in cross_bank_needed:
    cross_lines.append("%s=$98%04X" % (name, esc4_addr[name]))
cross_lines.append("; <<< ESCBANK3_XBANK_SYMS <<<")
cross_block = "\n".join(cross_lines)
cross_pat = re.compile(
    r"; >>> ESCBANK3_XBANK_SYMS.*?; <<< ESCBANK3_XBANK_SYMS <<<",
    re.DOTALL,
)
src = (
    cross_pat.sub(cross_block, src)
    if cross_pat.search(src)
    else src.replace(
        "; <<< ESCBANK3_SYMS <<<",
        "; <<< ESCBANK3_SYMS <<<\n\n" + cross_block,
        1,
    )
)

esc_path.write_text(src)
print(
    "gen_escbank3_syms: wrote %d bank-$00 + %d bank-$98 symbols%s"
    % (
        len(NEEDED) - len(missing),
        len(cross_bank_needed),
        (" (MISSING: %s)" % missing) if missing else "",
    )
)
