#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $02F542 bounds leaf in bank $9F."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "escbank9.pasm"
TRANSPILE = ROOT / "tools" / "transpile.py"
START = "; >>> STAGE3_2F542 — generated by tools/gen_stage3_2f542.py <<<"
END = "; <<< STAGE3_2F542 <<<"
PC = 0x02F542


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 11 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $02F542 transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_2f542:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """    .org $FE00
.a16
.i16
; Reserved island $9F:FE00-$9F:FFFF; source PC $02F542.
entry_2f542t:
    rep #$30
    ; A4 accesses use the exact generic 68000 address helpers.  Only the
    ; faithful RTS is direct: reject before the first architectural write
    ; unless its genuine return lies in canonical mapped work RAM.
    lda $3E
    cmp #$00F0
    bne h2f542_cold
    lda $3C
    cmp #$3FFD
    bcs h2f542_cold
    bra h2f542_hot
h2f542_cold:
    lda #$F542
    sta $40
    lda #$0002
    sta $42
    jml.l inext
h2f542_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $02F542 table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if body.count("    jsr esc9_ac_charge\n") != 6:
        raise RuntimeError("$02F542 lost an AC-charge basic block")
    return body + "\nentry_2f542t_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $02F542 generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_2f542: regenerated $02F542@$9F:FE00")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
