#!/usr/bin/env python3
"""Refresh cross-bank imports for escape bank $9D."""

import re
import sys
from pathlib import Path


SOURCE = Path("src/escbank7.pasm")
IMPORTS = [
    (
        Path("src/escbank3.sym"),
        0x97,
        [
            "h25110_stage2_generated_setup",
            "Lf25110_144",
            "Lf25110_267",
            "L25110_25816",
            "h25110_final_tst_rebuild",
            "entry_1d5f0",
            "Lcaf6_cb9c",
            "entry_1f1c0_generated",
        ],
    ),
    (
        Path("src/interp.sym"),
        0x00,
        [
            "op_rte",
            "inext",
            "jsrabs_hook",
            "push32_l",
            "rdw_ea_l",
            "usmul_l",
            "readbyte_l",
            "writeword_l",
            "writebyte_l",
            "ojmp_hook",
            "ors_pre",
            "h20e8_fill_resume",
            "_20e8_t53",
        ],
    ),
    (
        Path("src/escbank2.sym"),
        0x94,
        [
            "h158_dma_1020", "h158_set_ccr", "h158_dma_residue", "xd_table",
            "entry_1008", "entry_c9a6",
        ],
    ),
    (
        Path("src/escbank.sym"),
        0x92,
        [
            "entry_c2f8",
            "entry_2658e",
            "entry_4542",
            "entry_ce58",
            "entry_2bda_generated_resume",
            "entry_3c36_generated_resume",
            "br3c36_5",
            "ibridge",
            "entry_2df0",
            "entry_4178",
            "entry_3a92",
        ],
    ),
    (
        Path("src/escbank2.sym"),
        0x94,
        ["entry_c172", "entry_295at", "entry_29b6t"],
    ),
    (
        Path("src/escbank5.sym"),
        0x99,
        [
            "entry_24bc2", "entry_2429c", "entry_c846", "entry_11752",
            "entry_96a", "entry_9ea", "entry_24920t", "entry_24956t",
        ],
    ),
    (
        Path("src/escbank6.sym"),
        0x95,
        [
            "entry_2a190",
            "entry_175a0",
            "entry_1c11a",
            "entry_29128",
            "entry_29144",
        ],
    ),
]


if not SOURCE.exists():
    raise SystemExit(0)
resolved: list[tuple[str, int]] = []
for symbols, mapped_bank, needed in IMPORTS:
    if not symbols.exists():
        sys.exit(f"gen_escbank7_syms: {symbols} missing")
    available: dict[str, int] = {}
    for raw in symbols.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"\s*00:([0-9A-Fa-f]{4})\s+(\S+)", raw)
        if match:
            available[match.group(2)] = int(match.group(1), 16)
    missing = [name for name in needed if name not in available]
    if missing:
        sys.exit(f"gen_escbank7_syms: missing {symbols} symbols: {missing}")
    resolved.extend(
        (name, (mapped_bank << 16) | available[name]) for name in needed
    )

lines = [
    "; >>> ESCBANK7_SYMS — auto-generated by tools/gen_escbank7_syms.py (do not edit) <<<"
]
lines.extend(f"{name}=${address:06X}" for name, address in resolved)
lines.append("; <<< ESCBANK7_SYMS <<<")
block = "\n".join(lines)

source = SOURCE.read_text(encoding="utf-8")
pattern = re.compile(
    r"; >>> ESCBANK7_SYMS.*?; <<< ESCBANK7_SYMS <<<", re.DOTALL
)
if not pattern.search(source):
    sys.exit("gen_escbank7_syms: marked symbol block missing")
SOURCE.write_text(pattern.sub(block, source), encoding="utf-8")
print(f"gen_escbank7_syms: wrote {len(resolved)} symbols")
