#!/usr/bin/env python3
"""Regenerate guarded Stage-3 draw wrappers in bank $9D.

The original wrappers call the already-native $02E49C lookup and then a
runtime renderer callback.  The transpiler supplies the exact register/CCR/X,
argument-frame, dynamic AC-charge, and indirect-bridge behavior.  This
generator adds:

* read-only entry guards for the two direct-mapped pointers;
* the bank-$9D AC-charge helper name; and
* the genuine MC68000 callback-return residue below A7, replacing the native
  bridge sentinel after the callback returns.

Fixed 512-byte islands make Poppy's otherwise-silent .org overlap detectable
by the ROM packer.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank7.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = (
    "; >>> STAGE3_DRAW_WRAPPERS — generated by "
    "tools/gen_stage3_draw_wrappers.py <<<"
)
END = "; <<< STAGE3_DRAW_WRAPPERS <<<"
SPECS = (
    (0x02E4B8, 0xDC00, 0xE000, 0x02E4F0),
    # $9D:E000-$E18F remains the pinned $CD1A/$0FB8 fusion.  This wrapper
    # occupies the otherwise-zero seam immediately after it.
    (0x02E524, 0xE190, 0xE400, 0x02E554),
)
FLAGS = (
    "--bank7",
    "--table",
    "--exitccr",
    "--xflag",
    "--accharge",
    "--restore-static-residue",
)


def guard(pc: int) -> str:
    hot = f"h{pc:x}_hot"
    cold = f"h{pc:x}_cold"
    return f"""    ; A5 supplies the callback pointer through a direct BW-RAM
    ; access, while push32_l writes the emulated A7 stack.  Reject before the
    ; first architectural change unless both ranges are canonical.
    lda $36
    cmp #$00F0
    bne {cold}
    lda $34
    cmp #$234F
    bcs {cold}
    lda $3E
    cmp #$00F0
    bne {cold}
    lda $3C
    cmp #$0012
    bcc {cold}
    cmp #$3FFD
    bcs {cold}
    bra {hot}
{cold}:
    lda #${pc & 0xFFFF:04X}
    sta $40
    lda #${pc >> 16:04X}
    sta $42
    jml.l inext
{hot}:
"""


def callback_residue(label: str, return_pc: int) -> str:
    return f"""{label}:
    ; The indirect bridge used a private $00F8 sentinel.  Restore the exact
    ; real JSR return bytes that the arcade leaves below the popped A7.
    lda $3C
    sec
    sbc #$0004
    tax
    lda #${return_pc >> 16:04X}
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #${return_pc & 0xFFFF:04X}
    xba
    sta $400000,x
    xba
"""


def generate(pc: int, origin: int, limit: int, callback_return: int) -> str:
    result = subprocess.run(
        [sys.executable, str(TRANSPILE), f"{pc:06X}", *FLAGS],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        f"all " not in result.stderr
        or "instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            f"incomplete Stage-3 draw wrapper ${pc:06X}:\n"
            f"{result.stdout}\n{result.stderr}"
        )
    body = result.stdout.rstrip()
    name = f"entry_{pc:x}"
    prologue = (
        f"{name}:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = (
        f"{name}:\n"
        "    rep #$30\n"
        + guard(pc)
        + "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    if body.count(prologue) != 1:
        raise RuntimeError(f"unexpected ${pc:06X} table prologue")
    body = body.replace(prologue, guarded, 1)

    charge_calls = body.count("    jsr esc_ac_charge\n")
    if charge_calls < 3:
        raise RuntimeError(
            f"${pc:06X} unexpectedly has only {charge_calls} AC-charge sites"
        )
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc7_ac_charge\n"
    )

    # The callee is a fixed, independently guarded native leaf.  Retain the
    # exact private return push (so its RTS and residue remain architectural),
    # but skip the generic ojmp/xlat lookup.  If the callee rejects A4/A7 or
    # its selector, its own cold path installs $02E49C and enters the
    # interpreter with this same sentinel still on the emulated stack.
    generic_e49c_edge = (
        "    lda #$E49C\n"
        "    sta $40\n"
        "    lda #$0002\n"
        "    sta $42\n"
        "    jml.l ojmp_hook\n"
    )
    if body.count(generic_e49c_edge) != 1:
        raise RuntimeError(
            f"${pc:06X} lost its unique generic $02E49C call edge"
        )
    body = body.replace(
        generic_e49c_edge,
        "    ; Fixed guarded native edge to $02E49C@$94:D340.\n"
        "    jml.l $94D340\n",
        1,
    )

    callback_label = f"br{pc:x}_2"
    label_line = f"{callback_label}:\n"
    if body.count(label_line) != 1:
        raise RuntimeError(
            f"${pc:06X} lost its unique callback continuation"
        )
    body = body.replace(
        label_line,
        callback_residue(callback_label, callback_return),
        1,
    )
    return (
        f"    .org ${origin:04X}\n"
        ".a16\n"
        ".i16\n"
        f"; Reserved island ${origin:04X}-${limit - 1:04X}; "
        f"source PC ${pc:06X}.\n"
        f"{body}\n"
        f"{name}_end:\n"
    )


def main() -> int:
    text = SOURCE.read_text()
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 draw-wrapper generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    generated = "\n\n".join(
        generate(pc, origin, limit, callback_return).rstrip()
        for pc, origin, limit, callback_return in SPECS
    )
    SOURCE.write_text(
        before
        + START
        + "\n"
        + generated
        + "\n"
        + END
        + after
    )
    print(
        "gen_stage3_draw_wrappers: regenerated "
        + ", ".join(
            f"${pc:06X}@${origin:04X}"
            for pc, origin, _limit, _return in SPECS
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
