#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $027AEA collision/status leaf."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = "; >>> STAGE3_27AEA — generated by tools/gen_stage3_27aea.py <<<"
END = "; <<< STAGE3_27AEA <<<"
PC = 0x027AEA


def replace_canonical_word_read(
    body: str,
    *,
    base: str,
    high: str,
    displacement: int,
    count: int,
) -> str:
    """Inline a word read already proved to remain in bank-$F0 work RAM."""

    pattern = (
        f"    lda {base}\n"
        "    clc\n"
        f"    adc #${displacement:04X}\n"
        "    sta $54\n"
        f"    lda {high}\n"
        "    adc #$0000\n"
        "    sta $52\n"
        "    jsl.l rdw_ea_l\n"
    )
    replacement = (
        f"    ldx {base}\n"
        f"    lda $40{displacement:04X},x\n"
        "    xba\n"
    )
    if body.count(pattern) != count:
        raise RuntimeError(
            "$027AEA lost canonical word read "
            f"{base}+${displacement:02X}: "
            f"expected {count}, found {body.count(pattern)}"
        )
    return body.replace(pattern, replacement)


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 27 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $027AEA transpilation:\n"
            + result.stdout
            + result.stderr
        )

    body = result.stdout.rstrip()
    prologue = (
        "entry_27aea:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """    .org $C000
.a16
.i16
; Reserved island $9F:C000-$CFFF; source PC $027AEA.
entry_27aea:
    rep #$30
    ; This leaf writes through two pointers stored in the current object
    ; record and pops a genuine 68000 return. Reject before the first
    ; architectural change unless the record, pointers, and stack are all in
    ; the canonical mapped 16 KiB work-RAM window.
    lda $32
    cmp #$00F0
    bne h27aea_cold
    lda $30
    cmp #$3FE5
    bcs h27aea_cold
    tax
    lda $400018,x
    xba
    cmp #$00F0
    bne h27aea_cold
    lda $40001A,x
    xba
    cmp #$3FF1
    bcs h27aea_cold
    lda $40000E,x
    xba
    cmp #$00F0
    bne h27aea_cold
    lda $400010,x
    xba
    cmp #$3FF1
    bcs h27aea_cold
    lda $3E
    cmp #$00F0
    bne h27aea_cold
    lda $3C
    cmp #$3FFD
    bcs h27aea_cold
    bra h27aea_hot
h27aea_cold:
    lda #$7AEA
    sta $40
    lda #$0002
    sta $42
    jml.l inext
h27aea_hot:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $027AEA table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace("    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n")
    if body.count("    jsr esc9_ac_charge\n") != 8:
        raise RuntimeError("$027AEA lost an AC-charge basic block")

    # The entry guard proves A4 and both pointer longs are bank-$F0 mapped
    # with enough tail room for every displacement.  Avoid eight round trips
    # through the generic EA helper while retaining the generated branch,
    # register, CCR/X, and instruction-charge structure.
    for base, high, displacement, count in (
        ("$30", "$32", 0x18, 1),
        ("$30", "$32", 0x1A, 1),
        ("$2C", "$2E", 0x0E, 2),
        ("$30", "$32", 0x0E, 2),
        ("$30", "$32", 0x10, 2),
    ):
        body = replace_canonical_word_read(
            body,
            base=base,
            high=high,
            displacement=displacement,
            count=count,
        )

    byte_pattern = (
        "    lda $2C\n"
        "    clc\n"
        "    adc #$000D\n"
        "    sta $54\n"
        "    lda $2E\n"
        "    adc #$0000\n"
        "    sta $52\n"
        "    jsl.l readbyte_l\n"
    )
    byte_replacement = (
        "    ldx $2C\n"
        "    lda $40000D,x\n"
        "    and #$00FF\n"
    )
    if body.count(byte_pattern) != 1:
        raise RuntimeError("$027AEA lost its canonical A6+$0D byte read")
    body = body.replace(byte_pattern, byte_replacement, 1)
    return body + "\nentry_27aea_end:\n"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit("Stage-3 $027AEA generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    SOURCE.write_text(
        before + START + "\n" + generate() + END + after,
        encoding="utf-8",
    )
    print("gen_stage3_27aea: regenerated $027AEA@$9F:C000")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
