#!/usr/bin/env python3
"""Refresh bank-$00 imports for the sixth SA-1 escape bank ($95:8000)."""

import re
import sys
from pathlib import Path

NEEDED = [
    "inext",
    "rdw40_l",
    "wrw40_l",
    "rdb40_l",
    "wrb40_l",
    "push32_l",
    "rdw_ea_l",
    "readbyte_l",
    "writeword_l",
    "writebyte_l",
    "usmul_l",
    "op_rts",
    "op_rts_sentinel",
    "ojmp_hook",
    "ors_pre",
]
XBANK = [
    ("ibridge", "src/escbank.sym", 0x92),
    ("entry_295at", "src/escbank2.sym", 0x94),
    ("entry_29b6t", "src/escbank2.sym", 0x94),
    ("h158_dma_residue", "src/escbank2.sym", 0x94),
    ("h96a_generated_resume", "src/escbank5.sym", 0x99),
    ("h9ea_generated_resume", "src/escbank5.sym", 0x99),
    ("entry_c262_generated_resume", "src/escbank5.sym", 0x99),
    ("entry_2742t", "src/escbank5.sym", 0x99),
    ("L25110_25122", "src/escbank3.sym", 0x97),
    ("h25110_stage1_done", "src/escbank3.sym", 0x97),
    ("Lcaf6_cb9c", "src/escbank3.sym", 0x97),
]


def load_syms(path: str) -> dict[str, tuple[int, int]]:
    out: dict[str, tuple[int, int]] = {}
    source = Path(path)
    if not source.exists():
        return out
    for line in source.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
        if match:
            out[match.group(3)] = (int(match.group(1), 16), int(match.group(2), 16))
    return out


interp_path = Path("src/interp.sym")
source_path = Path("src/escbank6.pasm")
if not interp_path.exists():
    sys.exit("gen_escbank6_syms: src/interp.sym missing")
if not source_path.exists():
    sys.exit(0)

interp = load_syms(str(interp_path))
lines = ["; >>> ESCBANK6_SYMS — auto-generated by tools/gen_escbank6_syms.py (do not edit) <<<"]
missing: list[str] = []
for name in NEEDED:
    if name in interp:
        bank, offset = interp[name]
        lines.append(f"{name}=${bank:02X}{offset:04X}")
    else:
        missing.append(name)
for name, sym_path, bank in XBANK:
    symbols = load_syms(sym_path)
    if name in symbols:
        lines.append(f"{name}=${bank:02X}{symbols[name][1]:04X}")
    else:
        missing.append(name)
lines.append("; <<< ESCBANK6_SYMS <<<")
block = "\n".join(lines)

source = source_path.read_text()
pattern = re.compile(r"; >>> ESCBANK6_SYMS.*?; <<< ESCBANK6_SYMS <<<", re.DOTALL)
source = pattern.sub(block, source) if pattern.search(source) else block + "\n\n" + source
source_path.write_text(source)
print(
    "gen_escbank6_syms: wrote %d symbols%s"
    % (
        len(NEEDED) + len(XBANK) - len(missing),
        f" (MISSING: {missing})" if missing else "",
    )
)
