#!/usr/bin/env python3
"""Refresh cross-bank imports for escape bank $9E."""

from __future__ import annotations

import re
import sys
from pathlib import Path


SOURCE = Path("src/escbank8.pasm")
IMPORTS = (
    (
        Path("src/interp.sym"),
        0x00,
        (
            "inext",
            "op_rte",
            "push32_l",
            "rdw_ea_l",
            "readbyte_l",
            "writeword_l",
            "usmul_l",
            "ors_pre",
        ),
    ),
    (Path("src/escbank5.sym"), 0x99, ("entry_24cb6", "entry_96a")),
    (
        Path("src/escbank7.sym"),
        0x9D,
        (
            "entry_24aa8t",
            "entry_28f92t",
            "entry_91et",
            "entry_c0bc_generated",
            "c0bc_hle_29b6_return",
            "entry_29b6_fast",
        ),
    ),
    (Path("src/escbank2.sym"), 0x94, ("xd_table", "entry_8fat")),
)


def load(path: Path) -> dict[str, int]:
    values: dict[str, int] = {}
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"\s*[0-9A-Fa-f]{2}:([0-9A-Fa-f]{4})\s+(\S+)", raw)
        if match:
            values[match.group(2)] = int(match.group(1), 16)
    return values


def main() -> int:
    if not SOURCE.exists():
        return 0
    resolved: list[tuple[str, int]] = []
    for path, bank, names in IMPORTS:
        if not path.exists():
            raise SystemExit(f"gen_escbank8_syms: missing {path}")
        available = load(path)
        missing = [name for name in names if name not in available]
        if missing:
            raise SystemExit(f"gen_escbank8_syms: missing {path} symbols: {missing}")
        resolved.extend((name, (bank << 16) | available[name]) for name in names)

    lines = [
        "; >>> ESCBANK8_SYMS — auto-generated by tools/gen_escbank8_syms.py (do not edit) <<<"
    ]
    lines.extend(f"{name}=${address:06X}" for name, address in resolved)
    lines.append("; <<< ESCBANK8_SYMS <<<")
    block = "\n".join(lines)
    source = SOURCE.read_text(encoding="utf-8")
    pattern = re.compile(
        r"; >>> ESCBANK8_SYMS.*?; <<< ESCBANK8_SYMS <<<", re.DOTALL
    )
    if len(pattern.findall(source)) != 1:
        raise SystemExit("gen_escbank8_syms: marked symbol block missing or duplicated")
    SOURCE.write_text(pattern.sub(block, source), encoding="utf-8")
    print(f"gen_escbank8_syms: wrote {len(resolved)} symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
