#!/usr/bin/env python3
"""Regenerate the guarded Stage-3 $02E42C selector in bank $9F."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank9.pasm"
TRANSPILE = ROOT / "tools/transpile.py"
START = "; >>> STAGE3_SELECTOR — generated by tools/gen_stage3_selector.py <<<"
END = "; <<< STAGE3_SELECTOR <<<"
FAST_START = (
    "; >>> STAGE3_SELECTOR_FAST — generated by "
    "tools/gen_stage3_selector.py <<<"
)
FAST_END = "; <<< STAGE3_SELECTOR_FAST <<<"
PC = 0x02E42C


def callback_residue(label: str, return_pc: int) -> str:
    return f"""{label}:
    ; Replace the private bridge tag below the popped A7 with the exact
    ; original JSR return bytes retained by the arcade.
    lda $3C
    sec
    sbc #$0004
    tax
    lda #${return_pc >> 16:04X}
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #${return_pc & 0xFFFF:04X}
    xba
    sta $400000,x
    xba
"""


def generate() -> str:
    result = subprocess.run(
        [
            sys.executable,
            str(TRANSPILE),
            f"{PC:06X}",
            "--bank7",
            "--table",
            "--exitccr",
            "--xflag",
            "--accharge",
            "--restore-static-residue",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    if (
        "all 19 instrs transpiled" not in result.stderr
        or "UNIMPLEMENTED" in result.stdout
        or "BAIL" in result.stderr
    ):
        raise RuntimeError(
            "incomplete $02E42C selector transpilation:\n"
            + result.stdout
            + result.stderr
        )
    body = result.stdout.rstrip()
    prologue = (
        "entry_2e42c:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack "
        "-> NO re-simulate push\n"
    )
    guarded = """entry_2e42c:
    rep #$30
    ; MOVEM pushes 28 bytes and the two nested calls need another eight.
    ; Reject before any architectural write unless the complete frame and
    ; existing caller return remain inside canonical work RAM.
    lda $3E
    cmp #$00F0
    bne h2e42c_cold
    lda $3C
    cmp #$0024
    bcc h2e42c_cold
    cmp #$3FFD
    bcs h2e42c_cold
    bra h2e42c_hot
h2e42c_cold:
    lda #$E42C
    sta $40
    lda #$0002
    sta $42
    jml.l inext
h2e42c_hot:
    ; The retained Stage-3 checkpoint has two selector families.  Admit only
    ; their exact callback/type/count tuples to the direct-frame loop below.
    ; Every other canonical state retains the generated implementation.
    lda $22
    cmp #$0002
    bne h2e42c_generated
    lda $20
    cmp #$78E8
    beq h2e42c_guard_278e8
    cmp #$F2E0
    bne h2e42c_generated
    lda $00
    and #$00FF
    cmp #$0003
    bne h2e42c_generated
    lda $04
    cmp #$0009
    bne h2e42c_generated
    jmp h2e42c_fast_entry
h2e42c_guard_278e8:
    lda $00
    and #$00FF
    cmp #$0009
    bne h2e42c_generated
    lda $04
    cmp #$0006
    bne h2e42c_generated
    jmp h2e42c_fast_entry
h2e42c_generated:
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
"""
    if body.count(prologue) != 1:
        raise RuntimeError("unexpected $02E42C table prologue")
    body = body.replace(prologue, guarded, 1)
    body = body.replace(
        "    jsr esc_ac_charge\n", "    jsr esc9_ac_charge\n"
    )
    if body.count("    jsr esc9_ac_charge\n") < 5:
        raise RuntimeError("$02E42C lost dynamic AC-charge sites")

    bsr_bridge = (
        "    lda #br2e42c_1\n"
        "    sta $54\n"
        "    lda #$00F8\n"
        "    sta $56\n"
    )
    bsr_pinned = (
        "    lda #$E3C0\n"
        "    sta $54\n"
        "    lda #$00F8\n"
        "    sta $56\n"
    )
    if body.count(bsr_bridge) != 1:
        raise RuntimeError("$02E42C lost its unique BSR bridge")
    body = body.replace(bsr_bridge, bsr_pinned, 1)

    callback_bridge = (
        "    lda #br2e42c_2\n"
        "    sta $40\n"
        "    lda #$00F8\n"
        "    sta $42\n"
    )
    callback_pinned = (
        "    lda #$E3C4\n"
        "    sta $40\n"
        "    lda #$00F8\n"
        "    sta $42\n"
    )
    if body.count(callback_bridge) != 1:
        raise RuntimeError("$02E42C lost its unique indirect bridge")
    body = body.replace(callback_bridge, callback_pinned, 1)

    label = "br2e42c_2:\n"
    if body.count(label) != 1:
        raise RuntimeError("$02E42C lost its callback continuation")
    body = body.replace(label, callback_residue("br2e42c_2", 0x02E44C), 1)
    return (
        "    .org $A140\n"
        ".a16\n"
        ".i16\n"
        "; Reserved selector island $9F:A140-$A7FF.\n"
        + body
        + "\nentry_2e42c_end:\n"
    )


def generate_fast() -> str:
    """Emit the exact direct-frame loop for the two live Stage-3 families."""

    return """    .org $A900
.a16
.i16
; The private $00F8 selector callback tag first lands on a pinned bank-$9D
; trampoline, then resumes here.  A7 points at the saved seven-register
; MOVEM frame exactly as it does after the original callback RTS.
entry_2e42c_fast_callback_resume:
    ; Retain the original JSR (A0) return residue below the popped A7.
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$E44C
    xba
    sta $400000,x
    xba

    ; MOVEM restore / SUBQ.W #1,D1 / BEQ is one source basic block.
    php
    rep #$30
    lda #$0003
    jsr esc9_ac_charge
    plp
    jsr h2e42c_fast_restore
    lda $04
    sec
    sbc #$0001
    sta $04
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    lda $50
    and #$0040
    sta $72
    lda $50
    and #$0001
    eor #$0001
    sta $6E
    sta $A2
    lda $04
    beq h2e42c_fast_return
    jmp h2e42c_fast_skip

h2e42c_fast_return:
    ; Faithful selector RTS: charge it, pop the genuine parent return, and
    ; retain SUBQ's final CCR/X (for the admitted positive count it is Z=1).
    php
    rep #$30
    lda #$0001
    jsr esc9_ac_charge
    plp
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; Entry is reached only after the read-only tuple and stack guards at A140.
; The first thirty table bytes cover every captured live slot.  The loop
; reads them on every pass, so callback-side changes are observed.  If the
; requested match count is not exhausted there, architectural state rejoins
; the retained generated loop at the exact next TST.B boundary.
h2e42c_fast_entry:
    php
    rep #$30
    lda #$0003
    jsr esc9_ac_charge
    plp
    stz $08
    lda #$3134
    sta $24
    lda #$00F0
    sta $26
    lda #$3152
    sta $28
    lda #$00F0
    sta $2A

h2e42c_fast_loop:
    ; TST.B (A1)
    php
    rep #$30
    lda #$0002
    jsr esc9_ac_charge
    plp
    ldx $08
    lda $403134,x
    and #$00FF
    bne h2e42c_fast_active
    jmp h2e42c_fast_skip

h2e42c_fast_active:
    ; CMP.B (A2),D0 / BNE
    php
    rep #$30
    lda #$0002
    jsr esc9_ac_charge
    plp
    ldx $08
    lda $403152,x
    and #$00FF
    sta $9A
    lda $00
    and #$00FF
    cmp $9A
    beq h2e42c_fast_match
    jmp h2e42c_fast_skip

h2e42c_fast_match:
    ; MOVEM.L D0-D3/A0-A2,-(A7) / MOVE.B D2,D0 / BSR $02E40E.
    php
    rep #$30
    lda #$0003
    jsr esc9_ac_charge
    plp
    jsr h2e42c_fast_save
    lda $08
    and #$00FF
    sep #$20
    sta $00
    rep #$20

    ; Inline the proven $02E40E leaf while retaining its three dynamic
    ; instruction-charge boundaries and exact D0/A4/CCR/X outputs.
    php
    rep #$30
    lda #$0003
    jsr esc9_ac_charge
    plp
    lda #$3CF6
    sta $30
    lda #$00F0
    sta $32
    lda $00
    and #$00FF
    sta $9A
    cmp #$0007
    bcc h2e42c_fast_index_ready
    php
    rep #$30
    lda #$0002
    jsr esc9_ac_charge
    plp
    lda #$2BB4
    sta $30
    lda #$00F0
    sta $32
    lda $9A
    sec
    sbc #$0007
    sta $9A

h2e42c_fast_index_ready:
    php
    rep #$30
    lda #$0005
    jsr esc9_ac_charge
    plp
    lda $9A
    and #$00FF
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a
    sta $00
    stz $02
    lda $30
    clc
    adc $00
    sta $30
    lda $32
    adc $02
    sta $32
    stz $6E
    stz $A2
    stz $70
    stz $72
    lda $00
    beq h2e42c_fast_shift_zero
    stz $60
    bra h2e42c_fast_shift_done
h2e42c_fast_shift_zero:
    lda #$0002
    sta $60
h2e42c_fast_shift_done:

    ; JSR (A0): admission proved that A0 is exactly $0278E8 or $02F2E0.
    ; Materialize the genuine private return on the 68000 stack, then enter
    ; the corresponding table-convention body directly.  This removes only
    ; the generic indirect-dispatch scan; both callees retain their own
    ; complete guards and may still delegate to the interpreter untouched.
    ; The resume above restores exact $02E44C stack residue afterward.
    php
    rep #$30
    lda #$0001
    jsr esc9_ac_charge
    plp
    lda #$E3F0
    sta $40
    sta $54
    lda #$00F8
    sta $42
    sta $56
    jsl.l push32_l
    lda $20
    cmp #$78E8
    beq h2e42c_fast_call_278e8
    lda #$F2E0
    sta $40
    lda #$0002
    sta $42
    jmp entry_2f2e0t
h2e42c_fast_call_278e8:
    lda #$78E8
    sta $40
    lda #$0002
    sta $42
    jmp entry_278e8

h2e42c_fast_skip:
    ; ADDQ.W #1,D2 / ADDA.L #1,A1 / ADDA.L #1,A2 / BRA.
    php
    rep #$30
    lda #$0004
    jsr esc9_ac_charge
    plp
    lda $08
    clc
    adc #$0001
    sta $08
    ; D2 starts at zero and this direct island ends at thirty, so ADDQ's
    ; exact result flags and X are all clear throughout the admitted span.
    stz $60
    stz $6E
    stz $A2
    stz $70
    stz $72
    lda $24
    clc
    adc #$0001
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $28
    clc
    adc #$0001
    sta $28
    lda $2A
    adc #$0000
    sta $2A
    lda $08
    cmp #$001E
    bcs h2e42c_fast_fallback
    jmp h2e42c_fast_loop
h2e42c_fast_fallback:
    jmp L2e42c_2e43a

; Direct big-endian equivalent of MOVEM.L D0-D3/A0-A2,-(A7).
h2e42c_fast_save:
    lda $3C
    sec
    sbc #$001C
    sta $3C
    tax
    lda $02
    xba
    sta $400000,x
    lda $00
    xba
    sta $400002,x
    lda $06
    xba
    sta $400004,x
    lda $04
    xba
    sta $400006,x
    lda $0A
    xba
    sta $400008,x
    lda $08
    xba
    sta $40000A,x
    lda $0E
    xba
    sta $40000C,x
    lda $0C
    xba
    sta $40000E,x
    lda $22
    xba
    sta $400010,x
    lda $20
    xba
    sta $400012,x
    lda $26
    xba
    sta $400014,x
    lda $24
    xba
    sta $400016,x
    lda $2A
    xba
    sta $400018,x
    lda $28
    xba
    sta $40001A,x
    rts

; Direct big-endian equivalent of MOVEM.L (A7)+,D0-D3/A0-A2.
h2e42c_fast_restore:
    ldx $3C
    lda $400000,x
    xba
    sta $02
    lda $400002,x
    xba
    sta $00
    lda $400004,x
    xba
    sta $06
    lda $400006,x
    xba
    sta $04
    lda $400008,x
    xba
    sta $0A
    lda $40000A,x
    xba
    sta $08
    lda $40000C,x
    xba
    sta $0E
    lda $40000E,x
    xba
    sta $0C
    lda $400010,x
    xba
    sta $22
    lda $400012,x
    xba
    sta $20
    lda $400014,x
    xba
    sta $26
    lda $400016,x
    xba
    sta $24
    lda $400018,x
    xba
    sta $2A
    lda $40001A,x
    xba
    sta $28
    lda $3C
    clc
    adc #$001C
    sta $3C
    rts
entry_2e42c_fast_end:
"""


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    if (
        text.count(START) != 1
        or text.count(END) != 1
        or text.count(FAST_START) != 1
        or text.count(FAST_END) != 1
    ):
        raise SystemExit("Stage-3 selector generation markers are missing")
    before, remainder = text.split(START, 1)
    _old, after = remainder.split(END, 1)
    text = before + START + "\n" + generate() + END + after
    before, remainder = text.split(FAST_START, 1)
    _old, after = remainder.split(FAST_END, 1)
    SOURCE.write_text(
        before + FAST_START + "\n" + generate_fast() + FAST_END + after,
        encoding="utf-8",
    )
    print(
        "gen_stage3_selector: regenerated "
        "$02E42C@$9F:A140 and guarded fast loop@$9F:A900"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
