#!/usr/bin/env python3
"""Refresh the auto-generated symbol constants in src/escbank5.pasm.

escbank5.pasm is the FIFTH escape bank (SA-1 $99:8000, file $2C8000) — hosts the $023-25xxx
trap#5-cluster SHELL segments (entry_24bc2/entry_2429c coroutine bodies + their same-bank
callees). Like gen_escbank4_syms.py it pins the bank-$00 jml/jsl targets from interp.sym, and
ADDITIONALLY imports the cross-bank --escapes targets the shells jml.l into: the Phase-1.4
family roots in escbank4 ($98: entry_23342/entry_235e0/entry_23864) and entry_25110 in
escbank3 ($97). The shells' CALL-BRIDGE sentinels are sed'd #$00FD->#$00FA so the resume goes
ors_pre->...->ors_98chk->ors_99chk->ors_pre_99 (bank $99).
"""
import re, sys
from pathlib import Path

NEEDED = ["inext", "rdw40_l", "wrw40_l", "rdb40_l", "wrb40_l", "push32_l",
          "rdw_ea_l", "readbyte_l", "writeword_l", "writebyte_l", "usmul_l",
          "op_rts_sentinel", "ojmp_hook", "ors_pre", "lh_nofire",
          "lh_0818_after_gateway"]
# cross-bank native callees: (symbol, source .sym, forced bank)
XBANK = [("entry_23342", "src/escbank4.sym", 0x98),
         ("entry_235e0", "src/escbank4.sym", 0x98),
         ("entry_23864", "src/escbank4.sym", 0x98),
         ("entry_25110", "src/escbank3.sym", 0x97)] + [
         (n, "src/escbank3.sym", 0x97) for n in    # the $011752 contiguous-tree callees
         ("entry_12e56", "entry_12c1a", "entry_129c6", "entry_12a92", "entry_12af6",
          "entry_117b4", "entry_cc44", "entry_cc80", "entry_caf6")] + [
         # Round-start initial coroutine roots use the proven bank-$92 callable bridge and
         # tail into the already deployed $CE58 continuation.
         ("ibridge", "src/escbank.sym", 0x92),
         ("entry_ce58", "src/escbank.sym", 0x92)]

sym_path = Path("src/interp.sym")
esc_path = Path("src/escbank5.pasm")
if not sym_path.exists():
    sys.exit("gen_escbank5_syms: src/interp.sym missing (build interp.bin with -s first)")
if not esc_path.exists():
    sys.exit(0)  # escbank5 optional

def load_syms(path):
    out = {}
    p = Path(path)
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8-sig").splitlines():
        m = re.match(r"\s*([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)", line)
        if m:
            out[m.group(3)] = (int(m.group(1), 16), int(m.group(2), 16))
    return out

interp = load_syms(sym_path)
lines = ["; >>> ESCBANK5_SYMS — auto-generated by tools/gen_escbank5_syms.py (do not edit) <<<"]
missing = []
for n in NEEDED:
    if n in interp:
        b, o = interp[n]
        lines.append("%s=$%02X%04X" % (n, b, o))
    else:
        missing.append(n)
for n, sym, bank in XBANK:
    syms = load_syms(sym)
    if n in syms:
        lines.append("%s=$%02X%04X" % (n, bank, syms[n][1]))   # .sym bank column is bogus; force
    else:
        missing.append(n)
lines.append("; <<< ESCBANK5_SYMS <<<")
block = "\n".join(lines)

src = esc_path.read_text()
pat = re.compile(r"; >>> ESCBANK5_SYMS.*?; <<< ESCBANK5_SYMS <<<", re.DOTALL)
src = pat.sub(block, src) if pat.search(src) else block + "\n\n" + src
esc_path.write_text(src)
print("gen_escbank5_syms: wrote %d symbols%s" %
      (len(NEEDED) + len(XBANK) - len(missing), (" (MISSING: %s)" % missing) if missing else ""))
