#!/usr/bin/env python3
"""Regenerate guarded late-combat bodies in ``src/escbank7.pasm``."""

from __future__ import annotations

import re
import hashlib
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/escbank7.pasm"
ARCADE_IMAGE = ROOT / "data/superman_m68k.bin"
H20E8_DMA_DATA = ROOT / "src/h20e8_dma_data.bin"
START = "; >>> ESCBANK7_BODIES — generated by tools/gen_escbank7_bodies.py <<<"
END = "; <<< ESCBANK7_BODIES <<<"
ALLOC_START = "; >>> ESCBANK7_ALLOC_BODIES — generated by tools/gen_escbank7_bodies.py <<<"
ALLOC_END = "; <<< ESCBANK7_ALLOC_BODIES <<<"
DA_TASK_START = "; >>> ESCBANK7_DA_TASK_BODIES — generated by tools/gen_escbank7_bodies.py <<<"
DA_TASK_END = "; <<< ESCBANK7_DA_TASK_BODIES <<<"
ENTRY_INIT_START = "; >>> ESCBANK7_ENTRY_INIT_BODIES — generated by tools/gen_escbank7_bodies.py <<<"
ENTRY_INIT_END = "; <<< ESCBANK7_ENTRY_INIT_BODIES <<<"


def generate_h20e8_dma_data() -> bytes:
    """Build the exact late-game color/code row used by the $0020E8 fast path.

    Keep these private-derived bytes out of source control.  The assembly bank
    contains the generated blob so SA-1 PRG-ROM -> BW-RAM DMA can publish the
    same shadow bytes that the guarded software loops produced.
    """

    image = ARCADE_IMAGE.read_bytes()
    if len(image) != 0x80000:
        raise SystemExit(
            f"expected a 512 KiB Superman program image, got {len(image)} bytes"
        )

    payload = bytearray(b"\x28\x00" * 64)
    full_code = bytearray()
    for index in range(14):
        for base in (0x366F6, 0x36712):
            offset = base + index * 2
            tile = int.from_bytes(image[offset : offset + 2], "big")
            full_code.extend(((tile + 0x2000) & 0xFFFF).to_bytes(2, "big"))
    full_code.extend(bytes(8))

    # The 68000 clipping branches produce two additional invariant rows for
    # this descriptor.  Coordinates $0170-$017F retain the first descriptor
    # half and clear the interleaved second half; $0180-$01FF clear both.
    # Keep each exact row adjacent to the original full-row payload so the
    # guarded helper can select one 64-byte DMA source without approximating
    # the clipping loop.
    half_code = bytearray(full_code)
    for offset in range(2, 14 * 4, 4):
        half_code[offset : offset + 2] = b"\x00\x00"
    payload.extend(full_code)
    payload.extend(half_code)
    payload.extend(bytes(64))

    digest = hashlib.sha256(payload).hexdigest()
    if digest != "069f916c815015ed7e0d2b319270e99dcdca086af782e2f374fc681449412f0d":
        raise SystemExit(
            "$0020E8 DMA payload differs from the audited Superman descriptor: "
            + digest
        )
    return bytes(payload)


def workram_entry_guard(body: str, pc: int, entry: str) -> str:
    """Guard direct bank-$40 aliases before a generated body mutates state.

    These bodies use the transpiler's established A5/A7 work-RAM fast path.
    A5 is the game's canonical $F00000 base and the coroutine stack is in the
    same 64 KiB bank.  On any whole-program address-space miss, resume the
    original PC before its first instruction instead of approximating it.
    """

    needle = f"{entry}:\n    rep #$30\n"
    tag = entry.removeprefix("entry_")
    guarded = (
        needle
        + "    lda $34\n"
        + f"    bne h{tag}_cold\n"
        + "    lda $36\n"
        + "    cmp #$00F0\n"
        + f"    bne h{tag}_cold\n"
        + "    lda $3E\n"
        + "    cmp #$00F0\n"
        + f"    bne h{tag}_cold\n"
        + "    lda $3C\n"
        + "    cmp #$0040\n"
        + f"    bcc h{tag}_cold\n"
        + f"    bra h{tag}_hot\n"
        + f"h{tag}_cold:\n"
        + f"    lda #${pc & 0xFFFF:04X}\n"
        + "    sta $40\n"
        + f"    lda #${(pc >> 16) & 0xFF:04X}\n"
        + "    sta $42\n"
        + "    jml.l inext\n"
        + f"h{tag}_hot:\n"
    )
    if body.count(needle) != 1:
        raise SystemExit(f"unexpected ${pc:06X} entry prologue for {entry}")
    return body.replace(needle, guarded, 1)


def transpile_da_task(
    pc: int,
    convention: str,
    *,
    table_suffix: bool = False,
    real_return_calls: tuple[int, ...] = (),
) -> str:
    """Generate one exact $D8AC/$DAxx coroutine-path component."""

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        f"{pc:06X}",
        "--bank7",
        f"--{convention}",
        "--video",
        "--xflag",
        "--restore-indirect-residue",
        "--restore-static-residue",
    ]
    if real_return_calls:
        command.append(
            "--real-return-calls="
            + ",".join(f"{call:06X}" for call in real_return_calls)
        )
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"transpile failed for ${pc:06X}")
    if "UNIMPLEMENTED" in result.stdout or "BAIL" in result.stderr:
        raise SystemExit(f"transpile emitted an incomplete body for ${pc:06X}")

    body = result.stdout.rstrip()
    original_entry = f"entry_{pc:x}"
    public_entry = original_entry + ("t" if table_suffix else "")
    if table_suffix:
        if body.count(original_entry + ":") != 1:
            raise SystemExit(f"unexpected ${pc:06X} table entry label")
        body = body.replace(original_entry + ":", public_entry + ":", 1)
    body = workram_entry_guard(body, pc, public_entry)
    return body + f"\n{public_entry}_end:"


def transpile_d8ac_task() -> str:
    """Generate the yield-safe hot loop rooted at $D8AC.

    The $D8B0 BSR calls $DA44, which yields at $DA70 before returning.  A
    synthetic bank-$9D continuation would therefore be live scheduler state.
    Push the genuine $00D8B4 return and route $DA44 through its table body;
    the post-yield $DA72 RTS then reaches the generated entry_d8b4 label.
    """

    body = transpile_da_task(
        0x00D8AC,
        "coroutine",
        real_return_calls=(0x00D8B0,),
    )
    bridge = (
        "    lda #$DA44\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext\n"
        "    ; xlat continuation transpiled from $00D8B4\n"
    )
    native_bridge = bridge.replace("jml.l inext", "jml.l ojmp_hook")
    if body.count(bridge) != 1:
        raise SystemExit("unexpected $D8B0 real-return bridge")
    body = body.replace(bridge, native_bridge, 1)

    # entry_d8b4 is an RTE/RTS-xlat continuation within the generated body,
    # so it needs the same address-space proof as the public root.
    continuation = "entry_d8b4:\nbrd8ac_2:\n"
    guarded = (
        "entry_d8b4:\n"
        "    rep #$30\n"
        "    lda $34\n"
        "    bne hd8b4_cold\n"
        "    lda $36\n"
        "    cmp #$00F0\n"
        "    bne hd8b4_cold\n"
        "    lda $3E\n"
        "    cmp #$00F0\n"
        "    bne hd8b4_cold\n"
        "    lda $3C\n"
        "    cmp #$0040\n"
        "    bcc hd8b4_cold\n"
        "    bra hd8b4_hot\n"
        "hd8b4_cold:\n"
        "    lda #$D8B4\n"
        "    sta $40\n"
        "    stz $42\n"
        "    jml.l inext\n"
        "hd8b4_hot:\n"
        "brd8ac_2:\n"
    )
    if body.count(continuation) != 1:
        raise SystemExit("unexpected generated $D8B4 continuation")
    return body.replace(continuation, guarded, 1)


def transpile_da9e_table() -> str:
    """Keep the live $DA9E -> $DAF4 tail inside the table dispatcher."""

    body = transpile_da_task(0x00DA9E, "table", table_suffix=True)
    tail = (
        "Ltjda9e_daf4:\n"
        "    lda #$DAF4\n"
        "    sta $40\n"
        "    lda #$0000\n"
        "    sta $42\n"
        "    jml.l inext\n"
    )
    if body.count(tail) != 1:
        raise SystemExit("unexpected $DA9E -> $DAF4 tail")
    return body.replace(tail, tail.replace("jml.l inext", "jml.l ojmp_hook"), 1)


def transpile_alloc(pc: int, *extra: str) -> str:
    """Generate one callable bank-$9D object-allocation escape."""

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        f"{pc:06X}",
        "--bank7",
        "--exitccr",
        "--xflag",
        *extra,
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"transpile failed for ${pc:06X}")
    if "UNIMPLEMENTED" in result.stdout:
        raise SystemExit(f"transpile emitted an incomplete body for ${pc:06X}")
    body = result.stdout.rstrip()
    if pc == 0x01F2E4:
        # $01F4B0 is a ROM-table leaf.  Its generated table-convention body is
        # pinned at $9E:A000, so the existing synthetic $00F8 return on the
        # emulated stack can enter it directly.  This avoids allocating a new
        # 768-byte $01F4 xlat page when bank $96 has only $200 bytes free.
        needle = (
            "    lda #$F4B0\n"
            "    sta $40\n"
            "    lda #$0001\n"
            "    sta $42\n"
            "    jml.l ojmp_hook"
        )
        replacement = (
            "    lda #$F4B0\n"
            "    sta $40\n"
            "    lda #$0001\n"
            "    sta $42\n"
            "    jml.l $9EA000"
        )
        if body.count(needle) != 1:
            raise SystemExit("unexpected $01F2E4 -> $01F4B0 bridge")
        body = body.replace(needle, replacement, 1)
    return body + f"\nentry_{pc:x}_end:"


def transpile_entry_init(
    pc: int,
    convention: str,
    *,
    table_suffix: bool = False,
    extra: tuple[str, ...] = (),
) -> str:
    """Generate one guarded gameplay-entry initializer in bank $9D's tail.

    These roots are hot only during the organic attract-to-gameplay handoff.
    They all use the canonical A5 work-RAM base and a work-RAM task/caller
    stack.  Prove both before the first mutation; a miss restarts the original
    68000 PC with the already-pushed real return (table entries) or restored
    coroutine frame intact.
    """

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        f"{pc:06X}",
        "--bank7",
        f"--{convention}",
        "--exitccr",
        "--xflag",
        "--bail",
        *extra,
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"transpile failed for entry initializer ${pc:06X}")
    if "UNIMPLEMENTED" in result.stdout or "BAIL" in result.stderr:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"transpile emitted an incomplete entry initializer ${pc:06X}")

    body = result.stdout.rstrip()
    original_entry = f"entry_{pc:x}"
    public_entry = original_entry + ("t" if table_suffix else "")
    if table_suffix:
        if body.count(original_entry + ":") != 1:
            raise SystemExit(f"unexpected ${pc:06X} entry label")
        body = body.replace(original_entry + ":", public_entry + ":", 1)
    body = workram_entry_guard(body, pc, public_entry)
    return body + f"\n{public_entry}_end:"


def transpile_c0bc_init() -> str:
    """Generate $C0BC and bind its organic $29B6 callback to the fast wrapper."""

    body = transpile_entry_init(
        0x00C0BC,
        "coroutine",
        # The organic gameplay-entry callback at A5+$1CC2 is $0029B6;
        # sibling scene states use the already-supported $00295A form.
        # Keep the indirect bridge for every other runtime pointer.
        extra=("--escapes=00295A,0029B6", "--restore-indirect-residue"),
    )
    needle = "    jml.l entry_29b6t"
    if body.count(needle) != 1:
        raise SystemExit("unexpected $C0BC -> $29B6 direct-link body")
    body = body.replace(
        "; GUARDED DIRECT-LINK jsr (a0): An==$0029B6 -> entry_29b6t native",
        "; GUARDED DIRECT-LINK jsr (a0): An==$0029B6 -> $9D:FC00 fast wrapper",
        1,
    )
    body = body.replace(needle, "    jml.l $9DFC00", 1)
    old_tail = """Lfc0bc_4:
    lda #$C170
    sta $40
    lda #$0000
    sta $42
    jml.l inext"""
    new_tail = """Lfc0bc_4:
    ; Final ADDI.W #$0040,D2 produces $0380: X=N=Z=V=C=0;
    ; the following ADDA/DBRA preserve those architectural flags.
    stz $A2
    stz $70
    stz $60
    stz $72
    stz $6E
    lda #$C170
    sta $40
    stz $42
    jml.l inext"""
    if body.count(old_tail) != 1:
        raise SystemExit("unexpected $C0BC trap-exit lowering")
    body = body.replace(old_tail, new_tail, 1)

    # Keep the complete generated implementation as the rejection path for the
    # selector-0 production HLE in bank $9E.  Unlike the older C262 wrapper,
    # this entry's generated work-RAM guard precedes the emulated prologue, so
    # retain it wholesale rather than trying to replay only the first six
    # bytes.  The public xlat target becomes a side-effect-free JML wrapper;
    # hle_c0bc rejects to entry_c0bc_generated before changing emulated state.
    public = "entry_c0bc:"
    if body.count(public) != 1:
        raise SystemExit("unexpected $C0BC public entry label")
    body = body.replace(public, "entry_c0bc_generated:", 1)
    wrapper = """entry_c0bc:
    jml.l $9EEC00
    nop
    nop
"""

    # The $29B6 wrapper already owns the bank-$9D $00F8 return convention.
    # Give the bank-$9E HLE a four-byte bank-$9D trampoline so it can reuse
    # that proven router without introducing another synthetic bank sentinel.
    end = "\nentry_c0bc_end:"
    if body.count(end) != 1:
        raise SystemExit("unexpected $C0BC end label")
    body = body.replace(
        end,
        """
c0bc_hle_29b6_return:
    jml.l $9EEE00
entry_c0bc_end:""",
        1,
    )
    return body.replace("entry_c0bc_generated:", wrapper + "entry_c0bc_generated:", 1)


def transpile_24aa8_init() -> str:
    """Generate $024AA8 and materialize its final CLR.W condition codes.

    The generic body reproduces registers and memory but its final optimized
    zero store does not update the emulated CCR.  Replace that last fixed-A5
    address calculation with an equal-size specialized store plus the exact
    CLR.W result: Z=1, N=V=C=0, X unchanged.  Equal size keeps the absolute
    $028F92 entry at $9D:F298.
    """

    body = transpile_entry_init(0x024AA8, "table", table_suffix=True)
    old = """    lda $34
    clc
    adc #$357C
    sta $20
    lda $36
    adc #$0000
    sta $22
    lda #$0000
    pha
    ldx $20
    pla
    xba
    sta $400000,x
    xba"""
    new = """    ; Canonical A5 was guarded above: fixed final CLR.W $F0357C.
    ; The seven NOPs retain the generated body's byte layout exactly.
    ldx #$357C
    lda #$0000
    sta $400000,x
    lda #$0001
    sta $60
    stz $70
    stz $72
    stz $6E
    nop
    nop
    nop
    nop
    nop
    nop
    nop"""
    if body.count(old) != 1:
        raise SystemExit("unexpected $024AA8 final CLR.W lowering")
    return body.replace(old, new, 1)


def transpile_91e_init() -> str:
    """Generate $00091E with a guarded ROM-to-work-RAM DMA copy.

    The original selects one of twenty-seven immutable eleven-pointer lists, then
    copies eleven 32-byte ROM records to consecutive work RAM (the initial
    DBRA count of ten executes eleven iterations).  The generic lowering paid
    for 178 address-space-aware word reads and 176 CPU stores.
    For the exact in-range table interval, map the already-packed arcade ROM
    to $C1-$C8 and issue eleven synchronous 32-byte SA-1 DMA transfers instead.
    Any selector outside that audited interval restarts the untouched 68000
    routine through the interpreter.

    Keep the generated MOVEM stack residue/restores and the final ORI.L
    lowering.  The OR's N bit comes from the resulting high word, while
    Z/V/C are necessarily zero and X is preserved.
    """

    body = transpile_entry_init(0x00091E, "table", table_suffix=True)

    # Every accepted table entry and all ten records must remain inside the
    # packed 512 KiB program image and within a single 64 KiB DMA source bank.
    image = ARCADE_IMAGE.read_bytes()
    for table_offset in range(0, 0x6C, 4):
        table_entry = 0x313E0 + table_offset
        outer = int.from_bytes(image[table_entry : table_entry + 4], "big")
        if outer + 44 > len(image) or (outer >> 16) != ((outer + 43) >> 16):
            raise SystemExit(
                f"$00091E outer table ${table_offset:02X} crosses packed ROM"
            )
        for pointer_offset in range(0, 44, 4):
            pointer = int.from_bytes(
                image[outer + pointer_offset : outer + pointer_offset + 4], "big"
            )
            if pointer + 32 > len(image) or (pointer >> 16) != ((pointer + 31) >> 16):
                raise SystemExit(
                    "$00091E payload crosses packed ROM: "
                    f"table ${table_offset:02X}, pointer ${pointer:06X}"
                )

    hot = "h91et_hot:\n"
    ori_start = """    lda $34
    clc
    adc #$1B12
    tax
"""
    if body.count(hot) != 1 or body.count(ori_start) != 1:
        raise SystemExit("unexpected $00091E generated copy-loop boundaries")
    prefix, remainder = body.split(hot, 1)
    _, suffix = remainder.split(ori_start, 1)
    fast_copy = r"""    ; The original signed selector expression must land on one of the
    ; twenty-seven complete long pointers at $000313E0-$0003144B.  Reject before
    ; MOVEM changes work RAM so the interpreter can restart at $00091E.
    lda $402930
    xba
    bmi h91e_selector_reject
    cmp #$0009
    bcs h91e_selector_reject
    sta $80
    lda $402932
    xba
    bmi h91e_selector_reject
    cmp #$0003
    bcs h91e_selector_reject
    sta $82
    lda $80
    asl a
    asl a
    sta $84                    ; first selector * 4
    asl a
    clc
    adc $84                    ; first selector * 12
    sta $84
    lda $82
    asl a
    asl a
    clc
    adc $84
    cmp #$006C
    bcs h91e_selector_reject
    sta $84                    ; byte offset in the twenty-seven-entry table
    stz $A2                    ; accepted ADD.W has no carry: final preserved X=0
    bra h91e_selector_ready
h91e_selector_reject:
    jmp h91et_cold
h91e_selector_ready:

    ; Preserve the exact predecrement MOVEM residue.  The epilogue below reads
    ; this frame back with the original MOVEM.W sign extension.
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    tax
    lda $04
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    tax
    lda $00
    xba
    sta $400000,x
    xba

    ; Map the selected outer pointer through the packed arcade image.  Native
    ; long-indirect reads see raw byte pairs, hence XBA on each 68K word.
    lda $84
    clc
    adc #$13E0
    sta $8C
    lda #$00C4                ; 68K $0003xxxx -> SA-1 $C4:xxxx
    sta $8E
    ldy #$0000
    lda [$8C],y
    xba
    clc
    adc #$00C1
    sta $8A                   ; mapped bank of the eleven-pointer list
    ldy #$0002
    lda [$8C],y
    xba
    sta $88                   ; low word of the ten-pointer list

    lda #$17D2
    sta $86                   ; fixed A5-relative work-RAM destination
    lda #$000A
    sta $84                   ; eleven records, exact DBRA loop counter
h91e_dma_loop:
    ldy #$0000
    lda [$88],y
    xba
    clc
    adc #$00C1
    sta $92                   ; mapped payload source bank
    ldy #$0002
    lda [$88],y
    xba
    sta $90                   ; payload source low word
    jsr h91e_copy32_dma

    lda $88
    clc
    adc #$0004
    sta $88
    bcc h91e_outer_advanced
    inc $8A
h91e_outer_advanced:
    lda $86
    clc
    adc #$0020
    sta $86
    dec $84
    bpl h91e_dma_loop
    lda #$FFFF
    sta $1C                   ; final DBRA leaves D7.w=-1; D7 high is preserved

"""
    body = prefix + hot + fast_copy + ori_start + suffix

    old = """    lda $34
    clc
    adc #$1B12
    tax
    lda $400000,x
    xba
    ora #$0001
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1B14
    tax
    lda $400000,x
    xba
    ora #$FFC0
    xba
    sta $400000,x
    xba"""
    new = """    ; Canonical A5 was guarded above: final ORI.L at $F01B12.
    ldx #$1B12
    lda $400000,x
    xba
    ora #$0001
    pha
    asl a
    lda #$0000
    rol a
    sta $70
    pla
    xba
    sta $400000,x
    lda $400002,x
    xba
    ora #$FFC0
    xba
    sta $400002,x
    stz $60
    stz $72
    stz $6E

    ; Synchronous mapped-PRG-ROM -> physical BW-RAM bank 0 transfer.
    ; Source=$92:$90, destination=$86, length=32 bytes.
    bra h91e_copy32_dma_done
h91e_copy32_dma:
    sep #$20
.a8
.i16
    lda #$20
    sta $220B
    lda #$84
    sta $2230
    lda $90
    sta $2232
    lda $91
    sta $2233
    lda $92
    sta $2234
    lda #$20
    sta $2238
    stz $2239
    lda $86
    sta $2235
    lda $87
    sta $2236
    stz $2237
    lda #$20
    sta $220B
    stz $2230
    rep #$20
.a16
    rts
h91e_copy32_dma_done:"""
    if body.count(old) != 1:
        raise SystemExit("unexpected $00091E final ORI.L lowering")
    return body.replace(old, new, 1)


def hand_28f92() -> str:
    """Compact exact implementation of the $028F92/$02E358 clear chain.

    The generic transpiler deliberately bails on immediate MOVEA and
    CLR.L (A0)+.  Here every touched address is a fixed offset from the
    guarded canonical work-RAM bank, so word stores are both simpler and
    exact.  Recreate the observable A0, D6, CCR, stack return, and X
    preservation left by the original nested call.
    """

    body = r"""; --- transpiled from $028F92 (hand-specialized fixed clear chain) ---
entry_28f92t:
    rep #$30
    lda $34
    bne h28f92_cold
    lda $36
    cmp #$00F0
    bne h28f92_cold
    lda $3E
    cmp #$00F0
    bne h28f92_cold
    lda $3C
    cmp #$0040
    bcc h28f92_cold
    ; The real RTS return occupies A7..A7+3.  Conservatively reject the whole
    ; interval covering both fixed clear spans and the nested JSR return at
    ; A7-4; the interpreter handles harmless interior gaps too.  Also reject a
    ; four-byte return that crosses the arcade's mapped $F00000-$F03FFF
    ; work-RAM window.  Organic entry was $F016CE in the low fast interval.
    cmp #$3131
    bcc h28f92_hot
    cmp #$3ED8
    bcc h28f92_cold
    cmp #$3FFD
    bcs h28f92_cold
    bra h28f92_hot
h28f92_cold:
    lda #$8F92
    sta $40
    lda #$0002
    sta $42
    jml.l inext

h28f92_hot:
    stz $80
    ldx #$0000
h28f92_clear_objects:
    lda $80
    sta $403CF6,x
    inx
    inx
    cpx #$01C0
    bne h28f92_clear_objects

    lda $80
    sta $403EB6
    sta $403EB8
    sta $403EC0
    sta $403EC4
    sta $403EC6

    ldx #$0000
h28f92_clear_aux:
    lda $80
    sta $403134,x
    inx
    inx
    cpx #$003C
    bne h28f92_clear_aux

    lda $80
    sta $403EC8
    sta $403ECA
    sta $403ECC
    sta $403ECE
    sta $403ED0
    sta $403ED2

    ; $02E358 leaves A0 just past its 30-word clear and D6.W exhausted.
    lda #$3170
    sta $20
    lda #$00F0
    sta $22
    lda #$FFFF
    sta $18
    stz $1A

    ; Final CLR.L $3ED0: Z=1, N=V=C=0, X unchanged.
    lda #$0001
    sta $60
    stz $70
    stz $72
    stz $6E

    ; The nested JSR $02E358 pushes its $028FB8 return at A7-4.  RTS restores
    ; A7 but leaves those four big-endian bytes observable in work RAM.  The
    ; long-X bases encode -4/-2 without spending bytes changing X.
    ldx $3C
    lda #$0200
    sta $3FFFFC,x
    lda #$B88F
    sta $3FFFFE,x

    ; Faithful outer RTS with the real $0076BC return already on the stack.
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
entry_28f92t_end:"""
    return body


def transpile_2ad4c() -> str:
    """Generate the direct body and add a restart-exact address-space guard."""

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        "02AD4C",
        "--bank6",
        "--table",
        "--exitccr",
        "--xflag",
        "--workram=a4",
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit("transpile failed for $02AD4C")

    body = result.stdout.rstrip()
    needle = (
        "entry_2ad4c:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push\n"
    )
    wrapper = (
        "entry_2ad4ct:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack.\n"
        "    ; The direct body assumes A4 and both box pointers stay within the\n"
        "    ; arcade board's mapped low 16 KiB of bank-$F0 work RAM.  Prove\n"
        "    ; that complete read/write reach before its first write.\n"
        "    lda $32\n"
        "    cmp #$00F0\n"
        "    bne h2ad4c_cold\n"
        "    lda $30\n"
        "    cmp #$3FC9\n"
        "    bcs h2ad4c_cold\n"
        "    tax\n"
        "    lda $400030,x\n"
        "    xba\n"
        "    cmp #$00F0\n"
        "    bne h2ad4c_cold\n"
        "    lda $400032,x\n"
        "    xba\n"
        "    cmp #$3FF5\n"
        "    bcs h2ad4c_cold\n"
        "    lda $400034,x\n"
        "    xba\n"
        "    cmp #$00F0\n"
        "    bne h2ad4c_cold\n"
        "    lda $400036,x\n"
        "    xba\n"
        "    cmp #$3FFB\n"
        "    bcs h2ad4c_cold\n"
        "h2ad4c_hot:\n"
        "    jmp h2ad4c_generated\n"
        "\n"
        "h2ad4c_cold:\n"
        "    ; Execute MOVEA.L $30(A4),A3 with the legal address mapper, then\n"
        "    ; resume at $02AD50.  That later PC is not an xlat entry, so the\n"
        "    ; fallback cannot redispatch this wrapper.  MOVEA changes no CCR.\n"
        "    lda $30\n"
        "    clc\n"
        "    adc #$0030\n"
        "    sta $54\n"
        "    lda $32\n"
        "    adc #$0000\n"
        "    sta $52\n"
        "    jsl.l rdw_ea_l\n"
        "    sta $9E\n"
        "    lda $30\n"
        "    clc\n"
        "    adc #$0032\n"
        "    sta $54\n"
        "    lda $32\n"
        "    adc #$0000\n"
        "    sta $52\n"
        "    jsl.l rdw_ea_l\n"
        "    sta $2C\n"
        "    lda $9E\n"
        "    sta $2E\n"
        "    lda #$AD50\n"
        "    sta $40\n"
        "    lda #$0002\n"
        "    sta $42\n"
        "    jml.l inext\n"
        "\n"
        "h2ad4c_generated:\n"
        "    rep #$30\n"
        "    ; Direct transpiled body after the wrapper's complete proof.\n"
    )
    if body.count(needle) != 1:
        raise SystemExit("unexpected $02AD4C transpiler prologue")
    return body.replace(needle, wrapper, 1) + "\nentry_2ad4ct_end:"


def transpile_2a86e() -> str:
    """Generate the table-convention late-combat state handler.

    Unlike the compact $02AD4C leaf, this routine calls back into several
    interpreter/native callees and touches runtime pointers.  Keep all reads
    and writes on the legal address mapper (``--video`` with no ``--workram``
    assertion), preserve real call-return residue, and use bank $9D's $00F8
    continuation sentinel.
    """

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        "02A86E",
        "--bank7",
        "--table",
        "--exitccr",
        "--xflag",
        "--video",
        "--escapes=029128,029144",
        "--restore-static-residue",
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit("transpile failed for $02A86E")

    body = result.stdout.rstrip()
    needle = (
        "entry_2a86e:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push\n"
    )
    wrapper = (
        "entry_2a86et:\n"
        "    rep #$30\n"
        "    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack.\n"
        "    ; Runtime pointers retain the legal ROM/RAM/video address mapper.\n"
    )
    if body.count(needle) != 1:
        raise SystemExit("unexpected $02A86E transpiler prologue")
    return body.replace(needle, wrapper, 1) + "\nentry_2a86et_end:"


def transpile_122a4() -> str:
    """Generate the post-TRAP object collision spine.

    The coroutine resumes at $0122A4, visits eight already-native callees, and
    returns to the next TRAP or the original task tail.  Retain the real 68K
    return residue at every call boundary while eliminating the repeated
    interpreter dispatches between them.
    """

    command = [
        sys.executable,
        str(ROOT / "tools/transpile.py"),
        "0122A4",
        "--coroutine",
        "--bank7",
        "--bail",
        "--xflag",
        "--exitccr",
        "--accharge",
        "--escapes=12e56,12c1a,129c6,cc10,12b6c,12a92,12af6,caf6",
    ]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit("transpile failed for $0122A4")
    if "UNIMPLEMENTED" in result.stdout or "BAIL" in result.stderr:
        raise SystemExit("transpile emitted an incomplete $0122A4 body")

    body = result.stdout.rstrip()
    needle = (
        "entry_122a4:\n"
        "    rep #$30\n"
        "    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)\n"
    )
    wrapper = (
        "entry_122a4:\n"
        "    rep #$30\n"
        "    lda $3A\n"
        "    cmp #$00F0\n"
        "    bne h122a4_cold\n"
        "    lda $3E\n"
        "    cmp #$00F0\n"
        "    bne h122a4_cold\n"
        "    lda $3C\n"
        "    cmp #$0020\n"
        "    bcc h122a4_cold\n"
        "    bra h122a4_hot\n"
        "h122a4_cold:\n"
        "    lda #$22A4\n"
        "    sta $40\n"
        "    lda #$0001\n"
        "    sta $42\n"
        "    jml.l inext\n"
        "h122a4_hot:\n"
        "    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)\n"
    )
    if body.count(needle) != 1:
        raise SystemExit("unexpected $0122A4 transpiler prologue")
    body = body.replace(needle, wrapper, 1)
    if body.count("    jmp entry_12b6c") != 1:
        raise SystemExit("unexpected $0122A4 -> $012B6C call bridge")
    body = body.replace("    jmp entry_12b6c", "    jml.l hle_12b6c", 1)
    charge_calls = body.count("    jsr esc_ac_charge\n")
    if charge_calls != 12:
        raise SystemExit(
            f"expected 12 dynamic AC-charge sites in $0122A4, found {charge_calls}"
        )
    body = body.replace("    jsr esc_ac_charge\n", "    jsr esc7_ac_charge\n")
    helper = """

; Bank-local twin of escbank2's esc_ac_charge.  The RTE hook enters this
; complete 15-instruction 68K spine without returning through iloop between
; its outer instructions, so charge each generated basic block dynamically.
; The eight native callees retain their own established charge contracts.
esc7_ac_charge:
    rep #$30
    pha
    lda $AC
    sec
    sbc $01,s
    bcc esc7_ac_clamp
    beq esc7_ac_clamp
    sta $AC
    pla
    rts
esc7_ac_clamp:
    lda #$0001
    sta $AC
    pla
    rts
"""
    return body + helper + "\nentry_122a4_end:"


def main() -> int:
    h20e8_dma_data = generate_h20e8_dma_data()
    H20E8_DMA_DATA.write_bytes(h20e8_dma_data)

    source = SOURCE.read_text(encoding="utf-8")
    block = (
        START
        + "\n"
        + transpile_2ad4c()
        + "\n\n    .org $8D00\n"
        + transpile_122a4()
        + "\n\n    .org $9000\n"
        + transpile_2a86e()
        + "\n"
        + END
    )
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if len(pattern.findall(source)) != 1:
        raise SystemExit("marked ESCBANK7_BODIES block is missing or duplicated")
    source = pattern.sub(block, source)

    alloc_block = (
        ALLOC_START
        + "\n    .org $B000\n"
        + transpile_alloc(0x02498C)
        + "\n\n    .org $B800\n"
        + transpile_alloc(0x0249C2)
        + "\n\n    .org $C000\n"
        + transpile_alloc(
            0x01F2E4,
            "--escapes=02498C,0249C2",
            "--restore-static-residue",
        )
        + "\n"
        + ALLOC_END
    )
    alloc_pattern = re.compile(
        re.escape(ALLOC_START) + r".*?" + re.escape(ALLOC_END), re.DOTALL
    )
    if len(alloc_pattern.findall(source)) != 1:
        raise SystemExit("marked ESCBANK7_ALLOC_BODIES block is missing or duplicated")
    source = alloc_pattern.sub(alloc_block, source)

    da_task_block = (
        DA_TASK_START
        + "\n    .org $CC00\n"
        + transpile_da_task(0x00DA72, "coroutine")
        + "\n\n"
        + transpile_d8ac_task()
        + "\n\n"
        + transpile_da_task(0x00D9CC, "table", table_suffix=True)
        + "\n\n"
        + transpile_da_task(0x00DC44, "table", table_suffix=True)
        + "\n\n"
        + transpile_da_task(0x00DA44, "table", table_suffix=True)
        + "\n\n"
        + transpile_da9e_table()
        + "\n\n"
        + transpile_da_task(0x00DAF4, "table", table_suffix=True)
        + "\n\n"
        + transpile_da_task(0x00DC2E, "table", table_suffix=True)
        + "\n"
        + DA_TASK_END
    )
    da_task_pattern = re.compile(
        re.escape(DA_TASK_START) + r".*?" + re.escape(DA_TASK_END),
        re.DOTALL,
    )
    if len(da_task_pattern.findall(source)) != 1:
        raise SystemExit("marked ESCBANK7_DA_TASK_BODIES block is missing or duplicated")
    source = da_task_pattern.sub(da_task_block, source)

    entry_init_block = (
        ENTRY_INIT_START
        + "\n    .org $F000\n"
        + transpile_24aa8_init()
        + "\n\n"
        + hand_28f92()
        + "\n\n"
        + transpile_91e_init()
        + "\n\n"
        + transpile_c0bc_init()
        + "\n"
        + ENTRY_INIT_END
    )
    entry_init_pattern = re.compile(
        re.escape(ENTRY_INIT_START) + r".*?" + re.escape(ENTRY_INIT_END),
        re.DOTALL,
    )
    if len(entry_init_pattern.findall(source)) != 1:
        raise SystemExit("marked ESCBANK7_ENTRY_INIT_BODIES block is missing or duplicated")
    SOURCE.write_text(entry_init_pattern.sub(entry_init_block, source), encoding="utf-8")
    print(
        "gen_escbank7_bodies: wrote the 320-byte $20E8 DMA payload, "
        "$02AD4C/$02A86E, $02498C/$0249C2/$01F2E4, $D8AC/$DAxx, "
        "and guarded gameplay-entry initializer bodies"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
