#!/usr/bin/env python3
"""Refresh cross-bank imports for the bank-$9F native region."""

from __future__ import annotations

import re
from pathlib import Path


SOURCE = Path("src/escbank9.pasm")
IMPORTS = (
    (
        Path("src/interp.sym"),
        0x00,
        (
            "inext",
            "push32_l",
            "readbyte_l",
            "rdw_ea_l",
            "writebyte_l",
            "ojmp_hook",
            "ors_pre",
        ),
    ),
    (Path("src/escbank.sym"), 0x92, ("ibridge",)),
    (Path("src/escbank2.sym"), 0x94, ("h135e0_direct",)),
)


def load(path: Path) -> dict[str, int]:
    values: dict[str, int] = {}
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(
            r"\s*[0-9A-Fa-f]{2}:([0-9A-Fa-f]{4})\s+(\S+)", raw
        )
        if match:
            values[match.group(2)] = int(match.group(1), 16)
    return values


def main() -> int:
    if not SOURCE.exists():
        return 0
    resolved: list[tuple[str, int]] = []
    for path, bank, names in IMPORTS:
        if not path.exists():
            raise SystemExit(f"gen_escbank9_syms: missing {path}")
        available = load(path)
        missing = [name for name in names if name not in available]
        if missing:
            raise SystemExit(
                f"gen_escbank9_syms: missing {path} symbols: {missing}"
            )
        resolved.extend(
            (name, (bank << 16) | available[name]) for name in names
        )

    lines = [
        "; >>> ESCBANK9_SYMS — auto-generated by "
        "tools/gen_escbank9_syms.py (do not edit) <<<"
    ]
    lines.extend(f"{name}=${address:06X}" for name, address in resolved)
    lines.append("; <<< ESCBANK9_SYMS <<<")
    source = SOURCE.read_text(encoding="utf-8")
    pattern = re.compile(
        r"; >>> ESCBANK9_SYMS.*?; <<< ESCBANK9_SYMS <<<", re.DOTALL
    )
    if len(pattern.findall(source)) != 1:
        raise SystemExit(
            "gen_escbank9_syms: marked symbol block missing or duplicated"
        )
    SOURCE.write_text(pattern.sub("\n".join(lines), source), encoding="utf-8")
    print(f"gen_escbank9_syms: wrote {len(resolved)} symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
