#!/usr/bin/env python3
"""
Build a SNES "palette proof" ROM + a ground-truth reference image.

Goal: prove, on a real SNES core, that the arcade->SNES palette conversion
displays the SAME colors the arcade hardware shows (i.e. that the xRGB555 ->
xBGR555 channel handling is correct -- the bug this catches is an R<->B swap).

What it does:
  - reads the arcade palette dump (xRGB555, from MAME),
  - takes the first N distinct *used* arcade colors,
  - converts each to a SNES CGRAM word the way the (fixed) pipeline does,
  - lays them out as an 8-palette x 16-color swatch grid,
  - emits build/proof.pasm (code + tiles + tilemap + cgram as .byte data),
  - writes build/proof_reference.png: the SAME colors decoded as the *arcade*
    hardware would show them. The SNES screenshot must match this.

Pixel index 0 of every 4bpp palette is hardware-transparent on a BG, so column 0
of the grid is forced to black in both the ROM and the reference.
"""
import struct
from pathlib import Path

ARCADE_PAL = "tools/mame-trace/arcade_palette.bin"
OUT_PASM = "build/proof.pasm"
OUT_REF = "build/proof_reference.png"
OUT_META = "build/proof_colors.txt"

NPAL = 8          # palette rows
NCOL = 16         # color columns (index 0 = transparent/black)
SW_W = 2          # swatch width in tiles  (16*2 = 32 tiles = full 256px width)
SW_H = 3          # swatch height in tiles (8*3  = 24 tiles = 192px tall)


def arcade_rgb(w):
    """How the Taito X / MAME interprets a palette word: xRRRRRGGGGGBBBBB."""
    return ((w >> 10) & 0x1F, (w >> 5) & 0x1F, w & 0x1F)


def to_snes_word(w):
    """Fixed pipeline conversion: arcade xRGB555 -> SNES xBGR555."""
    r, g, b = arcade_rgb(w)
    return (r | (g << 5) | (b << 10)) & 0x7FFF


def snes_rgb(word):
    """How the SNES PPU reads CGRAM: xBBBBBGGGGGRRRRR."""
    return (word & 0x1F, (word >> 5) & 0x1F, (word >> 10) & 0x1F)


def expand5to8(v):
    return (v << 3) | (v >> 2)


def main():
    data = Path(ARCADE_PAL).read_bytes()
    words = struct.unpack("<%dH" % (len(data) // 2), data)

    # distinct, used (non-zero), in palette order
    seen = set()
    colors = []
    for w in words:
        if w == 0 or w in seen:
            continue
        seen.add(w)
        colors.append(w)
    need = NPAL * (NCOL - 1)            # 8 * 15 = 120 displayable colors
    colors = colors[:need]
    print(f"using {len(colors)} distinct arcade colors")

    # --- CGRAM: 8 palettes x 16 colors (index 0 = black) ---
    cgram = bytearray()
    grid = []                          # grid[pal][col] -> snes word (for reference)
    ci = 0
    for p in range(NPAL):
        row = []
        for c in range(NCOL):
            if c == 0:
                word = 0x0000
            else:
                word = to_snes_word(colors[ci]) if ci < len(colors) else 0
                ci += 1
            row.append(word)
            cgram += struct.pack("<H", word)
        grid.append(row)
    assert len(cgram) == 256

    # --- tiles: 16 solid 4bpp tiles, tile i filled with pixel value i ---
    tiles = bytearray()
    for i in range(16):
        # 4bpp planar SNES: rows 0-7 bp0/bp1 interleaved, then bp2/bp3
        b0 = 0xFF if (i & 1) else 0x00
        b1 = 0xFF if (i & 2) else 0x00
        b2 = 0xFF if (i & 4) else 0x00
        b3 = 0xFF if (i & 8) else 0x00
        for _ in range(8):
            tiles += bytes((b0, b1))
        for _ in range(8):
            tiles += bytes((b2, b3))
    assert len(tiles) == 16 * 32

    # --- tilemap: 32x32 entries ---
    tilemap = bytearray()
    for ty in range(32):
        for tx in range(32):
            if ty < NPAL * SW_H and tx < NCOL * SW_W:
                pal = ty // SW_H
                col = tx // SW_W
                entry = (col & 0x3FF) | (pal << 10)
            else:
                entry = 0
            tilemap += struct.pack("<H", entry)
    assert len(tilemap) == 32 * 32 * 2

    # --- emit proof.pasm ---
    def byte_block(label, blob):
        out = [f"{label}:"]
        for i in range(0, len(blob), 16):
            chunk = ",".join("$%02X" % b for b in blob[i:i + 16])
            out.append(f"    .byte {chunk}")
        return "\n".join(out)

    asm = f"""; AUTO-GENERATED by tools/make_palette_proof.py -- do not edit.
; Palette proof ROM: displays the converted arcade palette as an 8x16 swatch
; grid so a real SNES core (Mesen) can confirm the colors are correct.
.snes

INIDISP  = $2100
VMAIN    = $2115
VMADDL   = $2116
VMADDH   = $2117
VMDATAL  = $2118
VMDATAH  = $2119
CGADD    = $2121
CGDATA   = $2122
BGMODE   = $2105
BG1SC    = $2107
BG12NBA  = $210B
TM       = $212C
NMITIMEN = $4200
MDMAEN   = $420B
DMAP0    = $4300
BBAD0    = $4301
A1T0L    = $4302
A1T0H    = $4303
A1B0     = $4304
DAS0L    = $4305
DAS0H    = $4306

.bank 0
.org $8000
reset:
    clc
    xce
    sei
    rep #$30
    ldx #$1fff
    txs
    sep #$20

    lda #$80
    sta INIDISP            ; forced blank
    stz NMITIMEN

    lda #$01
    sta BGMODE             ; mode 1, BG1 = 4bpp
    lda #$00
    sta BG1SC              ; BG1 tilemap base = VRAM word $0000, 32x32
    lda #$01
    sta BG12NBA            ; BG1 char base = VRAM word $1000
    lda #$80
    sta VMAIN              ; VRAM inc +1 word after high-byte write

    ; --- DMA tiles -> VRAM word $1000 ---
    lda #$00
    sta VMADDL
    lda #$10
    sta VMADDH
    lda #$01               ; 2-reg (L/H) transfer
    sta DMAP0
    lda #$18               ; -> $2118
    sta BBAD0
    lda #<tiles_data
    sta A1T0L
    lda #>tiles_data
    sta A1T0H
    stz A1B0               ; bank $00
    lda #<{len(tiles)}
    sta DAS0L
    lda #>{len(tiles)}
    sta DAS0H
    lda #$01
    sta MDMAEN

    ; --- DMA tilemap -> VRAM word $0000 ---
    stz VMADDL
    stz VMADDH
    lda #$01
    sta DMAP0
    lda #$18
    sta BBAD0
    lda #<map_data
    sta A1T0L
    lda #>map_data
    sta A1T0H
    stz A1B0
    lda #<{len(tilemap)}
    sta DAS0L
    lda #>{len(tilemap)}
    sta DAS0H
    lda #$01
    sta MDMAEN

    ; --- DMA palette -> CGRAM ---
    stz CGADD
    lda #$00               ; 1-reg transfer
    sta DMAP0
    lda #$22               ; -> $2122
    sta BBAD0
    lda #<cgram_data
    sta A1T0L
    lda #>cgram_data
    sta A1T0H
    stz A1B0
    lda #<256
    sta DAS0L
    lda #>256
    sta DAS0H
    lda #$01
    sta MDMAEN

    lda #$01
    sta TM                 ; enable BG1 on main screen
    lda #$0F
    sta INIDISP            ; screen on, full brightness

loop:
    wai
    bra loop

nmi:
    rti
irq:
    rti

{byte_block("tiles_data", tiles)}

{byte_block("map_data", tilemap)}

{byte_block("cgram_data", cgram)}

.org $FFE0
.word $0000
.word $0000
.word irq
.word irq
.word $0000
.word nmi
.word reset
.word irq
.org $FFF0
.word $0000
.word $0000
.word irq
.word $0000
.word $0000
.word nmi
.word reset
.word irq
"""
    Path("build").mkdir(exist_ok=True)
    Path(OUT_PASM).write_text(asm)
    print(f"wrote {OUT_PASM}")

    # --- reference image: the SAME grid, arcade-correct RGB, upscaled ---
    from PIL import Image
    cell = 16                          # px per swatch
    img = Image.new("RGB", (NCOL * cell, NPAL * cell), (0, 0, 0))
    px = img.load()
    meta = []
    for p in range(NPAL):
        for c in range(NCOL):
            word = grid[p][c]
            r, g, b = snes_rgb(word)   # what the PPU will output (== arcade rgb)
            rgb = (expand5to8(r), expand5to8(g), expand5to8(b))
            meta.append(f"pal{p} col{c:2d}  word=${word:04X}  rgb5={r,g,b}")
            for yy in range(cell):
                for xx in range(cell):
                    px[c * cell + xx, p * cell + yy] = rgb
    img.save(OUT_REF)
    Path(OUT_META).write_text("\n".join(meta) + "\n")
    print(f"wrote {OUT_REF} ({img.size}) and {OUT_META}")


if __name__ == "__main__":
    main()
