#!/usr/bin/env python3
"""Record every framebuffer generated by a real-controller input span.

This uses the emulator core's lossless animated-GIF recorder, so slow rendering
or debugger timing cannot skip a transient frame.  The selected ROM and state
are read-only; the only live stimulus is the port-0 controller override.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

from PIL import Image, ImageSequence


ROOT = Path(__file__).resolve().parents[1]
REAL_MESEN = Path("/home/chad/Mesen2/bin/linux-x64/Release/Mesen")
REAL_MESEN_DLL = REAL_MESEN.with_name("Mesen.dll")
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, "/home/chad/Mesen2/python")

import capture_mesen211_transitions as capture  # noqa: E402
from gameplay_acceptance_contract import unknown_diagnostic_gate  # noqa: E402
import mesen_mcp.session as _session  # noqa: E402

_session.validate_mesen_build = lambda *_args, **_kwargs: None
from mesen_mcp import McpSession  # noqa: E402


BUTTONS = {
    "neutral": 0,
    "right": McpSession.BTN_RIGHT,
    "left": McpSession.BTN_LEFT,
    "up": McpSession.BTN_UP,
    "down": McpSession.BTN_DOWN,
    "b": McpSession.BTN_B,
    "b+right": McpSession.BTN_B | McpSession.BTN_RIGHT,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--state", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--emulator", type=Path, required=True)
    parser.add_argument("--port", type=int, default=9270)
    parser.add_argument("--buttons", choices=sorted(BUTTONS), required=True)
    parser.add_argument("--frames", type=int, required=True)
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def configure_dotnet(emulator: Path) -> None:
    selected = (
        "/home/chad/.dotnet10"
        if emulator.name == "Nexen"
        else "/home/chad/.dotnet8"
    )
    other = (
        "/home/chad/.dotnet8"
        if selected.endswith("dotnet10")
        else "/home/chad/.dotnet10"
    )
    os.environ["DOTNET_ROOT"] = selected
    existing = [
        item
        for item in os.environ.get("PATH", "").split(":")
        if item and item not in (selected, other)
    ]
    os.environ["PATH"] = ":".join([selected, other, *existing])


def main() -> int:
    args = parse_args()
    if args.frames <= 0:
        raise SystemExit("--frames must be positive")
    for label, path in (
        ("ROM", args.rom),
        ("state", args.state),
        ("emulator", args.emulator),
    ):
        if not path.is_file():
            raise FileNotFoundError(f"{label} not found: {path}")
    rom = args.rom.resolve()
    if rom.stat().st_size != 0x400000:
        raise SystemExit("expected a 4 MiB production ROM")
    if int.from_bytes(rom.read_bytes()[0x77E0:0x77E2], "little") != 0:
        raise SystemExit("refusing non-production ROM: TESTFLAG is set")

    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    frames_dir = output / "frames"
    frames_dir.mkdir()
    gif_path = output / "framebuffers.gif"
    configure_dotnet(args.emulator)

    with McpSession(
        rom=rom,
        mesen=args.emulator.resolve(),
        cwd=ROOT,
        port=args.port,
        boot_wait=6.0,
        socket_timeout=300.0,
        stderr_log=output / "emulator.stderr.log",
    ) as m:
        m.pause()
        m.load_state(args.state.resolve())
        m.pause()
        start_frame = int(m.get_state().get("frameCount", 0))
        initial = capture.snapshot(m)
        initial_screenshot = capture.take_screenshot(m, output / "initial.png")
        record_response = m.tool("record_video", {"path": str(gif_path)})
        input_response = m.set_input(BUTTONS[args.buttons], args.frames)
        m.pause()
        end_frame = int(m.get_state().get("frameCount", 0))
        stop_response = m.tool("stop_video")
        final = capture.snapshot(m)
        final_screenshot = capture.take_screenshot(m, output / "final.png")
        final_state = capture.save_checkpoint(m, output / "final.mss")

    capture.wait_for_file(gif_path, timeout=60.0)
    extracted: list[dict[str, object]] = []
    with Image.open(gif_path) as animated:
        gif_size = list(animated.size)
        gif_frames = int(getattr(animated, "n_frames", 1))
        for index, frame in enumerate(ImageSequence.Iterator(animated)):
            target = frames_dir / f"frame-{index:06d}.png"
            frame.convert("RGB").save(target)
            extracted.append(
                {
                    "index": index,
                    "path": str(target),
                    "sha256": sha256(target),
                }
            )

    advanced = end_frame - start_frame
    report = {
        "schema": 1,
        "scope": (
            "lossless emulator-core framebuffer recording under real port-0 "
            "controller input; retained same-emulator state; no runtime memory writes"
        ),
        "rom": str(rom),
        "rom_sha256": sha256(rom),
        "state": str(args.state.resolve()),
        "state_sha256": sha256(args.state),
        "emulator": str(args.emulator.resolve()),
        "emulator_sha256": sha256(args.emulator),
        "mesen_2_1_1_binary": str(REAL_MESEN),
        "mesen_2_1_1_binary_sha256": sha256(REAL_MESEN),
        "mesen_2_1_1_managed_assembly": str(REAL_MESEN_DLL),
        "mesen_2_1_1_managed_assembly_sha256": sha256(REAL_MESEN_DLL),
        "buttons": args.buttons,
        "button_mask": BUTTONS[args.buttons],
        "requested_input_frames": args.frames,
        "start_video_frame": start_frame,
        "end_video_frame": end_frame,
        "advanced_video_frames": advanced,
        "runtime_memory_writes": [],
        "record_response": record_response,
        "input_response": input_response,
        "stop_response": stop_response,
        "initial": initial,
        "initial_screenshot": initial_screenshot,
        "final": final,
        "final_screenshot": final_screenshot,
        "final_state": final_state,
        "gif": {
            "path": str(gif_path),
            "sha256": sha256(gif_path),
            "size": gif_size,
            "frames": gif_frames,
        },
        "extracted_frames": extracted,
        "checks": {
            "interpreter_not_halted": int(final["halt"]) == 0,
            "video_frames_advanced": advanced > 0,
            "gif_has_frames": gif_frames > 0,
            "gif_frame_count_does_not_exceed_advanced": gif_frames <= advanced,
        },
        "acceptance_gate": unknown_diagnostic_gate(
            "framebuffer_capture",
            "Capture success is evidence availability, not visual correctness.",
        ),
    }
    report["result"] = (
        "captured" if all(report["checks"].values()) else "red"
    )
    report_path = output / "results.json"
    report_path.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "result": report["result"],
                "advanced_video_frames": advanced,
                "gif_frames": gif_frames,
                "report": str(report_path),
            },
            sort_keys=True,
        )
    )
    return 0 if report["result"] == "captured" else 1


if __name__ == "__main__":
    raise SystemExit(main())
