; >>> ESCBANK3_SYMS — auto-generated by tools/gen_escbank4_syms.py (do not edit) <<<
inext=$00D128
rdw40_l=$00E59E
wrw40_l=$00E5A2
rdb40_l=$00E5A6
wrb40_l=$00E5AA
push32_l=$00E5AE
rdw_ea_l=$00E5B2
readbyte_l=$00E5B6
writeword_l=$00E5BA
writebyte_l=$00E5BE
usmul_l=$00E5C2
op_rts_sentinel=$00EA3A
ojmp_hook=$00D1B3
ors_pre=$00D16F
; <<< ESCBANK3_SYMS <<<

.snes
; escbank4.pasm -- FOURTH SA-1 escape bank ($98:8000, file $2C0000). Hosts the $023xxx trap#5-cluster
; family (7 fns, ~9.5KB -- too big for escbank3's remaining 5.4KB; the family's internal --escapes
; direct links require same-bank placement). Reached from jah2_b2's zero-shift extension jb2_ext
; (bank-$02 jsr.l roots $023342/$0235E0/$023864). CALL-BRIDGE sentinels are $00FB -> ors_pre chain
; -> ors_98chk -> ors_pre_98 resumes bank $98. --video (IO-aware stores/RMW). The leading `.snes`
; is REQUIRED (rep/sep tracking).

; >>> ESCBANK4_SYMS -- auto-generated by tools/gen_escbank4_syms.py (do not edit) <<<
; <<< ESCBANK4_SYMS <<<


    .org $8000
; --- transpiled from $023342 (7 instrs) by tools/transpile.py [bank1] ---
entry_23342:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $18
    sta $54
    lda $1A
    sta $56
    jsl.l push32_l
    lda $14
    sta $54
    lda $16
    sta $56
    jsl.l push32_l
    lda $10
    sta $54
    lda $12
    sta $56
    jsl.l push32_l
    lda $0C
    sta $54
    lda $0E
    sta $56
    jsl.l push32_l
    lda $08
    sta $54
    lda $0A
    sta $56
    jsl.l push32_l
    lda $04
    sta $54
    lda $06
    sta $56
    jsl.l push32_l
    lda $00
    sta $54
    lda $02
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$3554
    tax
    lda $400000,x
    xba
    bne Lf23342_1
    jmp L23342_23354
Lf23342_1:
    ; CALL-BRIDGE jsr $2380c.l -> ojmp_hook (callee --table escape, else interpret), resume br23342_1
    lda #br23342_1
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$380C
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br23342_1:
L23342_23354:
    ; CALL-BRIDGE bsr.w $2335e -> entry_2335e (NATIVE escape), resume br23342_2
    lda #br23342_2
    sta $40
    lda #$00FB
    sta $42
    jmp entry_2335e
br23342_2:
    ldx $3C
    lda $400000,x
    xba
    sta $02
    inx
    inx
    lda $400000,x
    xba
    sta $00
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $06
    inx
    inx
    lda $400000,x
    xba
    sta $04
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0A
    inx
    inx
    lda $400000,x
    xba
    sta $08
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0E
    inx
    inx
    lda $400000,x
    xba
    sta $0C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $12
    inx
    inx
    lda $400000,x
    xba
    sta $10
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $16
    inx
    inx
    lda $400000,x
    xba
    sta $14
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $1A
    inx
    inx
    lda $400000,x
    xba
    sta $18
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $26
    inx
    inx
    lda $400000,x
    xba
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2A
    inx
    inx
    lda $400000,x
    xba
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2E
    inx
    inx
    lda $400000,x
    xba
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

    .org $8400
; --- transpiled from $02335E (124 instrs) by tools/transpile.py [bank1] ---
entry_2335e:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$3524
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda #$0001
    sta $18
L2335e_23366:
    lda $30
    clc
    adc #$000E
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf2335e_1
    jmp L2335e_23536
Lf2335e_1:
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    sep #$20
    sta $04
    rep #$20
    lda $04
    sec
    sbc #$0040
    sta $04
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    asl a
    asl a
    sta $00
    lda $00
    bmi Lf2335e_2
    jmp L2335e_23380
Lf2335e_2:
    lda $00
    eor #$FFFF
    inc a
    sta $00
L2335e_23380:
    lda $04
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $04
    lda $04
    asl a
    asl a
    sta $04
    lda $04
    bmi Lf2335e_3
    jmp L2335e_23388
Lf2335e_3:
    lda $04
    eor #$FFFF
    inc a
    sta $04
L2335e_23388:
    lda #$308E
    sta $20
    lda #$0000
    sta $22
    lda $04
    sta $8C
    and #$8000
    bne Lf2335e_4
    lda #$0000
    bra Lf2335e_5
Lf2335e_4:
    lda #$FFFF
Lf2335e_5:
    sta $8E
    lda $20
    clc
    adc $8C
    sta $54
    sta $8C
    lda $22
    adc $8E
    sta $52
    sta $8E
    jsl.l rdw_ea_l
    sta $9E
    lda $8C
    clc
    adc #$0002
    sta $54
    lda $8E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $04
    lda $9C
    sta $06
    lda $00
    sta $8C
    and #$8000
    bne Lf2335e_6
    lda #$0000
    bra Lf2335e_7
Lf2335e_6:
    lda #$FFFF
Lf2335e_7:
    sta $8E
    lda $20
    clc
    adc $8C
    sta $54
    sta $8C
    lda $22
    adc $8E
    sta $52
    sta $8E
    jsl.l rdw_ea_l
    sta $9E
    lda $8C
    clc
    adc #$0002
    sta $54
    lda $8E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $00
    lda $9C
    sta $02
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    beq Lf2335e_8
    jmp L2335e_233b6
Lf2335e_8:
    lda #$0000
    sta $04
    sta $06
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0001
    sta $80
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda #$2A32
    sta $54
    lda #$00F0
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc $08
    sta $80
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    jmp L2335e_23418
L2335e_233b6:
    lda #$000D
    sta $08
    lda $08
    and #$003F
    tax
Lf2335e_9:
    cpx #$0000
    beq Lf2335e_10
    lsr $06
    ror $04
    dex
    bra Lf2335e_9
Lf2335e_10:
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $04
    clc
    adc $9E
    sta $04
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $00
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bpl Lf2335e_11
    jmp L2335e_233d4
Lf2335e_11:
    lda $00
    sec
    sbc #$0001
    sta $00
    jmp L2335e_233d8
L2335e_233d4:
    lda $00
    clc
    adc #$0001
    sta $00
L2335e_233d8:
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $0C
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf2335e_12
    jmp L2335e_23418
Lf2335e_12:
    bpl Lf2335e_13
    jmp L2335e_23402
Lf2335e_13:
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    clc
    adc #$0001
    sta $80
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $0C
    lda $0C
    sec
    sbc #$00F0
    bvs Lf2335e_14
    bpl Lf2335e_15
    bra Lf2335e_16
Lf2335e_14:
    bmi Lf2335e_15
    bra Lf2335e_16
Lf2335e_15:
    jmp L2335e_2340c
Lf2335e_16:
    jmp L2335e_23414
L2335e_23402:
    lda $08
    sec
    sbc $0C
    sta $08
    lda $08
    sec
    sbc #$00F0
    bvs Lf2335e_17
    bmi Lf2335e_18
    bra Lf2335e_19
Lf2335e_17:
    bpl Lf2335e_18
    bra Lf2335e_19
Lf2335e_18:
    jmp L2335e_23414
Lf2335e_19:
L2335e_2340c:
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $04
    sta $80
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
L2335e_23414:
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc $00
    sta $80
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
L2335e_23418:
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0008
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CAE
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume br2335e_1
    lda #br2335e_1
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br2335e_1:
    lda $3C
    clc
    adc #$000A
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    clc
    adc #$0002
    sep #$20
    sta $80
    rep #$20
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$00FF
    beq Lf2335e_20
    jmp L2335e_2344a
Lf2335e_20:
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writebyte_l
L2335e_2344a:
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0008
    beq Lf2335e_21
    jmp L2335e_234a8
Lf2335e_21:
    lda #$0000
    sta $80
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda #$35B0
    sta $24
    lda #$0002
    sta $26
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0016
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    asl a
    asl a
    asl a
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    asl a
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    clc
    adc #$0001
    sta $80
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0004
    beq Lf2335e_22
    jmp L2335e_23486
Lf2335e_22:
    lda #$0000
    sta $80
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
L2335e_23486:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $28
    lda $9E
    sta $2A
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $80
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0008
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CAE
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume br2335e_2
    lda #br2335e_2
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br2335e_2:
    lda $3C
    clc
    adc #$000A
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
L2335e_234a8:
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    clc
    adc #$0001
    sta $80
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $30
    clc
    adc #$000A
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $30
    clc
    adc #$000C
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $24
    lda $9E
    sta $26
    lda #$0001
    sta $80
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $00
    sta $80
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $00
    clc
    adc #$0010
    sta $00
    lda $00
    sta $80
    lda $24
    clc
    adc #$0004
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $04
    sta $80
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $04
    clc
    adc #$0010
    sta $04
    lda $04
    sta $80
    lda $24
    clc
    adc #$0008
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $30
    clc
    adc #$0000
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $08
    rep #$20
    lda $08
    sta $80
    lda $24
    clc
    adc #$000A
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000D
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    bne Lf2335e_23
    jmp L2335e_23532
Lf2335e_23:
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0040
    bvs Lf2335e_24
    bmi Lf2335e_25
    bra Lf2335e_26
Lf2335e_24:
    bpl Lf2335e_25
    bra Lf2335e_26
Lf2335e_25:
    jmp L2335e_23510
Lf2335e_26:
    lda #$0002
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0001
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $5c5e.l -> ojmp_hook (callee --table escape, else interpret), resume br2335e_3
    lda #br2335e_3
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$5C5E
    sta $40
    lda #$0000
    sta $42
    jml.l ojmp_hook
br2335e_3:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    jmp L2335e_23522
L2335e_23510:
    lda #$0002
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $5c5e.l -> ojmp_hook (callee --table escape, else interpret), resume br2335e_4
    lda #br2335e_4
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$5C5E
    sta $40
    lda #$0000
    sta $42
    jml.l ojmp_hook
br2335e_4:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
L2335e_23522:
    ; CALL-BRIDGE bsr.w $23562 -> ojmp_hook (callee --table escape, else interpret), resume br2335e_5
    lda #br2335e_5
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$3562
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2335e_5:
    lda #$0000
    sta $80
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda #$0000
    sta $80
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    jmp L2335e_23536
L2335e_23532:
    ; CALL-BRIDGE bsr.w $23542 -> ojmp_hook (callee --table escape, else interpret), resume br2335e_6
    lda #br2335e_6
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$3542
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2335e_6:
L2335e_23536:
    lda $30
    clc
    adc #$0018
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf2335e_27
    jmp L2335e_23366
Lf2335e_27:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

    .org $9200
; --- transpiled from $0235E0 (38 instrs) by tools/transpile.py [bank1] ---
entry_235e0:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $18
    sta $54
    lda $1A
    sta $56
    jsl.l push32_l
    lda $14
    sta $54
    lda $16
    sta $56
    jsl.l push32_l
    lda $10
    sta $54
    lda $12
    sta $56
    jsl.l push32_l
    lda $0C
    sta $54
    lda $0E
    sta $56
    jsl.l push32_l
    lda $08
    sta $54
    lda $0A
    sta $56
    jsl.l push32_l
    lda $04
    sta $54
    lda $06
    sta $56
    jsl.l push32_l
    lda $00
    sta $54
    lda $02
    sta $56
    jsl.l push32_l
    lda #$0001
    sta $18
    lda $34
    clc
    adc #$3574
    sta $20
    lda $36
    adc #$0000
    sta $22
L235e0_235ec:
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    beq Lf235e0_1
    bmi Lf235e0_1
    bra Lf235e0_2
Lf235e0_1:
    jmp L235e0_23636
Lf235e0_2:
    lda #$0004
    sta $14
    lda $34
    clc
    adc #$3556
    sta $24
    lda $36
    adc #$0000
    sta $26
L235e0_235fc:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    beq Lf235e0_3
    bmi Lf235e0_3
    bra Lf235e0_4
Lf235e0_3:
    jmp L235e0_2362c
Lf235e0_4:
    lda $20
    clc
    adc #$0002
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $24
    clc
    adc #$0004
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $00
    sec
    sbc $9E
    beq Lf235e0_7
    bvs Lf235e0_5
    bpl Lf235e0_6
    bra Lf235e0_7
Lf235e0_5:
    bmi Lf235e0_6
    bra Lf235e0_7
Lf235e0_6:
    jmp L235e0_23626
Lf235e0_7:
    lda $20
    clc
    adc #$0004
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $00
    sec
    sbc $9E
    bvs Lf235e0_8
    bmi Lf235e0_9
    bra Lf235e0_10
Lf235e0_8:
    bpl Lf235e0_9
    bra Lf235e0_10
Lf235e0_9:
    jmp L235e0_23626
Lf235e0_10:
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l readbyte_l
    ora #$0002
    sta $80
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l writebyte_l
    jmp L235e0_23636
L235e0_23626:
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l readbyte_l
    and #$FFFD
    sta $80
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l writebyte_l
L235e0_2362c:
    lda $24
    clc
    adc #$0006
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $14
    dec a
    sta $14
    cmp #$FFFF
    beq Lf235e0_11
    jmp L235e0_235fc
Lf235e0_11:
L235e0_23636:
    lda $20
    clc
    adc #$0008
    sta $20
    lda $22
    adc #$0000
    sta $22
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf235e0_12
    jmp L235e0_235ec
Lf235e0_12:
    lda $34
    clc
    adc #$3574
    sta $20
    lda $36
    adc #$0000
    sta $22
    lda $34
    clc
    adc #$357C
    sta $24
    lda $36
    adc #$0000
    sta $26
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    beq Lf235e0_13
    bmi Lf235e0_13
    bra Lf235e0_14
Lf235e0_13:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L235e0_23680
Lf235e0_14:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    beq Lf235e0_15
    bmi Lf235e0_15
    bra Lf235e0_16
Lf235e0_15:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L235e0_23680
Lf235e0_16:
    lda $20
    clc
    adc #$0002
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $00
    sec
    sbc $9E
    bvs Lf235e0_17
    bmi Lf235e0_18
    bra Lf235e0_19
Lf235e0_17:
    bpl Lf235e0_18
    bra Lf235e0_19
Lf235e0_18:
    jmp L235e0_23674
Lf235e0_19:
    lda $24
    clc
    adc #$0007
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    and #$FFFB
    sta $80
    lda $24
    clc
    adc #$0007
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l readbyte_l
    ora #$0004
    sta $80
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l writebyte_l
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L235e0_23680
L235e0_23674:
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l readbyte_l
    and #$FFFB
    sta $80
    lda $20
    clc
    adc #$0007
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $24
    clc
    adc #$0007
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    ora #$0004
    sta $80
    lda $24
    clc
    adc #$0007
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
L235e0_23680:
    ldx $3C
    lda $400000,x
    xba
    sta $02
    inx
    inx
    lda $400000,x
    xba
    sta $00
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $06
    inx
    inx
    lda $400000,x
    xba
    sta $04
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0A
    inx
    inx
    lda $400000,x
    xba
    sta $08
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0E
    inx
    inx
    lda $400000,x
    xba
    sta $0C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $12
    inx
    inx
    lda $400000,x
    xba
    sta $10
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $16
    inx
    inx
    lda $400000,x
    xba
    sta $14
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $1A
    inx
    inx
    lda $400000,x
    xba
    sta $18
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $26
    inx
    inx
    lda $400000,x
    xba
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2A
    inx
    inx
    lda $400000,x
    xba
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2E
    inx
    inx
    lda $400000,x
    xba
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

    .org $9800
; --- transpiled from $023864 (97 instrs) by tools/transpile.py [bank1] ---
entry_23864:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $18
    sta $54
    lda $1A
    sta $56
    jsl.l push32_l
    lda $14
    sta $54
    lda $16
    sta $56
    jsl.l push32_l
    lda $10
    sta $54
    lda $12
    sta $56
    jsl.l push32_l
    lda $0C
    sta $54
    lda $0E
    sta $56
    jsl.l push32_l
    lda $08
    sta $54
    lda $0A
    sta $56
    jsl.l push32_l
    lda $04
    sta $54
    lda $06
    sta $56
    jsl.l push32_l
    lda $00
    sta $54
    lda $02
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$2A37
    tax
    lda $400000,x
    and #$00FF
    bne Lf23864_1
    jmp L23864_238a8
Lf23864_1:
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    and #$0001
    bne Lf23864_2
    jmp L23864_23884
Lf23864_2:
    lda $34
    clc
    adc #$2A4D
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0009
    bne Lf23864_3
    jmp L23864_238a8
Lf23864_3:
L23864_23884:
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    and #$0002
    bne Lf23864_4
    jmp L23864_23898
Lf23864_4:
    lda $34
    clc
    adc #$2A59
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0009
    bne Lf23864_5
    jmp L23864_238a8
Lf23864_5:
L23864_23898:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    bne Lf23864_6
    jmp L23864_238f0
Lf23864_6:
    lda $34
    clc
    adc #$3618
    tax
    lda $400000,x
    xba
    bmi Lf23864_7
    jmp L23864_238c6
Lf23864_7:
L23864_238a8:
    lda #$FFFF
    pha
    lda $34
    clc
    adc #$3618
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$3612
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$3614
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$3616
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$361C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$361B
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L23864_239fe
L23864_238c6:
    lda $34
    clc
    adc #$2A34
    tax
    lda $400000,x
    xba
    sta $00
    lda $34
    clc
    adc #$361C
    tax
    lda $400000,x
    xba
    sta $04
    lda $00
    sec
    sbc $04
    sta $00
    lda $00
    sec
    sbc #$00C0
    bvs Lf23864_8
    bmi Lf23864_9
    bra Lf23864_10
Lf23864_8:
    bpl Lf23864_9
    bra Lf23864_10
Lf23864_9:
    jmp L23864_238f6
Lf23864_10:
    lda $34
    clc
    adc #$3618
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$361C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$3612
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$3614
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0001
    pha
    lda $34
    clc
    adc #$361B
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L23864_238f0:
    lda $34
    clc
    adc #$2A34
    tax
    lda $400000,x
    xba
    pha
    lda $34
    clc
    adc #$361C
    tax
    pla
    xba
    sta $400000,x
    xba
L23864_238f6:
    lda $34
    clc
    adc #$3612
    tax
    lda $400000,x
    xba
    clc
    adc #$0001
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3614
    tax
    lda $400000,x
    xba
    clc
    adc #$0001
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3612
    tax
    lda $400000,x
    xba
    sec
    sbc #$04B0
    bvs Lf23864_11
    bmi Lf23864_12
    bra Lf23864_13
Lf23864_11:
    bpl Lf23864_12
    bra Lf23864_13
Lf23864_12:
    jmp L23864_23914
Lf23864_13:
    lda $34
    clc
    adc #$3618
    tax
    lda $400000,x
    xba
    sta $00
    jmp L23864_23920
L23864_23914:
    lda $34
    clc
    adc #$3618
    tax
    lda $400000,x
    xba
    bpl Lf23864_14
    jmp L23864_239fe
Lf23864_14:
    lda $34
    clc
    adc #$3618
    tax
    lda $400000,x
    xba
    sta $00
L23864_23920:
    lda $00
    sec
    sbc #$0003
    bne Lf23864_15
    jmp L23864_239e4
Lf23864_15:
    lda $00
    sec
    sbc #$0002
    bne Lf23864_16
    jmp L23864_239aa
Lf23864_16:
    lda $00
    sec
    sbc #$0001
    bne Lf23864_17
    jmp L23864_23970
Lf23864_17:
    lda $34
    clc
    adc #$361B
    tax
    lda $400000,x
    and #$00FF
    beq Lf23864_18
    jmp L23864_2394e
Lf23864_18:
    lda $34
    clc
    adc #$3612
    tax
    lda $400000,x
    xba
    sec
    sbc #$0708
    bvs Lf23864_19
    bpl Lf23864_20
    bra Lf23864_21
Lf23864_19:
    bmi Lf23864_20
    bra Lf23864_21
Lf23864_20:
    jmp L23864_23970
Lf23864_21:
    jmp L23864_23960
L23864_2394e:
    lda $34
    clc
    adc #$3614
    tax
    lda $400000,x
    xba
    sec
    sbc #$0258
    bvs Lf23864_22
    bmi Lf23864_23
    bra Lf23864_24
Lf23864_22:
    bpl Lf23864_23
    bra Lf23864_24
Lf23864_23:
    jmp L23864_23960
Lf23864_24:
    lda #$0000
    pha
    lda $34
    clc
    adc #$361B
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L23864_23970
L23864_23960:
    lda #$0000
    pha
    lda $34
    clc
    adc #$3618
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3616
    tax
    lda $400000,x
    xba
    bne Lf23864_25
    jmp L23864_239f6
Lf23864_25:
    jmp L23864_239fa
L23864_23970:
    lda $34
    clc
    adc #$361B
    tax
    lda $400000,x
    and #$00FF
    beq Lf23864_26
    jmp L23864_23986
Lf23864_26:
    lda $34
    clc
    adc #$3612
    tax
    lda $400000,x
    xba
    sec
    sbc #$0960
    bvs Lf23864_27
    bpl Lf23864_28
    bra Lf23864_29
Lf23864_27:
    bmi Lf23864_28
    bra Lf23864_29
Lf23864_28:
    jmp L23864_239aa
Lf23864_29:
    jmp L23864_23998
L23864_23986:
    lda $34
    clc
    adc #$3614
    tax
    lda $400000,x
    xba
    sec
    sbc #$0258
    bvs Lf23864_30
    bmi Lf23864_31
    bra Lf23864_32
Lf23864_30:
    bpl Lf23864_31
    bra Lf23864_32
Lf23864_31:
    jmp L23864_23998
Lf23864_32:
    lda #$0000
    pha
    lda $34
    clc
    adc #$361B
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L23864_239aa
L23864_23998:
    lda #$0001
    pha
    lda $34
    clc
    adc #$3618
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3616
    tax
    lda $400000,x
    xba
    bne Lf23864_33
    jmp L23864_239f6
Lf23864_33:
    jmp L23864_239fa
L23864_239aa:
    lda $34
    clc
    adc #$361B
    tax
    lda $400000,x
    and #$00FF
    beq Lf23864_34
    jmp L23864_239c0
Lf23864_34:
    lda $34
    clc
    adc #$3612
    tax
    lda $400000,x
    xba
    sec
    sbc #$0BB8
    bvs Lf23864_35
    bpl Lf23864_36
    bra Lf23864_37
Lf23864_35:
    bmi Lf23864_36
    bra Lf23864_37
Lf23864_36:
    jmp L23864_239e4
Lf23864_37:
    jmp L23864_239d2
L23864_239c0:
    lda $34
    clc
    adc #$3614
    tax
    lda $400000,x
    xba
    sec
    sbc #$0258
    bvs Lf23864_38
    bmi Lf23864_39
    bra Lf23864_40
Lf23864_38:
    bpl Lf23864_39
    bra Lf23864_40
Lf23864_39:
    jmp L23864_239d2
Lf23864_40:
    lda #$0000
    pha
    lda $34
    clc
    adc #$361B
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L23864_239e4
L23864_239d2:
    lda #$0002
    pha
    lda $34
    clc
    adc #$3618
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3616
    tax
    lda $400000,x
    xba
    bne Lf23864_41
    jmp L23864_239f6
Lf23864_41:
    jmp L23864_239fa
L23864_239e4:
    lda #$0003
    pha
    lda $34
    clc
    adc #$3618
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3616
    tax
    lda $400000,x
    xba
    bne Lf23864_42
    jmp L23864_239f6
Lf23864_42:
    jmp L23864_239fa
L23864_239f6:
    ; CALL-BRIDGE bsr.w $23ba4 -> ojmp_hook (callee --table escape, else interpret), resume br23864_1
    lda #br23864_1
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$3BA4
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br23864_1:
L23864_239fa:
    lda $34
    clc
    adc #$3616
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    xba
    sta $400000,x
    xba
L23864_239fe:
    ; CALL-BRIDGE bsr.w $23a0c -> entry_23a0c (NATIVE escape), resume br23864_2
    lda #br23864_2
    sta $40
    lda #$00FB
    sta $42
    jmp entry_23a0c
br23864_2:
    ; CALL-BRIDGE bsr.w $23b52 -> entry_23b52 (NATIVE escape), resume br23864_3
    lda #br23864_3
    sta $40
    lda #$00FB
    sta $42
    jmp entry_23b52
br23864_3:
    ldx $3C
    lda $400000,x
    xba
    sta $02
    inx
    inx
    lda $400000,x
    xba
    sta $00
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $06
    inx
    inx
    lda $400000,x
    xba
    sta $04
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0A
    inx
    inx
    lda $400000,x
    xba
    sta $08
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0E
    inx
    inx
    lda $400000,x
    xba
    sta $0C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $12
    inx
    inx
    lda $400000,x
    xba
    sta $10
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $16
    inx
    inx
    lda $400000,x
    xba
    sta $14
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $1A
    inx
    inx
    lda $400000,x
    xba
    sta $18
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $26
    inx
    inx
    lda $400000,x
    xba
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2A
    inx
    inx
    lda $400000,x
    xba
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2E
    inx
    inx
    lda $400000,x
    xba
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

    .org $A200
; --- transpiled from $023A0C (54 instrs) by tools/transpile.py [bank1] ---
entry_23a0c:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$3592
    sta $24
    lda $36
    adc #$0000
    sta $26
    lda #$0003
    sta $18
L23a0c_23a14:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    bne Lf23a0c_1
    jmp L23a0c_23ad6
Lf23a0c_1:
    lda #$0003
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0010
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    lda $9E
    sta $22
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $56
    jsl.l push32_l
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$1800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$000A
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C8A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume br23a0c_1
    lda #br23a0c_1
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br23a0c_1:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $24
    clc
    adc #$0016
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0018
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $00
    lda $9C
    sta $02
    lda $24
    clc
    adc #$001A
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$001C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $04
    lda $9C
    sta $06
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $08
    lda #$0010
    sta $0C
    lda $0C
    and #$003F
    tax
Lf23a0c_2:
    cpx #$0000
    beq Lf23a0c_3
    asl $08
    rol $0A
    dex
    bra Lf23a0c_2
Lf23a0c_3:
    lda $00
    sec
    sbc $08
    sta $00
    lda $02
    sbc $0A
    sta $02
    lda $24
    clc
    adc #$0004
    tax
    lda $400000,x
    xba
    clc
    adc $00
    php
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0002
    tax
    lda $400000,x
    xba
    plp
    adc $02
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    clc
    adc $04
    php
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0006
    tax
    lda $400000,x
    xba
    plp
    adc $06
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$001E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    beq Lf23a0c_4
    jmp L23a0c_23a98
Lf23a0c_4:
    lda #$0000
    sta $00
    sta $02
    lda #$0000
    sta $04
    sta $06
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    sec
    sbc #$0190
    beq Lf23a0c_7
    bvs Lf23a0c_5
    bpl Lf23a0c_6
    bra Lf23a0c_7
Lf23a0c_5:
    bmi Lf23a0c_6
    bra Lf23a0c_7
Lf23a0c_6:
    jmp L23a0c_23a98
Lf23a0c_7:
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $04
    sec
    sbc #$FFF0
    bvs Lf23a0c_8
    bmi Lf23a0c_9
    bra Lf23a0c_10
Lf23a0c_8:
    bpl Lf23a0c_9
    bra Lf23a0c_10
Lf23a0c_9:
    jmp L23a0c_23a98
Lf23a0c_10:
    lda #$005B
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $2d8a.l -> ojmp_hook (callee --table escape, else interpret), resume br23a0c_2
    lda #br23a0c_2
    sta $54
    lda #$00FB
    sta $56
    jsl.l push32_l
    lda #$2D8A
    sta $40
    lda #$0000
    sta $42
    jml.l ojmp_hook
br23a0c_2:
    lda $3C
    clc
    adc #$0002
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda #$0001
    sta $80
    lda $24
    clc
    adc #$001E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
L23a0c_23a98:
    lda $24
    clc
    adc #$000D
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    beq Lf23a0c_11
    jmp L23a0c_23ace
Lf23a0c_11:
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    clc
    adc #$0001
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$0004
    beq Lf23a0c_12
    jmp L23a0c_23ab4
Lf23a0c_12:
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
L23a0c_23ab4:
    lda #$3E24
    sta $28
    lda #$0002
    sta $2A
    lda $24
    clc
    adc #$000C
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $08
    rep #$20
    lda $08
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $08
    lda $08
    asl a
    asl a
    sta $08
    lda $08
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $28
    clc
    adc $9A
    sta $28
    lda $2A
    adc $9C
    sta $2A
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $28
    clc
    adc #$0002
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9C
    sta $80
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $9A
    sta $80
    lda $24
    clc
    adc #$0010
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda #$0005
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000D
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
L23a0c_23ace:
    lda $24
    clc
    adc #$000D
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$0001
    sep #$20
    sta $80
    rep #$20
    lda $24
    clc
    adc #$000D
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l writebyte_l
    ; CALL-BRIDGE bsr.w $23ae2 -> entry_23ae2 (NATIVE escape), resume br23a0c_3
    lda #br23a0c_3
    sta $40
    lda #$00FB
    sta $42
    jmp entry_23ae2
br23a0c_3:
L23a0c_23ad6:
    lda $24
    clc
    adc #$0020
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf23a0c_13
    jmp L23a0c_23a14
Lf23a0c_13:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

    .org $A900
; --- transpiled from $023AE2 (9 instrs) by tools/transpile.py [bank1] ---
entry_23ae2:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda #$0000
    sta $00
    sta $02
    lda #$0000
    sta $04
    sta $06
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    sec
    sbc #$01A0
    bvs Lf23ae2_1
    bpl Lf23ae2_2
    bra Lf23ae2_3
Lf23ae2_1:
    bmi Lf23ae2_2
    bra Lf23ae2_3
Lf23ae2_2:
    jmp Ltj23ae2_23b00
Lf23ae2_3:
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $04
    sec
    sbc #$0100
    bvs Lf23ae2_4
    bpl Lf23ae2_5
    bra Lf23ae2_6
Lf23ae2_4:
    bmi Lf23ae2_5
    bra Lf23ae2_6
Lf23ae2_5:
    jmp Ltj23ae2_23b00
Lf23ae2_6:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
Ltj23ae2_23b00:
    lda #$3B00
    sta $40
    lda #$0002
    sta $42
    jml.l inext

    .org $AB00
; --- transpiled from $023B52 (20 instrs) by tools/transpile.py [bank1] ---
entry_23b52:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$3592
    sta $24
    lda $36
    adc #$0000
    sta $26
    lda #$0003
    sta $18
L23b52_23b5a:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    bne Lf23b52_1
    jmp L23b52_23b98
Lf23b52_1:
    lda $24
    clc
    adc #$0012
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0014
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $28
    lda $9E
    sta $2A
    lda #$0001
    sta $80
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $00
    clc
    adc #$0008
    sta $00
    lda $04
    clc
    adc #$0008
    sta $04
    lda $00
    sta $80
    lda $28
    clc
    adc #$0002
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $04
    sta $80
    lda $28
    clc
    adc #$0006
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $00
    clc
    adc #$0010
    sta $00
    lda $04
    clc
    adc #$0010
    sta $04
    lda $00
    sta $80
    lda $28
    clc
    adc #$0004
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda $04
    sta $80
    lda $28
    clc
    adc #$0008
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
    lda #$0000
    sta $80
    lda $28
    clc
    adc #$000E
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l writeword_l
L23b52_23b98:
    lda $24
    clc
    adc #$0020
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf23b52_2
    jmp L23b52_23b5a
Lf23b52_2:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
