; escbank5.pasm -- FIFTH SA-1 escape bank ($99:8000, file $2C8000). Hosts the $023-25xxx
; trap#5-cluster SHELL segments (CP1 item 2.3): the two coroutine yield-loop bodies
; (entry_24bc2 / entry_2429c, resume PCs dispatched via bank-$02 xlat pages) plus their
; still-interpreted callees. Cross-bank --escapes targets (escbank4 $98 family roots +
; escbank3 $97 entry_25110) are jml.l via gen_escbank5_syms.py imports; CALL-BRIDGE
; sentinels are $00FA -> ors_pre chain -> ors_99chk -> ors_pre_99 resumes bank $99.
; The leading `.snes` is REQUIRED (rep/sep tracking).

; >>> ESCBANK5_SYMS — auto-generated by tools/gen_escbank5_syms.py (do not edit) <<<
inext=$00D128
rdw40_l=$00E59E
wrw40_l=$00E5A2
rdb40_l=$00E5A6
wrb40_l=$00E5AA
push32_l=$00E5AE
rdw_ea_l=$00E5B2
readbyte_l=$00E5B6
writeword_l=$00E5BA
writebyte_l=$00E5BE
usmul_l=$00E5C2
op_rts_sentinel=$00EA3A
ojmp_hook=$00D1B3
ors_pre=$00D16F
entry_23342=$988000
entry_235e0=$989200
entry_23864=$989800
entry_25110=$978000
; <<< ESCBANK5_SYMS <<<

.snes

    .org $8000
; --- entry_24bc2 — trap#5 SHELL 1 (--coroutine): resume $024BC2, yield $024BC0; jsr $23864.l/$28ddc.l + bsr $24d98 static-linked ---
; --- transpiled from $024BC2 (99 instrs) by tools/transpile.py [bank1] ---
entry_24bc2:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $34
    clc
    adc #$1CCE
    tax
    lda $400000,x
    xba
    bne Lf24bc2_1
    jmp L24bc2_24bda
Lf24bc2_1:
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0000
    beq Lf24bc2_2
    jmp L24bc2_24bda
Lf24bc2_2:
    ; CALL-BRIDGE jsr $23864.l -> entry_23864 (NATIVE escape), resume br24bc2_1
    lda #br24bc2_1
    sta $40
    lda #$00FA
    sta $42
    jml.l entry_23864
br24bc2_1:
L24bc2_24bda:
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    ; CALL-BRIDGE jsr $28ddc.l -> entry_28ddc (NATIVE escape), resume br24bc2_2
    lda #br24bc2_2
    sta $40
    lda #$00FA
    sta $42
    jmp entry_28ddc
br24bc2_2:
    ldx $3C
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    bne Lf24bc2_3
    jmp L24bc2_24c28
Lf24bc2_3:
    lda $34
    clc
    adc #$2938
    tax
    lda $400000,x
    xba
    bne Lf24bc2_4
    jmp Ltj24bc2_24bc0
Lf24bc2_4:
    lda $34
    clc
    adc #$3732
    tax
    lda $400000,x
    xba
    beq Lf24bc2_5
    jmp L24bc2_24c28
Lf24bc2_5:
    lda $34
    clc
    adc #$2A37
    tax
    lda $400000,x
    and #$00FF
    beq Lf24bc2_6
    jmp L24bc2_24c10
Lf24bc2_6:
    lda $34
    clc
    adc #$3522
    tax
    lda $400000,x
    and #$00FF
    bne Lf24bc2_7
    jmp L24bc2_24c1e
Lf24bc2_7:
L24bc2_24c10:
    ; CALL-BRIDGE bsr.w $24d98 -> entry_24d98 (NATIVE escape), resume br24bc2_3
    lda #br24bc2_3
    sta $40
    lda #$00FA
    sta $42
    jmp entry_24d98
br24bc2_3:
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    bne Lf24bc2_8
    jmp L24bc2_24c28
Lf24bc2_8:
L24bc2_24c1e:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $00
    lda $00
    bne Lf24bc2_9
    jmp Ltj24bc2_24eb2
Lf24bc2_9:
L24bc2_24c28:
    lda #$0000
    pha
    lda $34
    clc
    adc #$3732
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3700
    tax
    lda $400000,x
    and #$00FF
    bne Lf24bc2_10
    jmp L24bc2_24cb6
Lf24bc2_10:
    lda $34
    clc
    adc #$36F6
    tax
    lda $400000,x
    xba
    sta $04
    lda $34
    clc
    adc #$36F8
    tax
    lda $400000,x
    xba
    sta $08
    lda $04
    clc
    adc $08
    sta $04
    lda $04
    sec
    sbc #$FFF0
    beq Lf24bc2_13
    bvs Lf24bc2_11
    bpl Lf24bc2_12
    bra Lf24bc2_13
Lf24bc2_11:
    bmi Lf24bc2_12
    bra Lf24bc2_13
Lf24bc2_12:
    jmp L24bc2_24c62
Lf24bc2_13:
    lda #$0000
    pha
    lda $34
    clc
    adc #$3700
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0027
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0088
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C9A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
Lf24bc2_14:
Lf24bc2_15:
Lf24bc2_16:
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br24bc2_4
    lda #br24bc2_4
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br24bc2_4:
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    jmp L24bc2_24cb6
L24bc2_24c62:
    lda #$4F52
    sta $24
    lda #$0002
    sta $26
    lda $00
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda #$0000
    sta $00
    sta $02
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $34
    clc
    adc #$36F4
    tax
    lda $400000,x
    xba
    sta $04
    lda $00
    clc
    adc $04
    sta $00
    lda $00
    sta $08
    lda $00
    and #$FF00
    sta $00
    lda $00
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    sta $00
    lda $08
    and #$00FF
    sta $08
    lda $08
    pha
    lda $34
    clc
    adc #$36F4
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$36F6
    tax
    lda $400000,x
    xba
    sec
    sbc $00
    xba
    sta $400000,x
    xba
    lda #$0027
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$36FA
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$36F6
    tax
    lda $400000,x
    xba
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$36FE
    tax
    lda $400000,x
    xba
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0088
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C92
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
Lf24bc2_17:
Lf24bc2_18:
Lf24bc2_19:
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br24bc2_5
    lda #br24bc2_5
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br24bc2_5:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $34
    clc
    adc #$3701
    tax
    lda $400000,x
    and #$00FF
    beq Lf24bc2_20
    jmp Ltj24bc2_24eb2
Lf24bc2_20:
L24bc2_24cb6:
    lda $34
    clc
    adc #$2A34
    tax
    lda $400000,x
    xba
    sta $00
    lda $30
    clc
    adc #$0000
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $04
    beq Lf24bc2_21
    jmp L24bc2_24ccc
Lf24bc2_21:
    lda #$0001
    pha
    lda $34
    clc
    adc #$3701
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$4EB2
    sta $40
    lda #$0002
    sta $42
    jml.l inext
L24bc2_24ccc:
    lda $04
    sec
    sbc $00
    beq Lf24bc2_24
    bvs Lf24bc2_22
    bpl Lf24bc2_23
    bra Lf24bc2_24
Lf24bc2_22:
    bmi Lf24bc2_23
    bra Lf24bc2_24
Lf24bc2_23:
    jmp Ltj24bc2_24eb2
Lf24bc2_24:
    lda $00
    sta $08
    lda $08
    sec
    sbc $04
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda #$0010
    sta $9A
    lda #$0000
    sta $9C
    lda $9A
    sta $0C
    lda $9C
    sta $0E
    lda $0C
    and #$003F
    tax
Lf24bc2_25:
    cpx #$0000
    beq Lf24bc2_26
    asl $08
    rol $0A
    dex
    bra Lf24bc2_25
Lf24bc2_26:
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    bne Lf24bc2_27
    jmp Ltj24bc2_24e1a
Lf24bc2_27:
    bpl Lf24bc2_28
    jmp Ltj24bc2_24d28
Lf24bc2_28:
    lda #$6780
    sta $24
    lda #$0004
    sta $26
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $02
    lda $00
    asl a
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $28
    lda $9E
    sta $2A
    lda #$0000
    sta $04
    sta $06
    lda $30
    clc
    adc #$0003
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $04
    rep #$20
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a
    sta $00
    lda $04
    ora $00
    sta $04
    lda $04
    ora $08
    sta $04
    lda $04
    sta $9A
    lda $06
    sta $9C
    lda $3C
    sec
    sbc #$0004
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $9C
    pha
    lda $3C
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $9A
    pha
    lda $3C
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0010
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $56
    jsl.l push32_l
    lda #$4D1A
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24bc2_24bc0:
    lda #$4BC0
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24bc2_24d28:
    lda #$4D28
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24bc2_24e1a:
    lda #$4E1A
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24bc2_24eb2:
    lda #$4EB2
    sta $40
    lda #$0002
    sta $42
    jml.l inext

; --- entry_2429c — trap#5 SHELL 2 (--coroutine): resume $02429C, yield $02429A; 5 jsr.l static-linked (23342/23e34/235e0/25110/259ca) + the $365e a4-scan ---
; --- transpiled from $02429C (78 instrs) by tools/transpile.py [bank1] ---
entry_2429c:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $34
    clc
    adc #$2930
    tax
    lda $400000,x
    xba
    sec
    sbc #$0008
    bne Lf2429c_1
    jmp L2429c_242b2
Lf2429c_1:
    ; CALL-BRIDGE jsr $23342.l -> entry_23342 (NATIVE escape), resume br2429c_1
    lda #br2429c_1
    sta $40
    lda #$00FA
    sta $42
    jml.l entry_23342
br2429c_1:
    ; CALL-BRIDGE jsr $23e34.l -> entry_23e34 (NATIVE escape), resume br2429c_2
    lda #br2429c_2
    sta $40
    lda #$00FA
    sta $42
    jmp entry_23e34
br2429c_2:
L2429c_242b2:
    ; CALL-BRIDGE jsr $235e0.l -> entry_235e0 (NATIVE escape), resume br2429c_3
    lda #br2429c_3
    sta $40
    lda #$00FA
    sta $42
    jml.l entry_235e0
br2429c_3:
    ; CALL-BRIDGE jsr $25110.l -> entry_25110 (NATIVE escape), resume br2429c_4
    lda #br2429c_4
    sta $40
    lda #$00FA
    sta $42
    jml.l entry_25110
br2429c_4:
    ; CALL-BRIDGE jsr $259ca.l -> entry_259ca (NATIVE escape), resume br2429c_5
    lda #br2429c_5
    sta $40
    lda #$00FA
    sta $42
    jmp entry_259ca
br2429c_5:
    lda $34
    clc
    adc #$3CB4
    tax
    lda $400000,x
    xba
    bne Lf2429c_2
    jmp L2429c_242d4
Lf2429c_2:
    lda #$0000
    pha
    lda $34
    clc
    adc #$3CB4
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L2429c_242da
L2429c_242d4:
    lda #$0001
    pha
    lda $34
    clc
    adc #$3CB4
    tax
    pla
    xba
    sta $400000,x
    xba
L2429c_242da:
    lda $34
    clc
    adc #$365E
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda #$0004
    sta $00
L2429c_242e2:
    lda $30
    clc
    adc #$0019
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf2429c_3
    jmp L2429c_243da
Lf2429c_3:
    lda $30
    clc
    adc #$0016
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf2429c_4
    jmp L2429c_24324
Lf2429c_4:
    lda $30
    clc
    adc #$0016
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0001
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $18
    lda $18
    sec
    sbc #$FF00
    beq Lf2429c_7
    bvs Lf2429c_5
    bpl Lf2429c_6
    bra Lf2429c_7
Lf2429c_5:
    bmi Lf2429c_6
    bra Lf2429c_7
Lf2429c_6:
    jmp L2429c_2430a
Lf2429c_7:
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_6
    lda #br2429c_6
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2429c_6:
    jmp L2429c_243da
L2429c_2430a:
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    bne Lf2429c_8
    jmp L2429c_243da
Lf2429c_8:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $0C
    lda $30
    clc
    adc #$000A
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0010
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    xba
    sta $400000,x
    xba
    jmp L2429c_243da
L2429c_24324:
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $18
    lda $18
    sec
    sbc #$FF00
    beq Lf2429c_11
    bvs Lf2429c_9
    bpl Lf2429c_10
    bra Lf2429c_11
Lf2429c_9:
    bmi Lf2429c_10
    bra Lf2429c_11
Lf2429c_10:
    jmp L2429c_24338
Lf2429c_11:
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_7
    lda #br2429c_7
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2429c_7:
    jmp L2429c_243da
L2429c_24338:
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    bne Lf2429c_12
    jmp L2429c_2434e
Lf2429c_12:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $0C
    lda $30
    clc
    adc #$0010
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$000A
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    xba
    sta $400000,x
    xba
L2429c_2434e:
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0000
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $24
    lda $9E
    sta $26
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    lda $9E
    sta $22
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $56
    jsl.l push32_l
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$000E
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$1800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C8A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
Lf2429c_13:
Lf2429c_14:
Lf2429c_15:
Lf2429c_16:
Lf2429c_17:
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br2429c_8
    lda #br2429c_8
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br2429c_8:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    ; CALL-BRIDGE bsr.w $2443a -> ojmp_hook (callee --table escape, else interpret), resume br2429c_9
    lda #br2429c_9
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$443A
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2429c_9:
    lda $30
    clc
    adc #$0019
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$0002
    bne Lf2429c_18
    jmp L2429c_24392
Lf2429c_18:
    lda $30
    clc
    adc #$0018
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$0002
    beq Lf2429c_19
    jmp L2429c_24392
Lf2429c_19:
    lda #$0002
    pha
    lda $30
    clc
    adc #$0019
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L2429c_24392:
    lda $30
    clc
    adc #$0017
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0001
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0017
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    beq Lf2429c_20
    jmp L2429c_243da
Lf2429c_20:
    lda #$451A
    sta $28
    lda #$0002
    sta $2A
    lda $30
    clc
    adc #$0018
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $04
    rep #$20
    lda $04
    sec
    sbc #$0005
    beq Lf2429c_21
    jmp L2429c_243b8
Lf2429c_21:
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_10
    lda #br2429c_10
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2429c_10:
    jmp L2429c_243da
L2429c_243b8:
    lda $04
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $04
    lda $04
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $28
    clc
    adc $9A
    sta $28
    lda $2A
    adc $9C
    sta $2A
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l readbyte_l
    pha
    lda $30
    clc
    adc #$0017
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0018
    tax
    lda $400000,x
    and #$00FF
    clc
    adc #$0001
    sep #$20
    sta $400000,x
    rep #$20
    lda $24
    clc
    adc #$0004
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $24
    sta $9A
    lda $26
    sta $9C
    lda $9C
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $9A
    pha
    lda $30
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CCC
    tax
    lda $400000,x
    xba
    sec
    sbc #$0008
    bne Lf2429c_22
    jmp L2429c_243da
Lf2429c_22:
    ; CALL-BRIDGE bsr.w $244d4 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_11
    lda #br2429c_11
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$44D4
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br2429c_11:
L2429c_243da:
    lda $30
    clc
    adc #$001E
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $00
    dec a
    sta $00
    cmp #$FFFF
    beq Lf2429c_23
    jmp L2429c_242e2
Lf2429c_23:
    lda #$429A
    sta $40
    lda #$0002
    sta $42
    jml.l inext

; --- entry_23e34 — jsr.l callee wrapper; bsr $23e42 static-linked same-bank ---
; --- transpiled from $023E34 (4 instrs) by tools/transpile.py [bank1] ---
entry_23e34:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $18
    sta $54
    lda $1A
    sta $56
    jsl.l push32_l
    lda $14
    sta $54
    lda $16
    sta $56
    jsl.l push32_l
    lda $10
    sta $54
    lda $12
    sta $56
    jsl.l push32_l
    lda $0C
    sta $54
    lda $0E
    sta $56
    jsl.l push32_l
    lda $08
    sta $54
    lda $0A
    sta $56
    jsl.l push32_l
    lda $04
    sta $54
    lda $06
    sta $56
    jsl.l push32_l
    lda $00
    sta $54
    lda $02
    sta $56
    jsl.l push32_l
    ; CALL-BRIDGE bsr.w $23e42 -> entry_23e42 (NATIVE escape), resume br23e34_1
    lda #br23e34_1
    sta $40
    lda #$00FA
    sta $42
    jmp entry_23e42
br23e34_1:
    ldx $3C
    lda $400000,x
    xba
    sta $02
    inx
    inx
    lda $400000,x
    xba
    sta $00
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $06
    inx
    inx
    lda $400000,x
    xba
    sta $04
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0A
    inx
    inx
    lda $400000,x
    xba
    sta $08
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $0E
    inx
    inx
    lda $400000,x
    xba
    sta $0C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $12
    inx
    inx
    lda $400000,x
    xba
    sta $10
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $16
    inx
    inx
    lda $400000,x
    xba
    sta $14
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $1A
    inx
    inx
    lda $400000,x
    xba
    sta $18
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $26
    inx
    inx
    lda $400000,x
    xba
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2A
    inx
    inx
    lda $400000,x
    xba
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $2E
    inx
    inx
    lda $400000,x
    xba
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- entry_23e42 — 23e34 worker (inner loop); 6 cold call-bridges ---
; --- transpiled from $023E42 (124 instrs) by tools/transpile.py [bank1] ---
entry_23e42:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$361E
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda #$0001
    sta $18
L23e42_23e4a:
    lda $30
    clc
    adc #$000E
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf23e42_1
    jmp L23e42_2401a
Lf23e42_1:
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    sep #$20
    sta $04
    rep #$20
    lda $04
    sec
    sbc #$0040
    sta $04
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    asl a
    asl a
    sta $00
    lda $00
    bmi Lf23e42_2
    jmp L23e42_23e64
Lf23e42_2:
    lda $00
    eor #$FFFF
    inc a
    sta $00
L23e42_23e64:
    lda $04
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $04
    lda $04
    asl a
    asl a
    sta $04
    lda $04
    bmi Lf23e42_3
    jmp L23e42_23e6c
Lf23e42_3:
    lda $04
    eor #$FFFF
    inc a
    sta $04
L23e42_23e6c:
    lda #$308E
    sta $20
    lda #$0000
    sta $22
    lda $04
    sta $8C
    and #$8000
    bne Lf23e42_4
    lda #$0000
    bra Lf23e42_5
Lf23e42_4:
    lda #$FFFF
Lf23e42_5:
    sta $8E
    lda $20
    clc
    adc $8C
    sta $54
    sta $8C
    lda $22
    adc $8E
    sta $52
    sta $8E
    jsl.l rdw_ea_l
    sta $9E
    lda $8C
    clc
    adc #$0002
    sta $54
    lda $8E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $04
    lda $9C
    sta $06
    lda $00
    sta $8C
    and #$8000
    bne Lf23e42_6
    lda #$0000
    bra Lf23e42_7
Lf23e42_6:
    lda #$FFFF
Lf23e42_7:
    sta $8E
    lda $20
    clc
    adc $8C
    sta $54
    sta $8C
    lda $22
    adc $8E
    sta $52
    sta $8E
    jsl.l rdw_ea_l
    sta $9E
    lda $8C
    clc
    adc #$0002
    sta $54
    lda $8E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9A
    sta $00
    lda $9C
    sta $02
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    beq Lf23e42_8
    jmp L23e42_23e9a
Lf23e42_8:
    lda #$0000
    sta $04
    sta $06
    lda $30
    clc
    adc #$0006
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda #$2A32
    sta $54
    lda #$00F0
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $30
    clc
    adc #$0004
    tax
    lda $400000,x
    xba
    sec
    sbc $08
    xba
    sta $400000,x
    xba
    jmp L23e42_23efc
L23e42_23e9a:
    lda #$000D
    sta $08
    lda $08
    and #$003F
    tax
Lf23e42_9:
    cpx #$0000
    beq Lf23e42_10
    lsr $06
    ror $04
    dex
    bra Lf23e42_9
Lf23e42_10:
    lda $30
    clc
    adc #$0006
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $04
    clc
    adc $9E
    sta $04
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $00
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bpl Lf23e42_11
    jmp L23e42_23eb8
Lf23e42_11:
    lda $00
    sec
    sbc #$0001
    sta $00
    jmp L23e42_23ebc
L23e42_23eb8:
    lda $00
    clc
    adc #$0001
    sta $00
L23e42_23ebc:
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $0C
    lda $30
    clc
    adc #$000F
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf23e42_12
    jmp L23e42_23efc
Lf23e42_12:
    bpl Lf23e42_13
    jmp L23e42_23ee6
Lf23e42_13:
    lda $30
    clc
    adc #$0010
    tax
    lda $400000,x
    xba
    clc
    adc #$0001
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $0C
    lda $0C
    sec
    sbc #$00F0
    bvs Lf23e42_14
    bpl Lf23e42_15
    bra Lf23e42_16
Lf23e42_14:
    bmi Lf23e42_15
    bra Lf23e42_16
Lf23e42_15:
    jmp L23e42_23ef0
Lf23e42_16:
    jmp L23e42_23ef8
L23e42_23ee6:
    lda $08
    sec
    sbc $0C
    sta $08
    lda $08
    sec
    sbc #$00F0
    bvs Lf23e42_17
    bmi Lf23e42_18
    bra Lf23e42_19
Lf23e42_17:
    bpl Lf23e42_18
    bra Lf23e42_19
Lf23e42_18:
    jmp L23e42_23ef8
Lf23e42_19:
L23e42_23ef0:
    lda #$0000
    pha
    lda $30
    clc
    adc #$000F
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $04
    pha
    lda $30
    clc
    adc #$0006
    tax
    pla
    xba
    sta $400000,x
    xba
L23e42_23ef8:
    lda $30
    clc
    adc #$0004
    tax
    lda $400000,x
    xba
    sec
    sbc $00
    xba
    sta $400000,x
    xba
L23e42_23efc:
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0008
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CAE
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br23e42_1
    lda #br23e42_1
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br23e42_1:
    lda $3C
    clc
    adc #$000A
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $30
    clc
    adc #$0001
    tax
    lda $400000,x
    and #$00FF
    clc
    adc #$0002
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0001
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$00FF
    beq Lf23e42_20
    jmp L23e42_23f2e
Lf23e42_20:
    lda #$0000
    pha
    lda $30
    clc
    adc #$0001
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L23e42_23f2e:
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0008
    beq Lf23e42_21
    jmp L23e42_23f8c
Lf23e42_21:
    lda #$0000
    pha
    lda $30
    clc
    adc #$0014
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$424C
    sta $24
    lda #$0002
    sta $26
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0016
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    asl a
    asl a
    asl a
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda #$0000
    sta $00
    sta $02
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $00
    asl a
    asl a
    sta $00
    lda $24
    clc
    adc $00
    sta $24
    lda $26
    adc $02
    sta $26
    lda $30
    clc
    adc #$0012
    tax
    lda $400000,x
    xba
    clc
    adc #$0001
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0004
    beq Lf23e42_22
    jmp L23e42_23f6a
Lf23e42_22:
    lda #$0000
    pha
    lda $30
    clc
    adc #$0012
    tax
    pla
    xba
    sta $400000,x
    xba
L23e42_23f6a:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $28
    lda $9E
    sta $2A
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $30
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0008
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CAE
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br23e42_2
    lda #br23e42_2
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br23e42_2:
    lda $3C
    clc
    adc #$000A
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
L23e42_23f8c:
    lda $30
    clc
    adc #$0014
    tax
    lda $400000,x
    xba
    clc
    adc #$0001
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0004
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $30
    clc
    adc #$000A
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $30
    clc
    adc #$000C
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $24
    lda $9E
    sta $26
    lda #$0001
    pha
    lda $24
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $00
    pha
    lda $24
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $00
    clc
    adc #$0010
    sta $00
    lda $00
    pha
    lda $24
    clc
    adc #$0004
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $24
    clc
    adc #$0006
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $04
    clc
    adc #$0010
    sta $04
    lda $04
    pha
    lda $24
    clc
    adc #$0008
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0000
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $08
    rep #$20
    lda $08
    pha
    lda $24
    clc
    adc #$000A
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $24
    clc
    adc #$000C
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0000
    pha
    lda $24
    clc
    adc #$000D
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    bne Lf23e42_23
    jmp L23e42_24016
Lf23e42_23:
    lda $24
    clc
    adc #$000E
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$0040
    bvs Lf23e42_24
    bmi Lf23e42_25
    bra Lf23e42_26
Lf23e42_24:
    bpl Lf23e42_25
    bra Lf23e42_26
Lf23e42_25:
    jmp L23e42_23ff4
Lf23e42_26:
    lda #$0002
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0001
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $5c5e.l -> ojmp_hook (callee --table escape, else interpret), resume br23e42_3
    lda #br23e42_3
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$5C5E
    sta $40
    lda #$0000
    sta $42
    jml.l ojmp_hook
br23e42_3:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    jmp L23e42_24006
L23e42_23ff4:
    lda #$0002
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $5c5e.l -> ojmp_hook (callee --table escape, else interpret), resume br23e42_4
    lda #br23e42_4
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$5C5E
    sta $40
    lda #$0000
    sta $42
    jml.l ojmp_hook
br23e42_4:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
L23e42_24006:
    ; CALL-BRIDGE bsr.w $24046 -> ojmp_hook (callee --table escape, else interpret), resume br23e42_5
    lda #br23e42_5
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$4046
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br23e42_5:
    lda #$0000
    pha
    lda $24
    clc
    adc #$000E
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $24
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L23e42_2401a
L23e42_24016:
    ; CALL-BRIDGE bsr.w $24026 -> ojmp_hook (callee --table escape, else interpret), resume br23e42_6
    lda #br23e42_6
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$4026
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br23e42_6:
L23e42_2401a:
    lda $30
    clc
    adc #$0018
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf23e42_27
    jmp L23e42_23e4a
Lf23e42_27:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre
=== all 124 instrs transpiled ===

; --- entry_259ca — $0259CA scan sub (×4 loop); cold jsr(a0)/bsr $25a22 bridges ---
; --- transpiled from $0259CA (21 instrs) by tools/transpile.py [bank1] ---
entry_259ca:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$3CB6
    sta $24
    lda $36
    adc #$0000
    sta $26
    lda #$0003
    sta $18
L259ca_259d2:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    bne Lf259ca_1
    jmp L259ca_25a16
Lf259ca_1:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $00
    lda $24
    clc
    adc #$0002
    tax
    lda $400000,x
    xba
    sec
    sbc $00
    xba
    sta $400000,x
    xba
    lda #$05F6
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0004
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$1800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CAE
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FA sentinel, resume br259ca_1
    lda #br259ca_1
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
br259ca_1:
    lda $3C
    clc
    adc #$000A
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $24
    clc
    adc #$0001
    tax
    lda $400000,x
    and #$00FF
    clc
    adc #$0001
    sep #$20
    sta $400000,x
    rep #$20
    lda $24
    clc
    adc #$0001
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sec
    sbc #$0003
    beq Lf259ca_2
    jmp L259ca_25a16
Lf259ca_2:
    ; CALL-BRIDGE bsr.w $25a22 -> ojmp_hook (callee --table escape, else interpret), resume br259ca_2
    lda #br259ca_2
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda #$5A22
    sta $40
    lda #$0002
    sta $42
    jml.l ojmp_hook
br259ca_2:
L259ca_25a16:
    lda $24
    clc
    adc #$0008
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $18
    dec a
    sta $18
    cmp #$FFFF
    beq Lf259ca_3
    jmp L259ca_259d2
Lf259ca_3:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- entry_28ddc — $028DDC helper (movem-wrapped from shell 1) ---
; --- transpiled from $028DDC (64 instrs) by tools/transpile.py [bank1] ---
entry_28ddc:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $34
    clc
    adc #$2930
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    beq Lf28ddc_1
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    lda $50
    and #$0040
    sta $72
    lda $50
    and #$0001
    eor #$0001
    sta $6E
    sta $A2
    jmp L28ddc_28ed2
Lf28ddc_1:
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    beq Lf28ddc_2
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    lda $50
    and #$0040
    sta $72
    lda $50
    and #$0001
    eor #$0001
    sta $6E
    sta $A2
    jmp L28ddc_28ed2
Lf28ddc_2:
    lda $34
    clc
    adc #$3EB8
    tax
    lda $400000,x
    xba
    bne Lf28ddc_3
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L28ddc_28ed2
Lf28ddc_3:
    lda $34
    clc
    adc #$3EBC
    tax
    lda $400000,x
    xba
    sta $9C
    inx
    inx
    lda $400000,x
    xba
    sta $9A
    lda $9C
    bne Lf28ddc_4
    lda $9A
    beq Lf28ddc_5
Lf28ddc_4:
    jmp L28ddc_28e0a
Lf28ddc_5:
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A53
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A5F
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L28ddc_28ed2
L28ddc_28e0a:
    lda #$0001
    pha
    lda $34
    clc
    adc #$2A53
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0001
    pha
    lda $34
    clc
    adc #$2A5F
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $34
    clc
    adc #$3EBC
    tax
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda #$FFFF
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $30
    clc
    adc #$000E
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3EB8
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    bne Lf28ddc_6
    jmp L28ddc_28e94
Lf28ddc_6:
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $00
    lda $34
    clc
    adc #$3EBA
    tax
    lda $400000,x
    xba
    sec
    sbc $00
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3EBA
    tax
    lda $400000,x
    xba
    sta $00
    lda $00
    sta $04
    lda $34
    clc
    adc #$3EB8
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    beq Lf28ddc_7
    jmp L28ddc_28e52
Lf28ddc_7:
    lda $04
    clc
    adc #$0060
    sta $04
    lda $00
    sec
    sbc #$FFB8
    beq Lf28ddc_10
    bvs Lf28ddc_8
    bpl Lf28ddc_9
    bra Lf28ddc_10
Lf28ddc_8:
    bmi Lf28ddc_9
    bra Lf28ddc_10
Lf28ddc_9:
    jmp L28ddc_28e5c
Lf28ddc_10:
    lda #$0001
    pha
    lda $34
    clc
    adc #$3EB8
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L28ddc_28e94
L28ddc_28e52:
    lda $00
    sec
    sbc #$0018
    bvs Lf28ddc_11
    bmi Lf28ddc_12
    bra Lf28ddc_13
Lf28ddc_11:
    bpl Lf28ddc_12
    bra Lf28ddc_13
Lf28ddc_12:
    jmp L28ddc_28ec0
Lf28ddc_13:
    lda $04
    clc
    adc #$0180
    sta $04
L28ddc_28e5c:
    lda $00
    clc
    adc #$0008
    sta $00
    lda $04
    clc
    adc #$000C
    sta $04
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    and #$0001
    bne Lf28ddc_14
    jmp L28ddc_28e78
Lf28ddc_14:
    lda $34
    clc
    adc #$2A50
    tax
    lda $400000,x
    xba
    sta $9E
    lda $00
    sec
    sbc $9E
    bvs Lf28ddc_15
    bpl Lf28ddc_16
    bra Lf28ddc_17
Lf28ddc_15:
    bmi Lf28ddc_16
    bra Lf28ddc_17
Lf28ddc_16:
    jmp L28ddc_28e7c
Lf28ddc_17:
    lda $34
    clc
    adc #$2A50
    tax
    lda $400000,x
    xba
    sta $9E
    lda $04
    sec
    sbc $9E
    beq Lf28ddc_19
    bvs Lf28ddc_18
    bmi Lf28ddc_19
    bra Lf28ddc_20
Lf28ddc_18:
    bpl Lf28ddc_19
    bra Lf28ddc_20
Lf28ddc_19:
    jmp L28ddc_28e7c
Lf28ddc_20:
L28ddc_28e78:
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A53
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L28ddc_28e7c:
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    and #$0002
    bne Lf28ddc_21
    jmp L28ddc_28e90
Lf28ddc_21:
    lda $34
    clc
    adc #$2A5C
    tax
    lda $400000,x
    xba
    sta $9E
    lda $00
    sec
    sbc $9E
    bvs Lf28ddc_22
    bpl Lf28ddc_23
    bra Lf28ddc_24
Lf28ddc_22:
    bmi Lf28ddc_23
    bra Lf28ddc_24
Lf28ddc_23:
    jmp L28ddc_28e94
Lf28ddc_24:
    lda $34
    clc
    adc #$2A5C
    tax
    lda $400000,x
    xba
    sta $9E
    lda $04
    sec
    sbc $9E
    beq Lf28ddc_26
    bvs Lf28ddc_25
    bmi Lf28ddc_26
    bra Lf28ddc_27
Lf28ddc_25:
    bpl Lf28ddc_26
    bra Lf28ddc_27
Lf28ddc_26:
    jmp L28ddc_28e94
Lf28ddc_27:
L28ddc_28e90:
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A5F
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L28ddc_28e94:
    lda $34
    clc
    adc #$3EBC
    tax
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda #$80E8
    pha
    lda $30
    clc
    adc #$000A
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$00C0
    pha
    lda $30
    clc
    adc #$000C
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0002
    pha
    lda $30
    clc
    adc #$000D
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0001
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda #$0008
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda #$0178
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda #$00D0
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda #$00E0
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    jmp L28ddc_28ed2
L28ddc_28ec0:
    lda #$0000
    pha
    lda $34
    clc
    adc #$3EB8
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$3EBC
    tax
    lda $400000,x
    xba
    sta $32
    inx
    inx
    lda $400000,x
    xba
    sta $30
    lda #$0000
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A53
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A5F
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L28ddc_28ed2:
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- entry_24d98 — $024D98 scan sub (×4 over $3702(a5)); cold trap#1 edge = pre-pushed bail ---
; --- transpiled from $024D98 (27 instrs) by tools/transpile.py [bank1] ---
entry_24d98:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda #$0003
    sta $18
    lda $34
    clc
    adc #$3702
    sta $24
    lda $36
    adc #$0000
    sta $26
    lda $24
    clc
    adc #$0004
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9A
    lda $9E
    sta $9C
    lda $9C
    bne Lf24d98_1
    lda $9A
    bne Lf24d98_1
    jmp Ltj24d98_24e0e
Lf24d98_1:
    lda #$0000
    sta $04
    sta $06
    lda #$0000
    sta $00
    sta $02
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $9E
    lda $04
    sec
    sbc $9E
    sta $04
    ; HAND-PATCH (X-flag gap): `sub.w $2a32(a5),d1` is the ONLY hot-path X-SETTER in the trap#5
    ; shell cluster, and the trap#5 yield that follows SAVES SR (sr_build reads $A2) into the task
    ; frame -> a stale $A2 lands in work RAM (FULLDIFF caught it: $F00D01 = $14 vs $04 = bit 4).
    ; 68K X = the sub's borrow = !native C (still live: sta/lda don't touch carry). php/plp keeps
    ; N/Z/C for the fused ble lowering below. Cold-path X-setters (28ddc's $2930==2 arm, this
    ; body's trap#1 branch subq/lsr) keep the documented transpiler gap ("cmp X-untouched" class).
    php
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    plp
    lda $04
    beq Lf24d98_2
    bmi Lf24d98_2
    bra Lf24d98_3
Lf24d98_2:
    jmp Ltj24d98_24e02
Lf24d98_3:
    lda $04
    pha
    lda $24
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$0002
    tax
    lda $400000,x
    xba
    sta $08
    lda $00
    and #$001F
    cmp #$0010
    bcc Lf24d98_4
    sec
    sbc #$0010
    tax
    lda $0A
    bra Lf24d98_5
Lf24d98_4:
    tax
    lda $08
Lf24d98_5:
Lf24d98_6:
    cpx #$0000
    beq Lf24d98_7
    lsr a
    dex
    bra Lf24d98_6
Lf24d98_7:
    and #$0001
    bne Lf24d98_8
    jmp L24d98_24dd6
Lf24d98_8:
    lda #$00B4
    pha
    lda $24
    clc
    adc #$0008
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$4E0E
    sta $40
    lda #$0002
    sta $42
    jml.l inext
L24d98_24dd6:
    lda $24
    clc
    adc #$0008
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    bne Lf24d98_9
    jmp L24d98_24de6
Lf24d98_9:
    lda $24
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    xba
    sta $400000,x
    xba
    lda #$4E0E
    sta $40
    lda #$0002
    sta $42
    jml.l inext
L24d98_24de6:
    lda $04
    lsr a
    lsr a
    lsr a
    lsr a
    sta $04
    lda $24
    clc
    adc #$0004
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0006
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $28
    lda $9E
    sta $2A
    lda $04
    sta $9A
    lda $06
    sta $9C
    lda $3C
    sec
    sbc #$0004
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $9C
    pha
    lda $3C
    clc
    adc #$0000
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $9A
    pha
    lda $3C
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $00
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $56
    jsl.l push32_l
    lda #$4DF2
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24d98_24e02:
    lda #$4E02
    sta $40
    lda #$0002
    sta $42
    jml.l inext
Ltj24d98_24e0e:
    lda #$4E0E
    sta $40
    lda #$0002
    sta $42
    jml.l inext

; --- entry_c604: CP1 2.2 — the $C58A game-mode yield loop (light-tick task; resume $00C604,
; yield trap#5 $00C602; mode-transition branches -> bank-$01 Ltj bails, faithful) ---
; --- transpiled from $00C604 (30 instrs) by tools/transpile.py [bank1] ---
; (RESUME PC $00C604 = `bra.b $c58a`; the body is the $00C58A game-mode yield loop it lands in —
;  regen: transpile.py 00C58A --coroutine --bail --bank2 --xflag + this header/name fixup)
entry_c604:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda #$0000
    pha
    lda $38
    clc
    adc #$FFA0
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $38
    clc
    adc #$FF8E
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $38
    clc
    adc #$FF98
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CCC
    tax
    lda $400000,x
    xba
    sta $00
    lda #$3206
    sta $2C
    lda #$0001
    sta $2E
    lda $38
    clc
    adc #$FFB0
    tax
    lda $400000,x
    xba
    bne Lfc58a_1
    jmp Lc58a_c5ac
Lfc58a_1:
    lda #$3206
    sta $2C
    lda #$0001
    sta $2E
Lc58a_c5ac:
    lda $00
    sec
    sbc #$0006
    bne Lfc58a_2
    jmp Ltjc58a_1252a
Lfc58a_2:
    lda $00
    sec
    sbc #$0008
    bne Lfc58a_3
    jmp Ltjc58a_1252a
Lfc58a_3:
    lda #$2318
    sta $2C
    lda #$0003
    sta $2E
    lda $38
    clc
    adc #$FFB0
    tax
    lda $400000,x
    xba
    bne Lfc58a_4
    jmp Lc58a_c5ce
Lfc58a_4:
    lda #$2318
    sta $2C
    lda #$0003
    sta $2E
Lc58a_c5ce:
    lda $00
    sec
    sbc #$0012
    bne Lfc58a_5
    jmp Ltjc58a_11420
Lfc58a_5:
    lda $00
    sec
    sbc #$0003
    bne Lfc58a_6
    jmp Ltjc58a_11420
Lfc58a_6:
    lda $00
    sec
    sbc #$0004
    bne Lfc58a_7
    jmp Ltjc58a_11576
Lfc58a_7:
    lda $00
    sec
    sbc #$0005
    bne Lfc58a_8
    jmp Ltjc58a_11420
Lfc58a_8:
    lda $00
    sec
    sbc #$0007
    beq Lfc58a_9
    jmp Lc58a_c602
Lfc58a_9:
    lda $34
    clc
    adc #$2930
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    bne Lfc58a_10
    jmp Ltjc58a_11420
Lfc58a_10:
    lda #$1576
    sta $40
    lda #$0001
    sta $42
    jml.l inext
Lc58a_c602:
    lda #$C602
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc58a_11420:
    lda #$1420
    sta $40
    lda #$0001
    sta $42
    jml.l inext
Ltjc58a_11576:
    lda #$1576
    sta $40
    lda #$0001
    sta $42
    jml.l inext
Ltjc58a_1252a:
    lda #$252A
    sta $40
    lda #$0001
    sta $42
    jml.l inext

; --- entry_c78e: CP1 2.2 — light-tick task resume $00C78E: movem/push + jsr $4a9e.l
; (static-linked entry_4a9e same-bank) + tail incl. the hot jsr (a0) via $1c8a(a5)
; (INDIRECT-BRIDGE -> xlat -> entry_ce4t native) -> yield trap#5 $00C7DA. 1 guarded
; t-variant arm(s) stripped. ---
; --- transpiled from $00C78E (21 instrs) by tools/transpile.py [bank1] ---
entry_c78e:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $18
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $14
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $08
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $04
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $4a9e.l -> entry_4a9e (NATIVE escape), resume brc78e_1
    lda #brc78e_1
    sta $40
    lda #$00FA
    sta $42
    jmp entry_4a9e
brc78e_1:
    lda #$0002
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    ldx $3C
    lda $400000,x
    xba
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $14
    lda $14
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $16
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $18
    lda $18
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1A
    lda $3C
    clc
    adc #$0002
    sta $3C
    lda $1C
    beq Lfc78e_1
    jmp Ltjc78e_c8ba
Lfc78e_1:
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    pha
    lda $04
    and #$0007
    tax
    pla
Lfc78e_2:
    cpx #$0000
    beq Lfc78e_3
    lsr a
    dex
    bra Lfc78e_2
Lfc78e_3:
    and #$0001
    beq Lfc78e_4
    jmp Ltjc78e_c8da
Lfc78e_4:
    lda $08
    dec a
    sta $08
    cmp #$FFFF
    beq Lfc78e_5
    jmp Ltjc78e_c78c
Lfc78e_5:
    lda #$0007
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$4E56
    sta $54
    lda #$0000
    sta $56
    jsl.l push32_l
    lda $14
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$00E0
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $18
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C8A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
Lfc78e_6:
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brc78e_2
    lda #brc78e_2
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brc78e_2:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda #$0009
    sta $08
    lda #$C7DA
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc78e_c78c:
    lda #$C78C
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc78e_c8ba:
    lda #$C8BA
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc78e_c8da:
    lda #$C8DA
    sta $40
    lda #$0000
    sta $42
    jml.l inext

; --- entry_4a9e: the $004A9E link-frame body (CP1 "hard target" — transpiles clean with
; --bail; --xflag REQUIRED: 22 X-setter sites (lsl/lsr/neg/subq) and the caller's trap#5
; SR-save exposes stale X — the trap5-shells $F00D01 lesson, now transpiler-handled) ---
; --- transpiled from $004A9E (141 instrs) by tools/transpile.py [bank1] ---
entry_4a9e:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $38
    sta $54
    lda $3A
    sta $56
    jsl.l push32_l
    lda $3C
    sta $38
    lda $3E
    sta $3A
    lda $3C
    clc
    adc #$FFFC
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $34
    clc
    adc #$3EE2
    tax
    lda $400000,x
    xba
    bne Lf4a9e_1
    jmp L4a9e_4b84
Lf4a9e_1:
    lda $34
    clc
    adc #$1C76
    tax
    lda $400000,x
    xba
    beq Lf4a9e_2
    jmp L4a9e_4abe
Lf4a9e_2:
    lda $34
    clc
    adc #$1C62
    tax
    lda $400000,x
    xba
    beq Lf4a9e_3
    jmp L4a9e_4abe
Lf4a9e_3:
    jmp L4a9e_4b84
L4a9e_4abe:
    lda #$0001
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $04
    lda $04
    bpl Lf4a9e_4
    jmp L4a9e_4ad2
Lf4a9e_4:
    lda $04
    and #$003F
    tax
    lda $00
Lf4a9e_5:
    cpx #$0000
    beq Lf4a9e_6
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_5
Lf4a9e_6:
    sta $00
    jmp L4a9e_4ad6
L4a9e_4ad2:
    lda $04
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_7
    lda #$0001
    bra Lf4a9e_8
Lf4a9e_7:
    lda #$0000
Lf4a9e_8:
    sta $A2
    pla
    plp
    sta $04
    lda $04
    and #$003F
    tax
    lda $00
Lf4a9e_9:
    cpx #$0000
    beq Lf4a9e_10
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_9
Lf4a9e_10:
    sta $00
L4a9e_4ad6:
    lda $34
    clc
    adc #$2936
    tax
    lda $400000,x
    xba
    sta $08
    lda $08
    and $00
    sta $08
    lda $08
    bne Lf4a9e_11
    jmp L4a9e_4b84
Lf4a9e_11:
    lda $34
    clc
    adc #$2A4A
    tax
    lda $400000,x
    xba
    beq Lf4a9e_12
    jmp L4a9e_4b06
Lf4a9e_12:
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    beq Lf4a9e_13
    jmp L4a9e_4afa
Lf4a9e_13:
    lda $34
    clc
    adc #$1C52
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $0C
    rep #$20
    lda $0C
    eor #$00FF
    sta $0C
    lda $0C
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L4a9e_4b04
L4a9e_4afa:
    lda $34
    clc
    adc #$1C53
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $10
    rep #$20
    lda $10
    eor #$00FF
    sta $10
    lda $10
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4b04:
    jmp L4a9e_4b0a
L4a9e_4b06:
    lda #$0000
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4b0a:
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    beq Lf4a9e_14
    jmp L4a9e_4b1a
Lf4a9e_14:
    lda $34
    clc
    adc #$1C4E
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $14
    rep #$20
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    ora $14
    sep #$20
    sta $400000,x
    rep #$20
    jmp L4a9e_4b22
L4a9e_4b1a:
    lda $34
    clc
    adc #$1C4F
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $18
    rep #$20
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    ora $18
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4b22:
    lda #$0000
    sta $04
    sta $06
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $04
    rep #$20
    lda $04
    and #$0080
    sta $04
    lda $04
    beq Lf4a9e_15
    jmp L4a9e_4b84
Lf4a9e_15:
    lda $34
    clc
    adc #$1C76
    tax
    lda $400000,x
    xba
    bne Lf4a9e_16
    jmp L4a9e_4b3c
Lf4a9e_16:
    lda $34
    clc
    adc #$1C76
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    jmp L4a9e_4b4a
L4a9e_4b3c:
    lda $34
    clc
    adc #$1C62
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C64
    tax
    lda $400000,x
    xba
    sta $00
    lda $00
    sec
    sbc #$0001
    sta $00
    php
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    plp
    lda $00
    pha
    lda $34
    clc
    adc #$1C76
    tax
    pla
    xba
    sta $400000,x
    xba
L4a9e_4b4a:
    lda #$0001
    sep #$20
    sta $08
    rep #$20
    lda $08
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $08
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $0C
    lda $0C
    bpl Lf4a9e_17
    jmp L4a9e_4b5a
Lf4a9e_17:
    lda $0C
    and #$003F
    tax
    lda $08
Lf4a9e_18:
    cpx #$0000
    beq Lf4a9e_19
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_18
Lf4a9e_19:
    sta $08
    jmp L4a9e_4b5e
L4a9e_4b5a:
    lda $0C
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_20
    lda #$0001
    bra Lf4a9e_21
Lf4a9e_20:
    lda #$0000
Lf4a9e_21:
    sta $A2
    pla
    plp
    sta $0C
    lda $0C
    and #$003F
    tax
    lda $08
Lf4a9e_22:
    cpx #$0000
    beq Lf4a9e_23
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_22
Lf4a9e_23:
    sta $08
L4a9e_4b5e:
    lda $34
    clc
    adc #$2A4A
    tax
    lda $400000,x
    xba
    ora $08
    xba
    sta $400000,x
    xba
    lda #$0001
    sep #$20
    sta $10
    rep #$20
    lda $10
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $10
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $14
    lda $14
    bpl Lf4a9e_24
    jmp L4a9e_4b72
Lf4a9e_24:
    lda $14
    and #$003F
    tax
    lda $10
Lf4a9e_25:
    cpx #$0000
    beq Lf4a9e_26
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_25
Lf4a9e_26:
    sta $10
    jmp L4a9e_4b76
L4a9e_4b72:
    lda $14
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_27
    lda #$0001
    bra Lf4a9e_28
Lf4a9e_27:
    lda #$0000
Lf4a9e_28:
    sta $A2
    pla
    plp
    sta $14
    lda $14
    and #$003F
    tax
    lda $10
Lf4a9e_29:
    cpx #$0000
    beq Lf4a9e_30
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_29
Lf4a9e_30:
    sta $10
L4a9e_4b76:
    lda $34
    clc
    adc #$2936
    tax
    lda $400000,x
    xba
    ora $10
    xba
    sta $400000,x
    xba
    lda #$FFFF
    pha
    lda $38
    clc
    adc #$FFFC
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L4a9e_4c44
L4a9e_4b84:
    lda $34
    clc
    adc #$1C62
    tax
    lda $400000,x
    xba
    bne Lf4a9e_31
    jmp L4a9e_4c3a
Lf4a9e_31:
    lda #$0001
    sep #$20
    sta $18
    rep #$20
    lda $18
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $18
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $04
    lda $04
    bpl Lf4a9e_32
    jmp L4a9e_4ba0
Lf4a9e_32:
    lda $04
    and #$003F
    tax
    lda $18
Lf4a9e_33:
    cpx #$0000
    beq Lf4a9e_34
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_33
Lf4a9e_34:
    sta $18
    jmp L4a9e_4ba4
L4a9e_4ba0:
    lda $04
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_35
    lda #$0001
    bra Lf4a9e_36
Lf4a9e_35:
    lda #$0000
Lf4a9e_36:
    sta $A2
    pla
    plp
    sta $04
    lda $04
    and #$003F
    tax
    lda $18
Lf4a9e_37:
    cpx #$0000
    beq Lf4a9e_38
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_37
Lf4a9e_38:
    sta $18
L4a9e_4ba4:
    lda $34
    clc
    adc #$2A4A
    tax
    lda $400000,x
    xba
    sta $00
    lda $00
    and $18
    sta $00
    lda $00
    beq Lf4a9e_39
    jmp L4a9e_4c3a
Lf4a9e_39:
    lda $34
    clc
    adc #$2A4A
    tax
    lda $400000,x
    xba
    beq Lf4a9e_40
    jmp L4a9e_4bd4
Lf4a9e_40:
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    beq Lf4a9e_41
    jmp L4a9e_4bc8
Lf4a9e_41:
    lda $34
    clc
    adc #$1C52
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $0C
    rep #$20
    lda $0C
    eor #$00FF
    sta $0C
    lda $0C
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    jmp L4a9e_4bd2
L4a9e_4bc8:
    lda $34
    clc
    adc #$1C53
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $08
    rep #$20
    lda $08
    eor #$00FF
    sta $08
    lda $08
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4bd2:
    jmp L4a9e_4bd8
L4a9e_4bd4:
    lda #$0000
    pha
    lda $38
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4bd8:
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    beq Lf4a9e_42
    jmp L4a9e_4be8
Lf4a9e_42:
    lda $34
    clc
    adc #$1C4E
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $14
    rep #$20
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    ora $14
    sep #$20
    sta $400000,x
    rep #$20
    jmp L4a9e_4bf0
L4a9e_4be8:
    lda $34
    clc
    adc #$1C4F
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $10
    rep #$20
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    ora $10
    sep #$20
    sta $400000,x
    rep #$20
L4a9e_4bf0:
    lda #$0000
    sta $04
    sta $06
    lda $38
    clc
    adc #$FFFE
    tax
    lda $400000,x
    and #$00FF
    sep #$20
    sta $04
    rep #$20
    lda $04
    and #$0080
    sta $04
    lda $04
    beq Lf4a9e_43
    jmp L4a9e_4c3a
Lf4a9e_43:
    lda $34
    clc
    adc #$1C62
    tax
    lda $400000,x
    xba
    sec
    sbc #$0001
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    lda #$0001
    sep #$20
    sta $18
    rep #$20
    lda $18
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $18
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $00
    lda $00
    bpl Lf4a9e_44
    jmp L4a9e_4c12
Lf4a9e_44:
    lda $00
    and #$003F
    tax
    lda $18
Lf4a9e_45:
    cpx #$0000
    beq Lf4a9e_46
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_45
Lf4a9e_46:
    sta $18
    jmp L4a9e_4c16
L4a9e_4c12:
    lda $00
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_47
    lda #$0001
    bra Lf4a9e_48
Lf4a9e_47:
    lda #$0000
Lf4a9e_48:
    sta $A2
    pla
    plp
    sta $00
    lda $00
    and #$003F
    tax
    lda $18
Lf4a9e_49:
    cpx #$0000
    beq Lf4a9e_50
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_49
Lf4a9e_50:
    sta $18
L4a9e_4c16:
    lda $34
    clc
    adc #$2A4A
    tax
    lda $400000,x
    xba
    ora $18
    xba
    sta $400000,x
    xba
    lda #$0001
    sep #$20
    sta $0C
    rep #$20
    lda $0C
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $0C
    lda $38
    clc
    adc #$0008
    tax
    lda $400000,x
    xba
    sta $08
    lda $08
    bpl Lf4a9e_51
    jmp L4a9e_4c2a
Lf4a9e_51:
    lda $08
    and #$003F
    tax
    lda $0C
Lf4a9e_52:
    cpx #$0000
    beq Lf4a9e_53
    asl a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_52
Lf4a9e_53:
    sta $0C
    jmp L4a9e_4c2e
L4a9e_4c2a:
    lda $08
    eor #$FFFF
    inc a
    php
    pha
    and #$FFFF
    beq Lf4a9e_54
    lda #$0001
    bra Lf4a9e_55
Lf4a9e_54:
    lda #$0000
Lf4a9e_55:
    sta $A2
    pla
    plp
    sta $08
    lda $08
    and #$003F
    tax
    lda $0C
Lf4a9e_56:
    cpx #$0000
    beq Lf4a9e_57
    lsr a
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    dex
    bra Lf4a9e_56
Lf4a9e_57:
    sta $0C
L4a9e_4c2e:
    lda $34
    clc
    adc #$2936
    tax
    lda $400000,x
    xba
    ora $0C
    xba
    sta $400000,x
    xba
    lda #$FFFF
    pha
    lda $38
    clc
    adc #$FFFC
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L4a9e_4c44
L4a9e_4c3a:
    lda #$0000
    sep #$20
    sta $14
    rep #$20
    lda $14
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $14
    lda $14
    pha
    lda $38
    clc
    adc #$FFFC
    tax
    pla
    xba
    sta $400000,x
    xba
L4a9e_4c44:
    lda $38
    clc
    adc #$FFFC
    tax
    lda $400000,x
    xba
    sta $1C
    lda $1C
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1E
    lda $38
    sta $3C
    lda $3A
    sta $3E
    ldx $3C
    lda $400000,x
    xba
    sta $3A
    inx
    inx
    lda $400000,x
    xba
    sta $38
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- entry_cd1a: CP1 2.2 — task resume $00CD1A (stable across tick classes); 30-instr
; spine ending in a FAITHFUL rts (pops the real $D522 return -> ors_pre routes it to the
; interp; the post-rts pc-rel jmp(a0) dispatcher/handler chain stays interpreted = the
; documented 2.2 residual) ---
; --- transpiled from $00CD1A (30 instrs) by tools/transpile.py [bank1] ---
entry_cd1a:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $34
    clc
    adc #$2A49
    tax
    lda $400000,x
    and #$00FF
    and #$0001
    beq Lfcd1a_1
    jmp Lcd1a_cd34
Lfcd1a_1:
    lda #$0012
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$01B6
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C9A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brcd1a_1
    lda #brcd1a_1
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brcd1a_1:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
Lcd1a_cd34:
    lda $34
    clc
    adc #$2A49
    tax
    lda $400000,x
    and #$00FF
    and #$0002
    beq Lfcd1a_2
    jmp Lcd1a_cd4e
Lfcd1a_2:
    lda #$0012
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$03AC
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C9A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brcd1a_2
    lda #brcd1a_2
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brcd1a_2:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
Lcd1a_cd4e:
    lda $34
    clc
    adc #$2A49
    tax
    lda $400000,x
    and #$00FF
    and #$0004
    beq Lfcd1a_3
    jmp Lcd1a_cd68
Lfcd1a_3:
    lda #$0012
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$01DE
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C9A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brcd1a_3
    lda #brcd1a_3
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brcd1a_3:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
Lcd1a_cd68:
    lda $34
    clc
    adc #$2A49
    tax
    lda $400000,x
    and #$00FF
    and #$0008
    beq Lfcd1a_4
    jmp Lcd1a_cd82
Lfcd1a_4:
    lda #$0012
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$03D4
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C9A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brcd1a_4
    lda #brcd1a_4
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brcd1a_4:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
Lcd1a_cd82:
    lda #$0000
    pha
    lda $34
    clc
    adc #$2A48
    tax
    pla
    xba
    sta $400000,x
    xba
    ldx $3C
    lda $400000,x
    xba
    and #$00FF
    sta $42
    inx
    inx
    lda $400000,x
    xba
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- entry_c846: CP1 2.2 — the GAMEPLAY-tick per-slot yield loop (the c78e twin, resume
; $00C846 fires EVERY gameplay tick): movem/push + jsr $4a9e.l (static-linked entry_4a9e
; same-bank) + slot-exit guards; dbra-taken -> Ltj $00C844 = the interpreted trap#5 yield.
; 1 guarded t-variant arm(s) stripped (INDIRECT fall-through faithful). ---
; --- transpiled from $00C846 (21 instrs) by tools/transpile.py [bank1] ---
entry_c846:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $18
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $14
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $08
    xba
    sta $400000,x
    xba
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $04
    xba
    sta $400000,x
    xba
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    ; CALL-BRIDGE jsr $4a9e.l -> entry_4a9e (NATIVE escape), resume brc846_1
    lda #brc846_1
    sta $40
    lda #$00FA
    sta $42
    jmp entry_4a9e
brc846_1:
    lda #$0002
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    ldx $3C
    lda $400000,x
    xba
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $14
    lda $14
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $16
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    lda $400000,x
    xba
    sta $18
    lda $18
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1A
    lda $3C
    clc
    adc #$0002
    sta $3C
    lda $1C
    beq Lfc846_1
    jmp Ltjc846_c8ba
Lfc846_1:
    lda $34
    clc
    adc #$2A4B
    tax
    lda $400000,x
    and #$00FF
    pha
    lda $04
    and #$0007
    tax
    pla
Lfc846_2:
    cpx #$0000
    beq Lfc846_3
    lsr a
    dex
    bra Lfc846_2
Lfc846_3:
    and #$0001
    beq Lfc846_4
    jmp Ltjc846_c8da
Lfc846_4:
    lda $08
    dec a
    sta $08
    cmp #$FFFF
    beq Lfc846_5
    jmp Ltjc846_c844
Lfc846_5:
    lda #$0007
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$4E56
    sta $54
    lda #$0000
    sta $56
    jsl.l push32_l
    lda $14
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$00E0
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $18
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C8A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
Lfc846_6:
    ; INDIRECT-BRIDGE jsr (a0) -> ojmp_hook (a0 --table escape, else interpret); $00FD sentinel, resume brc846_2
    lda #brc846_2
    sta $54
    lda #$00FA
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l ojmp_hook
brc846_2:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda #$0009
    sta $08
    lda #$C890
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc846_c844:
    lda #$C844
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc846_c8ba:
    lda #$C8BA
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjc846_c8da:
    lda #$C8DA
    sta $40
    lda #$0000
    sta $42
    jml.l inext
