.snes
; escbank2.pasm — SECOND SA-1 escape bank at $94:8000 (file $2A0000). For native escapes too big for
; the $92 bodies region (which overflowed past $F000 into jah2_ext; see escbank-overflow-second-bank).
; Reached from $92 dispatchers (entry_4542 bridge, jah2_ext slot, ojmp_disp, ...) via `jml entry_X`
; (24-bit cross-bank; escbank2's entry_X syms are fed into escbank.pasm by gen_escbank_syms.py).
; Bodies are --bank2 transpiled: bank-$00 helpers via jsl.l/jml.l; jsr(An) inlined w/ a $00FD sentinel
; (ors_pre -> ors_94chk -> bank-$94 resume). The leading `.snes` is REQUIRED (rep/sep tracking).

; >>> ESCBANK2_SYMS — auto-generated by tools/gen_escbank2_syms.py (do not edit) <<<
inext=$00D128
rdw40_l=$00E59E
wrw40_l=$00E5A2
rdb40_l=$00E5A6
wrb40_l=$00E5AA
push32_l=$00E5AE
rdw_ea_l=$00E5B2
readbyte_l=$00E5B6
writeword_l=$00E5BA
writebyte_l=$00E5BE
usmul_l=$00E5C2
op_rts_sentinel=$00EA3A
ojmp_hook=$00D1B3
ors_pre=$00D16F
; <<< ESCBANK2_SYMS <<<

    .org $8000

; esc_udiv — bank-$94 LOCAL unsigned 32/16 division for transpiled DIVU.w (a same-bank `jsr esc_udiv`;
; do NOT name it `udiv` -- collides with interp.pasm's bank-$00 udiv). in: dividend $50(lo):$52(hi) /
; divisor $54 -> quot $50:$52, rem $94.
esc_udiv:
    rep #$30             ; Poppy: assert 16-bit M/X here (this routine is jsr'd standalone, so the
                         ; caller's rep #$30 isn't tracked -> `ldy #$0020` would mis-size to 2 bytes)
    stz $94
    ldy #$0020
esud_l:
    asl $50
    rol $52
    rol $94
    bcs esud_sub
    lda $94
    cmp $54
    bcc esud_no
esud_sub:
    lda $94
    sec
    sbc $54
    sta $94
    inc $50
esud_no:
    dey
    bne esud_l
    rts

; esc_ac_charge — TASK #73 frame-pacing fix. The vblank-IRQ frame boundary fires when $AC (the per-
; frame interp-step countdown, interp.pasm reload=$7000) hits EXACTLY 0 via the main loop's `dec $AC`.
; An escape is ONE step but does N 68K instrs, so it must charge $AC by N (the main loop only takes 1).
; in: A = N (16-bit, instr count to charge). Decrements $AC by N; CLAMPS to 1 on underflow/zero so the
; next main-loop `dec` fires the boundary cleanly (never fires VID_FRAME mid-escape). Uses the stack for
; scratch (no DP clobber); clobbers A, preserves X/Y. Off-by-<=1-escape/frame timing error = negligible.
esc_ac_charge:
    rep #$30
    pha                  ; [16-bit N on stack]
    lda $AC
    sec
    sbc $01,s            ; $AC - N
    bcc eacc_clamp       ; borrow -> $AC < N -> underflow
    beq eacc_clamp       ; == 0 -> clamp (boundary needs the main-loop dec to reach 0)
    sta $AC
    pla
    rts
eacc_clamp:
    lda #$0001
    sta $AC
    pla
    rts

; --- transpiled from $00C9F8 (43 instrs) by tools/transpile.py [bank1] ---
entry_c9f8:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda #$0120
    sta $00
    lda $34
    clc
    adc #$1CCC
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$000D
    bne Lfc9f8_1
    jmp Lc9f8_ca08
Lfc9f8_1:
    lda #$0090
    sta $00
Lc9f8_ca08:
    lda #$0003
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$CA8E
    sta $54
    lda #$0000
    sta $56
    jsl.l push32_l
    lda $00
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$00E0
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$003C
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $34
    clc
    adc #$1C8A
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $22
    lda $34
    clc
    adc #$1C8C
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> interpret callee ($00FD bank-94 sentinel), resume brc9f8_1
    lda #brc9f8_1
    sta $54
    lda #$00FD
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l inext
brc9f8_1:
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    lda $00
    clc
    adc #$0040
    sta $00
    lda $34
    clc
    adc #$1C62
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $04
    sec
    sbc #$0064
    bvs Lfc9f8_2
    bmi Lfc9f8_3
    bra Lfc9f8_4
Lfc9f8_2:
    bpl Lfc9f8_3
    bra Lfc9f8_4
Lfc9f8_3:
    jmp Lc9f8_ca3e
Lfc9f8_4:
    lda #$0063
    sta $04
Lc9f8_ca3e:
    lda $04
    sta $50
    lda $06
    sta $52
    lda #$000A
    sta $54
    jsr esc_udiv
    lda $52
    bne dvovc9f8_2
    lda $50
    sta $04
    lda $94
    sta $06
dvovc9f8_2:
    lda $04
    clc
    adc #$E081
    sta $04
    lda #$E002
    sta $04
    lda $04
    sta $54
    lda $06
    sta $56
    jsl.l push32_l
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $00
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$00E0
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0046
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $34
    clc
    adc #$1CAE
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $22
    lda $34
    clc
    adc #$1CB0
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> interpret callee ($00FD bank-94 sentinel), resume brc9f8_3
    lda #brc9f8_3
    sta $54
    lda #$00FD
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l inext
brc9f8_3:
    lda #$000A
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $06
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $04
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $04
    tax
    lda $06
    sta $04
    txa
    sta $06
    lda $04
    clc
    adc #$E08B
    sta $04
    lda $04
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $00
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$00E0
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0000
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0044
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $34
    clc
    adc #$1CAE
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $22
    lda $34
    clc
    adc #$1CB0
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> interpret callee ($00FD bank-94 sentinel), resume brc9f8_4
    lda #brc9f8_4
    sta $54
    lda #$00FD
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l inext
brc9f8_4:
    lda #$000A
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $42
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- $00D5A0 leaf (escbank2 / $94): reached by `$D5EE bra $d5a0` INSIDE the $D5C4 state
; handler -- NOT a jmp-table dispatch. entry_d5c4 jml's here instead of bailing to the
; interpreter, so its $D5A0 tail loop (~14 interp-instr/fr) runs native. Ends in rts (pop
; 24-bit return -> ors_pre), like the coroutine task body it belongs to. ---
; --- transpiled from $00D5A0 (8 instrs) by tools/transpile.py [bank1] ---
entry_d5a0:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $34
    clc
    adc #$2AA8
    sta $20
    lda $36
    adc #$0000
    sta $22
    lda $30
    clc
    adc #$FFF5
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $20
    clc
    adc $9A
    sta $20
    lda $22
    adc $9C
    sta $22
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l readbyte_l
    beq Lfd5a0_1
    bmi Lfd5a0_1
    bra Lfd5a0_2
Lfd5a0_1:
    jmp Ld5a0_d5b2
Lfd5a0_2:
    lda #$0000
    sep #$20
    sta $80
    rep #$20
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l writebyte_l
Ld5a0_d5b2:
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $42
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- $001008 sprite-builder, jah2_ext jsr deploy (bank2 $94) ---
; --- transpiled from $001008 (38 instrs) by tools/transpile.py [bank1] ---
entry_1008:
    rep #$30
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $38
    sta $54
    lda $3A
    sta $56
    jsl.l push32_l
    lda $3C
    sta $38
    lda $3E
    sta $3A
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $18
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $14
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $10
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $0C
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $08
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $04
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $00
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $38
    clc
    adc #$0008
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $1C
    lda $34
    clc
    adc #$1CF6
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda $34
    clc
    adc #$20F2
    sta $2C
    lda $36
    adc #$0000
    sta $2E
    lda $34
    clc
    adc #$24EE
    sta $28
    lda $36
    adc #$0000
    sta $2A
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $30
    clc
    adc $9A
    sta $30
    lda $32
    adc $9C
    sta $32
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $2C
    clc
    adc $9A
    sta $2C
    lda $2E
    adc $9C
    sta $2E
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $28
    clc
    adc $9A
    sta $28
    lda $2A
    adc $9C
    sta $2A
    lda #$00EA
    sta $00
    lda $38
    clc
    adc #$000C
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $9E
    lda $00
    sec
    sbc $9E
    sta $00
    lda $38
    clc
    adc #$000E
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $04
    lda $04
    clc
    adc #$0000
    sta $04
    lda $38
    clc
    adc #$000A
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $9E
    lda $04
    clc
    adc $9E
    sta $04
    lda $38
    clc
    adc #$0010
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $26
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $24
    lda #$0008
    sta $14
    lda #$F9FF
    sta $0C
    lda #$0020
    sta $10
    lda #$005F
    sta $08
    lda #$0000
    sta $1C
L1008_1054:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l readbyte_l
    pha
    lda $24
    clc
    adc #$0001
    sta $24
    lda $26
    adc #$0000
    sta $26
    pla
    sep #$20
    sta $1C
    rep #$20
    lda $1C
    bne Lf1008_1
    jmp L1008_106e
Lf1008_1:
    lda $1C
    sec
    sbc $10
    bne Lf1008_2
    jmp L1008_106a
Lf1008_2:
    lda $1C
    sec
    sbc $08
    beq Lf1008_3
    jmp L1008_1062
Lf1008_3:
    lda $10
    sta $1C
L1008_1062:
    lda $1C
    pha
    lda $28
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $28
    clc
    adc #$0002
    sta $28
    lda $2A
    adc #$0000
    sta $2A
    lda $00
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $04
    and $0C
    sta $04
    lda $04
    pha
    lda $2C
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $2C
    clc
    adc #$0002
    sta $2C
    lda $2E
    adc #$0000
    sta $2E
L1008_106a:
    lda $04
    clc
    adc $14
    sta $04
    jmp L1008_1054
L1008_106e:
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $00
    lda $00
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $02
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $0C
    lda $0C
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0E
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $10
    lda $10
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $12
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $14
    lda $14
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $16
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $18
    lda $18
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $22
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $26
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2A
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2E
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $32
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $38
    sta $3C
    lda $3A
    sta $3E
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $3A
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $38
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $42
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; --- $00D01A jmp-state object handler ($CEB6 dispatch sibling of d0d0) ---
; --- transpiled from $00D01A (16 instrs) by tools/transpile.py [bank1] ---
entry_d01a:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $34
    clc
    adc #$2A4C
    sta $2C
    lda $36
    adc #$0000
    sta $2E
    lda $30
    clc
    adc #$FFF5
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    bne Lfd01a_1
    jmp Ld01a_d028
Lfd01a_1:
    lda $34
    clc
    adc #$2A58
    sta $2C
    lda $36
    adc #$0000
    sta $2E
Ld01a_d028:
    lda $2C
    clc
    adc #$0002
    sta $54
    lda $2E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $30
    clc
    adc #$FFFC
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$FFFC
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sec
    sbc #$0011
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $2C
    clc
    adc #$0004
    sta $54
    lda $2E
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $30
    clc
    adc #$FFFA
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$FFFA
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    clc
    adc #$001F
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0020
    pha
    lda $30
    clc
    adc #$FFF9
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $34
    clc
    adc #$2AA4
    sta $20
    lda $36
    adc #$0000
    sta $22
    lda $30
    clc
    adc #$FFF5
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $20
    clc
    adc $9A
    sta $20
    lda $22
    adc $9C
    sta $22
    lda #$0000
    pha
    lda $20
    clc
    adc #$0000
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda #$0008
    pha
    lda $30
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$CEC2
    sta $40
    lda #$0000
    sta $42
    jml.l inext
; --- $00D05E jmp-state object handler ($CEB6 dispatch sibling of d0d0) ---
; --- transpiled from $00D05E (7 instrs) by tools/transpile.py [bank1] ---
entry_d05e:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $30
    clc
    adc #$FFF8
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $30
    clc
    adc #$FFFA
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    clc
    adc $00
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$FFFA
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l rdw_ea_l
    sec
    sbc #$01A0
    bvs Lfd05e_1
    bmi Lfd05e_2
    bra Lfd05e_3
Lfd05e_1:
    bpl Lfd05e_2
    bra Lfd05e_3
Lfd05e_2:
    jmp Ld05e_d076
Lfd05e_3:
    lda #$0010
    pha
    lda $30
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
Ld05e_d076:
    lda #$CEC2
    sta $40
    lda #$0000
    sta $42
    jml.l inext
; --- $00D0BC jmp-state object handler ($CEB6 dispatch sibling of d0d0) ---
; --- transpiled from $00D0BC (6 instrs) by tools/transpile.py [bank1] ---
entry_d0bc:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $30
    clc
    adc #$FFF8
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $30
    clc
    adc #$FFFA
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    clc
    adc $00
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$FFF9
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sec
    sbc $00
    php
    pha
    lda $30
    clc
    adc #$FFF9
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    plp
    beq Lfd0bc_2
    bvs Lfd0bc_1
    bmi Lfd0bc_2
    bra Lfd0bc_3
Lfd0bc_1:
    bpl Lfd0bc_2
    bra Lfd0bc_3
Lfd0bc_2:
    jmp Ltjd0bc_d07a
Lfd0bc_3:
    lda #$CEC2
    sta $40
    lda #$0000
    sta $42
    jml.l inext
Ltjd0bc_d07a:
    lda #$D07A
    sta $40
    lda #$0000
    sta $42
    jml.l inext
; --- $00D07A jmp-state object handler ($CEB6 dispatch sibling of d0d0) ---
; --- transpiled from $00D07A (20 instrs) by tools/transpile.py [bank1] ---
entry_d07a:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    lda $30
    clc
    adc #$FFF0
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l rdw_ea_l
    sta $2E
    lda $30
    clc
    adc #$FFF2
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l rdw_ea_l
    sta $2C
    lda #$0000
    pha
    lda $2C
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0000
    pha
    lda $30
    clc
    adc #$FFFE
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $38
    clc
    adc #$FF1E
    sta $2C
    lda $3A
    adc #$0000
    sta $2E
    lda $30
    clc
    adc #$FFF5
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    bne Lfd07a_1
    jmp Ld07a_d094
Lfd07a_1:
    lda $38
    clc
    adc #$FF1C
    sta $2C
    lda $3A
    adc #$0000
    sta $2E
Ld07a_d094:
    lda $34
    clc
    adc #$2AA4
    sta $20
    lda $36
    adc #$0000
    sta $22
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $00
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $20
    clc
    adc $9A
    sta $20
    lda $22
    adc $9C
    sta $22
    lda #$0000
    pha
    lda $20
    clc
    adc #$0000
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$FFF4
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $00
    rep #$20
    lda $00
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $00
    lda $2C
    clc
    adc #$0000
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sec
    sbc $00
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda #$0001
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$FFF6
    sta $54
    lda $32
    adc #$FFFF
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $34
    clc
    adc #$1C9A
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $22
    lda $34
    clc
    adc #$1C9C
    sta $54
    lda $36
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> interpret callee ($00FD bank-94 sentinel), resume brd07a_1
    lda #brd07a_1
    sta $54
    lda #$00FD
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jml.l inext
brd07a_1:
    lda #$0004
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $3C
    clc
    adc $9A
    sta $3C
    lda $3E
    adc $9C
    sta $3E
    lda #$CF8A
    sta $40
    lda #$0000
    sta $42
    jml.l inext
; --- ce4t ship-validation 64KB ---
; --- transpiled from $000CE4 (57 instrs) by tools/transpile.py [bank1] ---
entry_ce4t:
    rep #$30
    lda $000724
    inc a
    sta $000724
    ; AOT-table/rts dispatch: caller return ALREADY on the 68K stack -> NO re-simulate push
    lda $38
    sta $54
    lda $3A
    sta $56
    jsl.l push32_l
    lda $3C
    sta $38
    lda $3E
    sta $3A
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $18
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $14
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $10
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $0C
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $08
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $04
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $00
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $38
    clc
    adc #$0008
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $1C
    lda $1C
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1E
    lda $34
    clc
    adc #$1CF6
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda $34
    clc
    adc #$20F2
    sta $2C
    lda $36
    adc #$0000
    sta $2E
    lda $34
    clc
    adc #$24EE
    sta $28
    lda $36
    adc #$0000
    sta $2A
    lda $30
    clc
    adc $1C
    sta $30
    lda $32
    adc $1E
    sta $32
    lda $2C
    clc
    adc $1C
    sta $2C
    lda $2E
    adc $1E
    sta $2E
    lda $28
    clc
    adc $1C
    sta $28
    lda $2A
    adc $1E
    sta $2A
    lda $38
    clc
    adc #$000A
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $18
    lda $38
    clc
    adc #$0010
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $22
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $20
    lda $20
    clc
    adc #$0004
    sta $24
    lda $22
    adc #$0000
    sta $26
    lda $38
    clc
    adc #$0014
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $1C
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda #$00EA
    sta $04
    lda $38
    clc
    adc #$000C
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $9E
    lda $04
    sec
    sbc $9E
    sta $04
Lce4t_d24:
    lda #$00FA
    sta $14
    lda $04
    sec
    sbc $14
    bvs Lfce4t_1
    bpl Lfce4t_2
    bra Lfce4t_3
Lfce4t_1:
    bmi Lfce4t_2
    bra Lfce4t_3
Lfce4t_2:
    jmp Lce4t_d34
Lfce4t_3:
    lda $04
    sec
    sbc #$FFFA
    beq Lfce4t_5
    bvs Lfce4t_4
    bmi Lfce4t_5
    bra Lfce4t_6
Lfce4t_4:
    bpl Lfce4t_5
    bra Lfce4t_6
Lfce4t_5:
    jmp Lce4t_d34
Lfce4t_6:
    lda $04
    sta $14
Lce4t_d34:
    lda $20
    clc
    adc #$0002
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $38
    clc
    adc #$000E
    tax
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $0C
    lda $0C
    clc
    adc #$0000
    sta $0C
Lce4t_d40:
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $24
    clc
    adc #$0002
    sta $24
    lda $26
    adc #$0000
    sta $26
    pla
    sta $10
    lda $10
    bne Lfce4t_7
    jmp Lce4t_d6c
Lfce4t_7:
    lda $0C
    sec
    sbc #$FFF0
    beq Lfce4t_9
    bvs Lfce4t_8
    bmi Lfce4t_9
    bra Lfce4t_10
Lfce4t_8:
    bpl Lfce4t_9
    bra Lfce4t_10
Lfce4t_9:
    jmp Lce4t_d50
Lfce4t_10:
    lda $0C
    sec
    sbc #$0180
    bvs Lfce4t_11
    bmi Lfce4t_12
    bra Lfce4t_13
Lfce4t_11:
    bpl Lfce4t_12
    bra Lfce4t_13
Lfce4t_12:
    jmp Lce4t_d56
Lfce4t_13:
Lce4t_d50:
    lda #$00FA
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    jmp Lce4t_d58
Lce4t_d56:
    lda $14
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
Lce4t_d58:
    lda $10
    clc
    adc #$2000
    sta $10
    lda $10
    pha
    lda $28
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $28
    clc
    adc #$0002
    sta $28
    lda $2A
    adc #$0000
    sta $2A
    lda $0C
    sta $10
    lda $10
    and #$01FF
    sta $10
    lda $10
    ora $18
    sta $10
    lda $10
    pha
    lda $2C
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $2C
    clc
    adc #$0002
    sta $2C
    lda $2E
    adc #$0000
    sta $2E
    lda $1C
    sec
    sbc #$0001
    sta $1C
    bvs Lfce4t_14
    bmi Lfce4t_15
    bra Lfce4t_16
Lfce4t_14:
    bpl Lfce4t_15
    bra Lfce4t_16
Lfce4t_15:
    jmp Lce4t_d8a
Lfce4t_16:
Lce4t_d6c:
    lda $0C
    clc
    adc #$0010
    sta $0C
    lda $08
    dec a
    sta $08
    cmp #$FFFF
    beq Lfce4t_17
    jmp Lce4t_d40
Lfce4t_17:
    lda $04
    sec
    sbc #$0010
    sta $04
    lda $00
    dec a
    sta $00
    cmp #$FFFF
    beq Lfce4t_18
    jmp Lce4t_d24
Lfce4t_18:
    lda $1C
    bpl Lfce4t_19
    jmp Lce4t_d8a
Lfce4t_19:
    lda #$00FA
    sta $00
Lce4t_d84:
    lda $00
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    sep #$20
    xba
    sta $400000,x
    xba
    sta $400001,x
    rep #$20
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $1C
    dec a
    sta $1C
    cmp #$FFFF
    beq Lfce4t_20
    jmp Lce4t_d84
Lfce4t_20:
Lce4t_d8a:
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $00
    lda $00
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $02
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $0C
    lda $0C
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0E
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $10
    lda $10
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $12
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $14
    lda $14
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $16
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $18
    lda $18
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $22
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $26
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2A
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2E
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $32
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $38
    sta $3C
    lda $3A
    sta $3E
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $3A
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $38
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $42
    inx
    inx
    sep #$20
    lda $400000,x
    xba
    lda $400001,x
    rep #$20
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l ors_pre

; >>> ESCBANK2_BODIES_END — new escbank2 bodies inserted before this line <<<

; ============================================================================
; xlat_dispatch — the AOT address-translation indirection ($94:F900).
; in: $40 = 68K PC lo16, $42 = PC bank, 16-bit A/X/Y. ojmp_hook (bank $00) jml's here after its
; gate check. Looks the PC up in the 2-level page table at $96:8000 (file $2B0000, built by
; tools/gen_xlat_table.py). HIT -> jml [native entry]; MISS -> jml inext (interpret as today).
; This replaces ojmp_hook's hardcoded cmp-chain AND escbank's ojmp_disp re-scan with one lookup.
; Bank-$00 PCs only for now (the table's jmp-state convention class); $42!=0 -> miss.
; ============================================================================
.org $F900
xlat_dispatch:
    ; CRITICAL scratch rule: the MISS path falls through to `jml inext`, and inext reads the interp
    ; 32-bit step counter $4A/$4C and stop marker $4E (`lda $4A; inc; ...; cmp $4C #$0800; bcs docap`).
    ; The old code used $4A/$4C/$4E as table-lookup scratch, so EVERY table miss corrupted the counter
    ; -- and any page whose sub-table offset >= $0800 (e.g. d5c4@$0800) tripped the cap -> docap halt
    ; -> the game diverged/ran away whenever escapes were enabled (escapes-on lockstep RED, off GREEN).
    ; Fix: use $96/$98 (escape-transient DP, dead on the miss path) and preserve X across the miss.
    rep #$30
    phx                      ; preserve X (interp decode state) for the miss path
    lda $42
    bne xd_miss              ; non-bank-0 target -> not in this table
    lda $40                  ; PC lo16
    xba                      ; low byte now = PC>>8 (page index)
    and #$00FF
    asl a                    ; *2 (2-byte page pointers)
    tax
    lda $968000,x            ; page[PC>>8] = sub-table byte-offset (0 = no escapes in page)
    beq xd_miss
    sta $96                  ; save sub-table offset (was $4C = step-counter hi)
    lda $40
    and #$00FF               ; PC low byte (entry index)
    sta $98                  ; (was $4E = stop marker)
    asl a                    ; *2
    clc
    adc $98                  ; + *1 = *3 (3-byte entries)
    clc
    adc $96                  ; + sub-table offset = blob offset of the entry
    tax
    lda $968002,x            ; native addr bank (high byte; ignore the mid byte overlap)
    and #$00FF
    sta $96                  ; native bank (was $4A = step-counter lo)
    lda $968000,x            ; native addr lo16
    bne xd_hit               ; lo16!=0 -> live entry (real entries are $8000+)
xd_miss:
    plx                      ; restore X
    jml.l inext
xd_hit:                      ; dispatch via push+RTL (avoids the Poppy-mis-sized jml [abs]).
    plx                      ; discard the preserved X (balance the stack before push+rtl)
    dec a                    ; A = native lo16 - 1 (RTL adds 1 to the pulled 16-bit PC)
    tax                      ; stash lo16-1
    sep #$20
    lda $96                  ; native bank
    pha                      ; push PBR FIRST (highest stack addr; RTL pulls it last)
    rep #$30
    txa
    pha                      ; push PCH:PCL (native lo16 - 1)
    rtl                      ; -> native bank:lo16
