.snes
; escbank.pasm — SA-1 "escape bank" (native escapes too big for bank-$00 gaps; runs at $92:8000,
; file $290000). The leading `.snes` is REQUIRED: it sets the target in source so the semantic
; analyzer creates a ProcessorState and tracks rep/sep — without it the analyzer sizes 16-bit
; immediates as 8-bit, drifting label addresses and breaking forward short branches. Bank-$00
; symbol constants are auto-generated from interp.sym by tools/gen_escbank_syms.py.

; >>> ESCBANK_SYMS — auto-generated by tools/gen_escbank_syms.py (do not edit) <<<
inext=$00D1A6
rdw40_l=$00E59E
wrw40_l=$00E5A2
rdb40_l=$00E5A6
wrb40_l=$00E5AA
push32_l=$00E5AE
rdw_ea_l=$00E5B2
readbyte_l=$00E5B6
op_rts_sentinel=$00EA2E
; <<< ESCBANK_SYMS <<<

    .org $8000
; --- transpiled from $000D96 (60 instrs) by tools/transpile.py [bank1] ---
entry_d96:
    rep #$30
    inc $0730            ; E1 marker
    ; re-simulate the jsr return-push the hook skipped (frame must match the real 68K)
    lda $40
    sta $54
    lda $42
    sta $56
    jsl.l push32_l
    lda $38
    sta $54
    lda $3A
    sta $56
    jsl.l push32_l
    lda $3C
    sta $38
    lda $3E
    sta $3A
    lda $30
    sta $54
    lda $32
    sta $56
    jsl.l push32_l
    lda $2C
    sta $54
    lda $2E
    sta $56
    jsl.l push32_l
    lda $28
    sta $54
    lda $2A
    sta $56
    jsl.l push32_l
    lda $24
    sta $54
    lda $26
    sta $56
    jsl.l push32_l
    lda $20
    sta $54
    lda $22
    sta $56
    jsl.l push32_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $18
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $14
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $10
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $0C
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $08
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $04
    jsl.l wrw40_l
    lda $3C
    sec
    sbc #$0002
    sta $3C
    ldx $3C
    lda $00
    jsl.l wrw40_l
    lda $38
    clc
    adc #$0008
    tax
    jsl.l rdw40_l
    sta $1C
    lda $34
    clc
    adc #$1CF6
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda $34
    clc
    adc #$20F2
    sta $2C
    lda $36
    adc #$0000
    sta $2E
    lda $34
    clc
    adc #$24EE
    sta $28
    lda $36
    adc #$0000
    sta $2A
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $30
    clc
    adc $9A
    sta $30
    lda $32
    adc $9C
    sta $32
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $2C
    clc
    adc $9A
    sta $2C
    lda $2E
    adc $9C
    sta $2E
    lda $1C
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $28
    clc
    adc $9A
    sta $28
    lda $2A
    adc $9C
    sta $2A
    lda $38
    clc
    adc #$0010
    tax
    jsl.l rdw40_l
    sta $22
    inx
    inx
    jsl.l rdw40_l
    sta $20
    lda $20
    clc
    adc #$0004
    sta $24
    lda $22
    adc #$0000
    sta $26
    lda $38
    clc
    adc #$0014
    tax
    jsl.l rdw40_l
    sta $1C
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $00
    lda #$00EA
    sta $04
    lda $38
    clc
    adc #$000C
    tax
    jsl.l rdw40_l
    sta $9E
    lda $04
    sec
    sbc $9E
    sta $04
Ld96_dd0:
    lda #$00FA
    sta $14
    lda $04
    sec
    sbc $14
    bvs Lfd96_1
    bpl Lfd96_2
    bra Lfd96_3
Lfd96_1:
    bmi Lfd96_2
    bra Lfd96_3
Lfd96_2:
    jmp Ld96_de0
Lfd96_3:
    lda $04
    sec
    sbc #$FFFA
    beq Lfd96_5
    bvs Lfd96_4
    bmi Lfd96_5
    bra Lfd96_6
Lfd96_4:
    bpl Lfd96_5
    bra Lfd96_6
Lfd96_5:
    jmp Ld96_de0
Lfd96_6:
    lda $04
    sta $14
Ld96_de0:
    lda $14
    sta $18
    lda $20
    clc
    adc #$0002
    sta $54
    lda $22
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $08
    lda $38
    clc
    adc #$000E
    tax
    jsl.l rdw40_l
    sta $0C
    lda $0C
    clc
    adc #$0000
    sta $0C
    lda $08
    sta $10
    lda $10
    asl a
    asl a
    asl a
    asl a
    sta $10
    lda $0C
    clc
    adc $10
    sta $0C
Ld96_df4:
    lda $18
    sta $14
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $24
    clc
    adc #$0002
    sta $24
    lda $26
    adc #$0000
    sta $26
    pla
    sta $10
    lda $10
    bne Lfd96_7
    jmp Ld96_e24
Lfd96_7:
    lda $0C
    sec
    sbc #$FFF0
    beq Lfd96_9
    bvs Lfd96_8
    bmi Lfd96_9
    bra Lfd96_10
Lfd96_8:
    bpl Lfd96_9
    bra Lfd96_10
Lfd96_9:
    jmp Ld96_e06
Lfd96_10:
    lda $0C
    sec
    sbc #$0180
    bvs Lfd96_11
    bmi Lfd96_12
    bra Lfd96_13
Lfd96_11:
    bpl Lfd96_12
    bra Lfd96_13
Lfd96_12:
    jmp Ld96_e0a
Lfd96_13:
Ld96_e06:
    lda #$00FA
    sta $14
Ld96_e0a:
    lda $1C
    bpl Lfd96_14
    jmp Ld96_e42
Lfd96_14:
    lda $10
    clc
    adc #$A000
    sta $10
    lda $10
    pha
    lda $28
    clc
    adc #$0000
    tax
    pla
    jsl.l wrw40_l
    lda $28
    clc
    adc #$0002
    sta $28
    lda $2A
    adc #$0000
    sta $2A
    lda $14
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    jsl.l wrw40_l
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $0C
    pha
    lda $2C
    clc
    adc #$0000
    tax
    pla
    jsl.l wrw40_l
    lda $2C
    clc
    adc #$0000
    tax
    jsl.l rdw40_l
    and #$01FF
    jsl.l wrw40_l
    lda $38
    clc
    adc #$000A
    tax
    jsl.l rdw40_l
    sta $10
    lda $2C
    clc
    adc #$0000
    tax
    jsl.l rdw40_l
    ora $10
    jsl.l wrw40_l
    lda $2C
    clc
    adc #$0002
    sta $2C
    lda $2E
    adc #$0000
    sta $2E
    lda $1C
    sec
    sbc #$0001
    sta $1C
Ld96_e24:
    lda $0C
    sec
    sbc #$0010
    sta $0C
    lda $08
    dec a
    sta $08
    cmp #$FFFF
    beq Lfd96_15
    jmp Ld96_df4
Lfd96_15:
    lda $04
    sec
    sbc #$0010
    sta $04
    lda $00
    dec a
    sta $00
    cmp #$FFFF
    beq Lfd96_16
    jmp Ld96_dd0
Lfd96_16:
    lda $1C
    bpl Lfd96_17
    jmp Ld96_e42
Lfd96_17:
    lda #$00FA
    sta $00
Ld96_e3c:
    lda $00
    pha
    lda $30
    clc
    adc #$0000
    tax
    pla
    jsl.l wrw40_l
    lda $30
    clc
    adc #$0002
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $1C
    dec a
    sta $1C
    cmp #$FFFF
    beq Lfd96_18
    jmp Ld96_e3c
Lfd96_18:
Ld96_e42:
    ldx $3C
    jsl.l rdw40_l
    sta $00
    lda $00
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $02
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $04
    lda $04
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $06
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $08
    lda $08
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $0C
    lda $0C
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $0E
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $10
    lda $10
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $12
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $14
    lda $14
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $16
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $18
    lda $18
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $1A
    lda $3C
    clc
    adc #$0002
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $22
    inx
    inx
    jsl.l rdw40_l
    sta $20
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $26
    inx
    inx
    jsl.l rdw40_l
    sta $24
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $2A
    inx
    inx
    jsl.l rdw40_l
    sta $28
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $2E
    inx
    inx
    jsl.l rdw40_l
    sta $2C
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $32
    inx
    inx
    jsl.l rdw40_l
    sta $30
    lda $3C
    clc
    adc #$0004
    sta $3C
    lda $38
    sta $3C
    lda $3A
    sta $3E
    ldx $3C
    jsl.l rdw40_l
    sta $3A
    inx
    inx
    jsl.l rdw40_l
    sta $38
    lda $3C
    clc
    adc #$0004
    sta $3C
    ldx $3C
    jsl.l rdw40_l
    sta $42
    inx
    inx
    jsl.l rdw40_l
    sta $40
    lda $3C
    clc
    adc #$0004
    sta $3C
    jml.l inext
