; Generated by tools/gen_vtime_esc5_root.py; do not edit.
; VTIME-only bank $F3 diagnostic; production routing remains bank $99.
inext=$00D0F5
push32_l=$00E5AE
readbyte_l=$00E5B6
rdw_ea_l=$00E5B2
ojmp_hook=$00D1B3
ibridge=$92F828
VTIME_ESC5_CHARGE=$F28900
VTIME_ESC5_FINISH=$F28B00

VTIME_ENABLE=$F28000
VTIME_FLAG_INTERPRETER_ONLY=$0002

.snes
; --- transpiled from $02429C (78 instrs) by tools/transpile.py [bank1] ---
    .org $8000
.a16
.i16
vtime_entry_2429c:
    rep #$30
    ; coroutine task body: NO return-push (entered by the op_rte resume hook, not a jsr)
    php
    rep #$30
    lda #$0001
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$2930
    tax
    lda $400000,x
    xba
    sec
    sbc #$0008
    bne Lf2429c_1
    jmp L2429c_242b2
Lf2429c_1:
    php
    rep #$30
    lda #$0002
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE jsr $23342.l -> ojmp_hook (callee --table escape, else interpret), resume br2429c_1
    lda #$42AC
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$3342
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_1:
    ; restore real 68K call return residue below A7: $0242AC
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$42AC
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0003
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE jsr $23e34.l -> ojmp_hook (callee --table escape, else interpret), resume br2429c_2
    lda #$42B2
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$3E34
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_2:
    ; restore real 68K call return residue below A7: $0242B2
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$42B2
    xba
    sta $400000,x
    xba
L2429c_242b2:
    php
    rep #$30
    lda #$0004
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE jsr $235e0.l -> ojmp_hook (callee --table escape, else interpret), resume br2429c_3
    lda #$42B8
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$35E0
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_3:
    ; restore real 68K call return residue below A7: $0242B8
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$42B8
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0005
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE jsr $25110.l -> ojmp_hook (callee --table escape, else interpret), resume br2429c_4
    lda #$42BE
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$5110
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_4:
    ; restore real 68K call return residue below A7: $0242BE
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$42BE
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0006
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE jsr $259ca.l -> ojmp_hook (callee --table escape, else interpret), resume br2429c_5
    lda #$42C4
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$59CA
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_5:
    ; restore real 68K call return residue below A7: $0242C4
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$42C4
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0007
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$3CB4
    tax
    lda $400000,x
    xba
    inc a
    dec a
    bne Lf2429c_2
    jmp L2429c_242d4
Lf2429c_2:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    php
    rep #$30
    lda #$0008
    jsr vtime_esc5_charge_gateway
    plp
    lda #$0000
    pha
    lda $34
    clc
    adc #$3CB4
    tax
    pla
    xba
    sta $400000,x
    xba
    jmp L2429c_242da
L2429c_242d4:
    php
    rep #$30
    lda #$0009
    jsr vtime_esc5_charge_gateway
    plp
    lda #$0001
    pha
    lda $34
    clc
    adc #$3CB4
    tax
    pla
    xba
    sta $400000,x
    xba
L2429c_242da:
    php
    rep #$30
    lda #$000A
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$365E
    sta $30
    lda $36
    adc #$0000
    sta $32
    lda #$0004
    sta $00
L2429c_242e2:
    php
    rep #$30
    lda #$000B
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0019
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    jmp vtime_h2429c_tst_byte19_branch
Lf2429c_3:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    php
    rep #$30
    lda #$000C
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0016
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    bne Lf2429c_4
    jmp L2429c_24324
Lf2429c_4:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    php
    rep #$30
    lda #$000D
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0016
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0001
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $18
    lda $18
    sec
    sbc #$FF00
    beq Lf2429c_7
    bvs Lf2429c_5
    bpl Lf2429c_6
    bra Lf2429c_7
Lf2429c_5:
    bmi Lf2429c_6
    bra Lf2429c_7
Lf2429c_6:
    jmp L2429c_2430a
Lf2429c_7:
    php
    rep #$30
    lda #$000E
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_6
    lda #$4306
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_6:
    ; restore real 68K call return residue below A7: $024306
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$4306
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$000F
    jsr vtime_esc5_charge_gateway
    plp
    jmp L2429c_243da
L2429c_2430a:
    php
    rep #$30
    lda #$0010
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    bne Lf2429c_8
    jmp L2429c_243da
Lf2429c_8:
    php
    rep #$30
    lda #$0011
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $0C
    lda $30
    clc
    adc #$000A
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0010
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    jmp L2429c_243da
L2429c_24324:
    php
    rep #$30
    lda #$0012
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $18
    lda $18
    sec
    sbc #$FF00
    beq Lf2429c_11
    bvs Lf2429c_9
    bpl Lf2429c_10
    bra Lf2429c_11
Lf2429c_9:
    bmi Lf2429c_10
    bra Lf2429c_11
Lf2429c_10:
    jmp L2429c_24338
Lf2429c_11:
    php
    rep #$30
    lda #$0013
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_7
    lda #$4334
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_7:
    ; restore real 68K call return residue below A7: $024334
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$4334
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0014
    jsr vtime_esc5_charge_gateway
    plp
    jmp L2429c_243da
L2429c_24338:
    php
    rep #$30
    lda #$0015
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$2932
    tax
    lda $400000,x
    xba
    sec
    sbc #$0002
    bne Lf2429c_12
    jmp L2429c_2434e
Lf2429c_12:
    php
    rep #$30
    lda #$0016
    jsr vtime_esc5_charge_gateway
    plp
    lda $34
    clc
    adc #$2A32
    tax
    lda $400000,x
    xba
    sta $0C
    lda $30
    clc
    adc #$0010
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$000A
    tax
    lda $400000,x
    xba
    sec
    sbc $0C
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    xba
    sta $400000,x
    xba
L2429c_2434e:
    php
    rep #$30
    lda #$0017
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0014
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0000
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $30
    clc
    adc #$0002
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $24
    lda $9E
    sta $26
    lda $24
    clc
    adc #$0000
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $9E
    lda $24
    clc
    adc #$0002
    sta $54
    lda $26
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    sta $20
    lda $9E
    sta $22
    lda $20
    clc
    adc #$0000
    sta $54
    lda $22
    adc #$0000
    sta $56
    jsl.l push32_l
    lda $30
    clc
    adc #$0010
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$000E
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda #$1800
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $30
    clc
    adc #$0012
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l rdw_ea_l
    pha
    lda $3C
    sec
    sbc #$0002
    sta $3C
    lda $3E
    sbc #$0000
    sta $3E
    lda $3C
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1C8A
    tax
    lda $400000,x
    xba
    sta $22
    inx
    inx
    lda $400000,x
    xba
    sta $20
    ; INDIRECT-BRIDGE jsr (a0) -> bank-$92 ibridge (standard escape or interpret); $00FA sentinel for bank $99, resume br2429c_8
    lda #$436E
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda $20
    sta $40
    lda $22
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_8:
    php
    rep #$30
    lda #$0018
    jsr vtime_esc5_charge_gateway
    plp
    lda $3C
    clc
    adc #$000E
    sta $3C
    lda $3E
    adc #$0000
    sta $3E
    ; CALL-BRIDGE bsr.w $2443a -> ojmp_hook (callee --table escape, else interpret), resume br2429c_9
    lda #$4378
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$443A
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_9:
    ; restore real 68K call return residue below A7: $024378
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$4378
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$0019
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0019
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sec
    sbc #$02
    rep #$20
    bne Lf2429c_13
    jmp L2429c_24392
Lf2429c_13:
    php
    rep #$30
    lda #$001A
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0018
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sec
    sbc #$02
    rep #$20
    beq Lf2429c_14
    jmp L2429c_24392
Lf2429c_14:
    php
    rep #$30
    lda #$001B
    jsr vtime_esc5_charge_gateway
    plp
    lda #$0002
    pha
    lda $30
    clc
    adc #$0019
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
L2429c_24392:
    php
    rep #$30
    lda #$001C
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$0017
    tax
    lda $400000,x
    and #$00FF
    sec
    sbc #$0001
    php
    pha
    lda #$0000
    rol a
    eor #$0001
    sta $A2
    pla
    plp
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0017
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    beq Lf2429c_15
    jmp L2429c_243da
Lf2429c_15:
    php
    sep #$20
    pla
    rep #$30
    and #$00FF
    sta $50
    and #$0002
    sta $60
    lda $50
    and #$0080
    sta $70
    stz $72
    stz $6E
    php
    rep #$30
    lda #$001D
    jsr vtime_esc5_charge_gateway
    plp
    lda #$451A
    sta $28
    lda #$0002
    sta $2A
    lda $30
    clc
    adc #$0018
    sta $54
    lda $32
    adc #$0000
    sta $52
    jsl.l readbyte_l
    sep #$20
    sta $04
    rep #$20
    lda $04
    sep #$20
    sec
    sbc #$05
    rep #$20
    beq Lf2429c_16
    jmp L2429c_243b8
Lf2429c_16:
    php
    rep #$30
    lda #$001E
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE bsr.w $243e8 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_10
    lda #$43B4
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$43E8
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_10:
    ; restore real 68K call return residue below A7: $0243B4
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$43B4
    xba
    sta $400000,x
    xba
    php
    rep #$30
    lda #$001F
    jsr vtime_esc5_charge_gateway
    plp
    jmp L2429c_243da
L2429c_243b8:
    php
    rep #$30
    lda #$0020
    jsr vtime_esc5_charge_gateway
    plp
    lda $04
    and #$00FF
    eor #$0080
    sec
    sbc #$0080
    sta $04
    lda $04
    sta $9A
    lda $9A
    asl a
    lda #$0000
    sbc #$0000
    eor #$FFFF
    sta $9C
    lda $28
    clc
    adc $9A
    sta $28
    lda $2A
    adc $9C
    sta $2A
    lda $28
    clc
    adc #$0000
    sta $54
    lda $2A
    adc #$0000
    sta $52
    jsl.l readbyte_l
    pha
    lda $30
    clc
    adc #$0017
    tax
    pla
    sep #$20
    sta $400000,x
    rep #$20
    lda $30
    clc
    adc #$0018
    tax
    lda $400000,x
    and #$00FF
    clc
    adc #$0001
    php
    pha
    lda #$0000
    rol a
    sta $A2
    pla
    plp
    sep #$20
    sta $400000,x
    rep #$20
    lda $24
    clc
    adc #$0004
    sta $24
    lda $26
    adc #$0000
    sta $26
    lda $24
    sta $9A
    lda $26
    sta $9C
    lda $9C
    pha
    ldx $30
    pla
    xba
    sta $400000,x
    xba
    lda $9A
    pha
    lda $30
    clc
    adc #$0002
    tax
    pla
    xba
    sta $400000,x
    xba
    lda $34
    clc
    adc #$1CCC
    tax
    lda $400000,x
    xba
    sec
    sbc #$0008
    bne Lf2429c_17
    jmp L2429c_243da
Lf2429c_17:
    php
    rep #$30
    lda #$0021
    jsr vtime_esc5_charge_gateway
    plp
    ; CALL-BRIDGE bsr.w $244d4 -> ojmp_hook (callee --table escape, else interpret), resume br2429c_11
    lda #$43DA
    sta $54
    lda #$0002
    sta $56
    jsl.l push32_l
    lda #$44D4
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_ojmp_gateway
br2429c_11:
    ; restore real 68K call return residue below A7: $0243DA
    lda $3C
    sec
    sbc #$0004
    tax
    lda #$0002
    xba
    sta $400000,x
    xba
    inx
    inx
    lda #$43DA
    xba
    sta $400000,x
    xba
L2429c_243da:
    php
    rep #$30
    lda #$0022
    jsr vtime_esc5_charge_gateway
    plp
    lda $30
    clc
    adc #$001E
    sta $30
    lda $32
    adc #$0000
    sta $32
    lda $00
    dec a
    sta $00
    cmp #$FFFF
    beq Lf2429c_18
    jmp L2429c_242e2
Lf2429c_18:
    php
    rep #$30
    lda #$0023
    jsr vtime_esc5_charge_gateway
    plp
    lda #$429A
    sta $40
    lda #$0002
    sta $42
    jmp vtime_esc5_inext_gateway

; Preserve the active a976 terminal TST.B CCR repair in the diagnostic copy.
vtime_h2429c_tst_byte19_branch:
    stz $70
    stz $72
    stz $6E
    stz $60
    and #$00FF
    beq vtime_h2429c_tst_byte19_zero
    and #$0080
    beq vtime_h2429c_tst_byte19_nonzero
    inc $70
vtime_h2429c_tst_byte19_nonzero:
    jmp Lf2429c_3
vtime_h2429c_tst_byte19_zero:
    inc $60
    jmp L2429c_243da

; The generated block prologue has PHP immediately before the local JSR.
; A due result discards both frames and resumes the interpreter at the exact
; original block PC selected by the F2 ledger.
vtime_esc5_charge_gateway:
    rep #$30
    jsl.l VTIME_ESC5_CHARGE
    cmp #$0001
    beq vtime_esc5_charge_due
    rts
vtime_esc5_charge_due:
    pla
    plp
    jml.l inext

; Each child bridge has already pushed its genuine 68000 return and published
; the child PC.  Flush the completed parent JSR/BSR block, then deliberately
; interpret the direct child.  A due result keeps that exact PC/stack state
; for IRQ delivery; both paths use inext and therefore bypass native dispatch
; for the child entry itself.
vtime_esc5_ojmp_gateway:
    rep #$30
    jsl.l VTIME_ESC5_FINISH
    stz $071A
    jml.l inext

; The terminal trap/yield PC is already in $40:$42.  Commit the last block and
; leave through the ordinary interpreter path regardless of whether it became
; the deadline-crossing block.
vtime_esc5_inext_gateway:
    rep #$30
    jsl.l VTIME_ESC5_FINISH
    jml.l inext

; op_rts has already consumed the genuine child return when the VTIME-only
; bank-$00 patch reaches this front end.  Child execution temporarily clears
; the native gate, so recognize these exact bank-$02 returns before consulting
; that gate, restore the mode-appropriate value, and resume the matching
; bank-$F3 continuation.  Ordinary VTIME restores the native gate; the explicit
; interpreter-only diagnostic must leave it clear.  Every miss reproduces
; op_rts_sentinel/op_rts_norm: $00FF is a local bank-$00 continuation, gate-on
; uses xlat_dispatch, and gate-off interprets.
vtime_esc5_return_dispatch:
    rep #$30
    lda $42
    cmp #$0002
    beq vtime_esc5_return_bank2
    jmp vtime_esc5_return_miss
vtime_esc5_return_bank2:
    lda $40
    cmp #$42AC
    bne vtime_esc5_return_next_1
    jsr vtime_esc5_restore_gate
    jmp br2429c_1
vtime_esc5_return_next_1:
    cmp #$42B2
    bne vtime_esc5_return_next_2
    jsr vtime_esc5_restore_gate
    jmp br2429c_2
vtime_esc5_return_next_2:
    cmp #$42B8
    bne vtime_esc5_return_next_3
    jsr vtime_esc5_restore_gate
    jmp br2429c_3
vtime_esc5_return_next_3:
    cmp #$42BE
    bne vtime_esc5_return_next_4
    jsr vtime_esc5_restore_gate
    jmp br2429c_4
vtime_esc5_return_next_4:
    cmp #$42C4
    bne vtime_esc5_return_next_5
    jsr vtime_esc5_restore_gate
    jmp br2429c_5
vtime_esc5_return_next_5:
    cmp #$4306
    bne vtime_esc5_return_next_6
    jsr vtime_esc5_restore_gate
    jmp br2429c_6
vtime_esc5_return_next_6:
    cmp #$4334
    bne vtime_esc5_return_next_7
    jsr vtime_esc5_restore_gate
    jmp br2429c_7
vtime_esc5_return_next_7:
    cmp #$436E
    bne vtime_esc5_return_next_8
    jsr vtime_esc5_restore_gate
    jmp br2429c_8
vtime_esc5_return_next_8:
    cmp #$4378
    bne vtime_esc5_return_next_9
    jsr vtime_esc5_restore_gate
    jmp br2429c_9
vtime_esc5_return_next_9:
    cmp #$43B4
    bne vtime_esc5_return_next_10
    jsr vtime_esc5_restore_gate
    jmp br2429c_10
vtime_esc5_return_next_10:
    cmp #$43DA
    bne vtime_esc5_return_next_11
    jsr vtime_esc5_restore_gate
    jmp br2429c_11
vtime_esc5_return_next_11:
vtime_esc5_return_miss:
    lda $42
    cmp #$00FF
    bne vtime_esc5_return_normal
    jmp ($0040)
vtime_esc5_return_normal:
    lda $071A
    beq vtime_esc5_return_interpret
    jml.l $94F900
vtime_esc5_return_interpret:
    jml.l inext

; The enable byte is followed immediately by executable code, so mask only the
; interpreter-only bit from the 16-bit long read.  Normal VTIME keeps the
; established native child/parent behavior; flag $0002 prevents this diagnostic
; root from leaking a global $071A=1 back into an interpreter-only campaign.
vtime_esc5_restore_gate:
    lda.l VTIME_ENABLE
    and #VTIME_FLAG_INTERPRETER_ONLY
    bne vtime_esc5_restore_gate_off
    lda #$0001
    sta $071A
    rts
vtime_esc5_restore_gate_off:
    stz $071A
    rts
vtime_esc5_return_dispatch_end:
vtime_esc5_root_end:
